// C&C Generals - Building Definitions Database

const std = @import("std");

pub const BuildingType = enum {
    // USA Buildings - Core
    USA_Command_Center,
    USA_Barracks,
    USA_Supply_Center,
    USA_War_Factory,
    USA_Airfield,
    USA_Strategy_Center,
    USA_Detention_Camp,
    USA_Patriot_Battery,
    USA_Fire_Base,
    USA_Particle_Cannon,

    // USA Buildings - Power & Economy
    USA_Cold_Fusion_Reactor,
    USA_Supply_Drop_Zone,

    // USA Buildings - General Specific (Air Force)
    USA_Advanced_Airfield,
    USA_Advanced_Strategy_Center,
    USA_Point_Defense_System,

    // USA Buildings - General Specific (Superweapon)
    USA_Advanced_Particle_Cannon,
    USA_EMP_Patriot_Battery,
    USA_Particle_Uplink_Cannon,

    // USA Buildings - General Specific (Infantry)
    USA_Advanced_Barracks,
    USA_Advanced_Detention_Camp,
    USA_Patriot_Bunker,

    // USA Buildings - Defensive
    USA_Advanced_Fire_Base,
    USA_Patriot_Missile_System,
    USA_EMP_Tower,
    USA_Laser_Defense_Turret,

    // USA Buildings - Support
    USA_Tech_Repair_Facility,
    USA_Advanced_Command_Center,
    USA_Radar_Station,
    USA_Chinook_Pad,

    // China Buildings
    China_Command_Center,
    China_Barracks,
    China_Supply_Center,
    China_War_Factory,
    China_Airfield,
    China_Propaganda_Center,
    China_Nuclear_Reactor,
    China_Gattling_Cannon,
    China_Bunker,
    China_Nuclear_Missile,

    // China Buildings - Tech & Support
    China_Internet_Center,
    China_Speaker_Tower,
    China_Listening_Outpost,

    // China Buildings - General Specific (Tank General)
    China_Advanced_War_Factory,
    China_Autoloader_Artillery,
    China_Nuclear_Tank_Bunker,

    // China Buildings - General Specific (Nuke General)
    China_Advanced_Nuclear_Reactor,
    China_Tactical_Nuke_Silo,
    China_Nuclear_Artillery_Platform,

    // China Buildings - General Specific (Infantry General)
    China_Advanced_Barracks,
    China_Fortified_Bunker,
    China_Minigun_Platform,

    // China Buildings - Defensive
    China_Advanced_Gattling_Cannon,
    China_Flame_Turret,
    China_Tank_Trap,
    China_Laser_Turret,

    // China Buildings - Support
    China_Helix_Pad,
    China_Advanced_Command_Center,
    China_ECM_Station,

    // GLA Buildings
    GLA_Command_Center,
    GLA_Barracks,
    GLA_Supply_Stash,
    GLA_Arms_Dealer,
    GLA_Black_Market,
    GLA_Palace,
    GLA_Tunnel_Network,
    GLA_Stinger_Site,
    GLA_SCUD_Storm,

    // GLA Buildings - Tech & Support
    GLA_Radar_Van_Station,
    GLA_Arms_Cache,
    GLA_Fake_Command_Center,

    // GLA Buildings - General Specific (Demolition)
    GLA_Advanced_Arms_Dealer,
    GLA_Demo_Trap_Factory,
    GLA_Explosive_Bunker,

    // GLA Buildings - General Specific (Toxin)
    GLA_Toxin_Lab,
    GLA_Anthrax_Bomb_Silo,
    GLA_Toxin_Tunnel,

    // GLA Buildings - General Specific (Stealth)
    GLA_Camouflage_Net,
    GLA_Stealth_Tunnel,
    GLA_GPS_Scrambler,

    // GLA Buildings - Defensive
    GLA_RPG_Trooper_Outpost,
    GLA_Demo_Trap,
    GLA_Tunnel_Entrance,
    GLA_Booby_Trap,

    // GLA Buildings - Support
    GLA_Repair_Bay,
    GLA_Advanced_Black_Market,
    GLA_Salvage_Yard,
    GLA_Worker_Camp,

    // More buildings...
};

pub const BuildingDef = struct {
    name: []const u8,
    display_name: []const u8,
    building_type: BuildingType,
    cost: u32,
    build_time: f32,
    health: u32,
    armor: u32,
    power: i32, // Negative = consumes, Positive = generates
    vision_range: f32,
    can_attack: bool,
    weapons: []const []const u8,
    produces: []const []const u8,
    upgrades: []const []const u8,
    size_x: f32,
    size_y: f32,
    description: []const u8,
};

pub const BUILDING_DATABASE = [_]BuildingDef{
    .{
        .name = "USA_Command_Center",
        .display_name = "Command Center",
        .building_type = .USA_Command_Center,
        .cost = 2000,
        .build_time = 30.0,
        .health = 5000,
        .armor = 30,
        .power = 0,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Dozer"},
        .upgrades = &[_][]const u8{},
        .size_x = 6.0,
        .size_y = 6.0,
        .description = "Main construction yard. Produces construction dozers. If destroyed, you cannot build.",
    },
    .{
        .name = "USA_Barracks",
        .display_name = "Barracks",
        .building_type = .USA_Barracks,
        .cost = 500,
        .build_time = 15.0,
        .health = 2000,
        .armor = 10,
        .power = -5,
        .vision_range = 180.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Ranger", "Missile_Defender", "Pathfinder", "Colonel_Burton" },
        .upgrades = &[_][]const u8{ "Advanced_Training", "Capture_Building" },
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Trains infantry units and provides infantry upgrades.",
    },
    .{
        .name = "USA_Supply_Center",
        .display_name = "Supply Center",
        .building_type = .USA_Supply_Center,
        .cost = 2000,
        .build_time = 25.0,
        .health = 3000,
        .armor = 15,
        .power = 0,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Supply_Truck", "Chinook"},
        .upgrades = &[_][]const u8{},
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Generates supplies. Supply trucks collect from here. Can be upgraded with additional supply pads.",
    },
    .{
        .name = "USA_War_Factory",
        .display_name = "War Factory",
        .building_type = .USA_War_Factory,
        .cost = 2000,
        .build_time = 30.0,
        .health = 3500,
        .armor = 20,
        .power = -10,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Humvee", "Tomahawk", "Crusader", "Paladin", "Avenger", "Ambulance" },
        .upgrades = &[_][]const u8{ "Composite_Armor", "TOW_Missile", "Battle_Drone" },
        .size_x = 6.0,
        .size_y = 5.0,
        .description = "Produces vehicles and provides vehicle upgrades.",
    },
    .{
        .name = "USA_Airfield",
        .display_name = "Airfield",
        .building_type = .USA_Airfield,
        .cost = 2500,
        .build_time = 35.0,
        .health = 3000,
        .armor = 15,
        .power = -15,
        .vision_range = 220.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Comanche", "Raptor", "Stealth_Fighter", "Aurora_Alpha" },
        .upgrades = &[_][]const u8{ "Countermeasures", "Laser_Missiles" },
        .size_x = 8.0,
        .size_y = 6.0,
        .description = "Produces aircraft and provides aircraft upgrades. Can hold up to 4 aircraft.",
    },
    .{
        .name = "USA_Patriot_Battery",
        .display_name = "Patriot Missile Battery",
        .building_type = .USA_Patriot_Battery,
        .cost = 1000,
        .build_time = 20.0,
        .health = 1500,
        .armor = 5,
        .power = -10,
        .vision_range = 200.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Patriot_Missile"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Advanced_Control_Rods"},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Anti-aircraft defense. Fires missiles at enemy aircraft.",
    },
    .{
        .name = "USA_Particle_Cannon",
        .display_name = "Particle Cannon",
        .building_type = .USA_Particle_Cannon,
        .cost = 5000,
        .build_time = 90.0,
        .health = 5000,
        .armor = 25,
        .power = -50,
        .vision_range = 300.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 6.0,
        .size_y = 6.0,
        .description = "Superweapon. Fires a devastating particle beam from orbit. 5 minute charge time.",
    },

    // ========================================
    // USA Buildings - Power & Economy
    // ========================================
    .{
        .name = "USA_Cold_Fusion_Reactor",
        .display_name = "Cold Fusion Reactor",
        .building_type = .USA_Cold_Fusion_Reactor,
        .cost = 800,
        .build_time = 20.0,
        .health = 1500,
        .armor = 5,
        .power = 10,
        .vision_range = 150.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Provides 10 power. Clean energy with no radiation risk.",
    },
    .{
        .name = "USA_Supply_Drop_Zone",
        .display_name = "Supply Drop Zone",
        .building_type = .USA_Supply_Drop_Zone,
        .cost = 1500,
        .build_time = 25.0,
        .health = 2500,
        .armor = 15,
        .power = -5,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Chinook supply drop zone. Generates income periodically from airlifted supplies.",
    },

    // ========================================
    // USA Buildings - Air Force General
    // ========================================
    .{
        .name = "USA_Advanced_Airfield",
        .display_name = "Advanced Airfield",
        .building_type = .USA_Advanced_Airfield,
        .cost = 2500,
        .build_time = 35.0,
        .health = 4000,
        .armor = 20,
        .power = -20,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Comanche", "Raptor", "Aurora_Alpha", "King_Raptor" },
        .upgrades = &[_][]const u8{ "Countermeasures", "Advanced_Training" },
        .size_x = 6.0,
        .size_y = 6.0,
        .description = "Air Force General's airfield. Produces advanced aircraft 25% faster.",
    },
    .{
        .name = "USA_Advanced_Strategy_Center",
        .display_name = "Advanced Strategy Center",
        .building_type = .USA_Advanced_Strategy_Center,
        .cost = 2500,
        .build_time = 30.0,
        .health = 3000,
        .armor = 20,
        .power = -15,
        .vision_range = 300.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "A10_Strike", "Spectre_Gunship", "Carpet_Bombing" },
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Air Force General's strategy center. Unlocks advanced air support powers.",
    },
    .{
        .name = "USA_Point_Defense_System",
        .display_name = "Point Defense Laser",
        .building_type = .USA_Point_Defense_System,
        .cost = 1800,
        .build_time = 22.0,
        .health = 2000,
        .armor = 15,
        .power = -15,
        .vision_range = 250.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Point_Defense_Laser"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Air Force General's laser defense. Shoots down incoming missiles and aircraft.",
    },

    // ========================================
    // USA Buildings - Superweapon General
    // ========================================
    .{
        .name = "USA_Advanced_Particle_Cannon",
        .display_name = "Advanced Particle Cannon",
        .building_type = .USA_Advanced_Particle_Cannon,
        .cost = 6000,
        .build_time = 100.0,
        .health = 6000,
        .armor = 30,
        .power = -75,
        .vision_range = 350.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 7.0,
        .size_y = 7.0,
        .description = "Superweapon General's enhanced particle cannon. 25% faster charge, larger blast radius.",
    },
    .{
        .name = "USA_EMP_Patriot_Battery",
        .display_name = "EMP Patriot Battery",
        .building_type = .USA_EMP_Patriot_Battery,
        .cost = 1500,
        .build_time = 20.0,
        .health = 2500,
        .armor = 15,
        .power = -10,
        .vision_range = 250.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"EMP_Patriot_Missile"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Superweapon General's EMP-armed Patriot. Disables vehicles and aircraft.",
    },
    .{
        .name = "USA_Particle_Uplink_Cannon",
        .display_name = "Particle Uplink Cannon",
        .building_type = .USA_Particle_Uplink_Cannon,
        .cost = 5500,
        .build_time = 85.0,
        .health = 5500,
        .armor = 28,
        .power = -60,
        .vision_range = 320.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 6.5,
        .size_y = 6.5,
        .description = "Superweapon General's secondary particle cannon with satellite uplink.",
    },

    // ========================================
    // USA Buildings - Infantry General
    // ========================================
    .{
        .name = "USA_Advanced_Barracks",
        .display_name = "Advanced Barracks",
        .building_type = .USA_Advanced_Barracks,
        .cost = 700,
        .build_time = 18.0,
        .health = 2500,
        .armor = 15,
        .power = -8,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Ranger", "Missile_Defender", "Pathfinder", "Advanced_Ranger" },
        .upgrades = &[_][]const u8{ "Advanced_Training", "Capture_Building", "Flash_Bang" },
        .size_x = 4.5,
        .size_y = 4.5,
        .description = "Infantry General's barracks. Trains infantry 25% faster with free upgrades.",
    },
    .{
        .name = "USA_Advanced_Detention_Camp",
        .display_name = "Advanced Detention Camp",
        .building_type = .USA_Advanced_Detention_Camp,
        .cost = 1200,
        .build_time = 22.0,
        .health = 3000,
        .armor = 20,
        .power = -5,
        .vision_range = 180.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Infantry General's detention camp. Generates more cash per prisoner.",
    },
    .{
        .name = "USA_Patriot_Bunker",
        .display_name = "Patriot Bunker",
        .building_type = .USA_Patriot_Bunker,
        .cost = 1200,
        .build_time = 18.0,
        .health = 3500,
        .armor = 20,
        .power = -8,
        .vision_range = 220.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Patriot_Missile", "Bunker_Weapons"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Infantry General's Patriot with bunker. Garrison infantry for additional firepower.",
    },

    // ========================================
    // USA Buildings - Defensive Structures
    // ========================================
    .{
        .name = "USA_Advanced_Fire_Base",
        .display_name = "Advanced Fire Base",
        .building_type = .USA_Advanced_Fire_Base,
        .cost = 2200,
        .build_time = 28.0,
        .health = 4500,
        .armor = 25,
        .power = -20,
        .vision_range = 300.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Patriot_Missile", "TOW_Missile", "50_Cal_MG"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "TOW_Missile", "Advanced_Training" },
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Enhanced Fire Base with multiple weapon systems and drone support.",
    },
    .{
        .name = "USA_Patriot_Missile_System",
        .display_name = "Patriot Missile System",
        .building_type = .USA_Patriot_Missile_System,
        .cost = 1400,
        .build_time = 20.0,
        .health = 2800,
        .armor = 18,
        .power = -12,
        .vision_range = 280.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Dual_Patriot_Missile"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.5,
        .size_y = 3.5,
        .description = "Advanced Patriot system with dual missile launchers. Superior anti-air coverage.",
    },
    .{
        .name = "USA_EMP_Tower",
        .display_name = "EMP Defense Tower",
        .building_type = .USA_EMP_Tower,
        .cost = 1600,
        .build_time = 22.0,
        .health = 2200,
        .armor = 15,
        .power = -15,
        .vision_range = 250.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"EMP_Burst"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Superweapon General's EMP tower. Disables enemy vehicles in area.",
    },
    .{
        .name = "USA_Laser_Defense_Turret",
        .display_name = "Laser Defense Turret",
        .building_type = .USA_Laser_Defense_Turret,
        .cost = 1700,
        .build_time = 24.0,
        .health = 2500,
        .armor = 18,
        .power = -18,
        .vision_range = 260.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Defense_Laser"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Air Force General's laser turret. Effective vs aircraft and missiles.",
    },

    // ========================================
    // USA Buildings - Support Structures
    // ========================================
    .{
        .name = "USA_Tech_Repair_Facility",
        .display_name = "Tech Repair Facility",
        .building_type = .USA_Tech_Repair_Facility,
        .cost = 1200,
        .build_time = 20.0,
        .health = 2000,
        .armor = 10,
        .power = -10,
        .vision_range = 180.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Repairs nearby vehicles automatically. Provides armor upgrade research.",
    },
    .{
        .name = "USA_Advanced_Command_Center",
        .display_name = "Advanced Command Center",
        .building_type = .USA_Advanced_Command_Center,
        .cost = 2500,
        .build_time = 35.0,
        .health = 6000,
        .armor = 35,
        .power = 5,
        .vision_range = 300.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Dozer"},
        .upgrades = &[_][]const u8{},
        .size_x = 6.5,
        .size_y = 6.5,
        .description = "Upgraded command center with improved armor and power generation.",
    },
    .{
        .name = "USA_Radar_Station",
        .display_name = "Radar Station",
        .building_type = .USA_Radar_Station,
        .cost = 800,
        .build_time = 15.0,
        .health = 1500,
        .armor = 8,
        .power = -5,
        .vision_range = 500.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Provides radar coverage. Detects stealth units and extends vision range.",
    },
    .{
        .name = "USA_Chinook_Pad",
        .display_name = "Chinook Pad",
        .building_type = .USA_Chinook_Pad,
        .cost = 1500,
        .build_time = 20.0,
        .health = 2500,
        .armor = 12,
        .power = -8,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Chinook", "Combat_Chinook", "Medical_Chinook" },
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Secondary airfield for Chinook helicopters. Supports supply operations.",
    },

    // ========================================
    // USA Buildings - Core (Continued)
    // ========================================
    .{
        .name = "USA_Strategy_Center",
        .display_name = "Strategy Center",
        .building_type = .USA_Strategy_Center,
        .cost = 2500,
        .build_time = 40.0,
        .health = 2500,
        .armor = 15,
        .power = -10,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "Hold_The_Line", "Search_And_Destroy", "Bombardment" },
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Advanced tactics building. Provides strategic bonuses to all units.",
    },
    .{
        .name = "USA_Detention_Camp",
        .display_name = "Detention Camp",
        .building_type = .USA_Detention_Camp,
        .cost = 1000,
        .build_time = 20.0,
        .health = 2000,
        .armor = 10,
        .power = -5,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Generates income from captured enemy soldiers. $5 per prisoner.",
    },
    .{
        .name = "USA_Fire_Base",
        .display_name = "Fire Base",
        .building_type = .USA_Fire_Base,
        .cost = 800,
        .build_time = 15.0,
        .health = 1800,
        .armor = 8,
        .power = -5,
        .vision_range = 220.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"M249_SAW"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{"TOW_Missile"},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Defensive bunker. Holds 4 infantry. Can be upgraded with TOW missiles.",
    },

    // ========================================
    // China Buildings
    // ========================================
    .{
        .name = "China_Command_Center",
        .display_name = "Command Center",
        .building_type = .China_Command_Center,
        .cost = 2000,
        .build_time = 30.0,
        .health = 5500,
        .armor = 35,
        .power = 0,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Dozer"},
        .upgrades = &[_][]const u8{},
        .size_x = 6.0,
        .size_y = 6.0,
        .description = "Chinese construction yard. Produces dozers.",
    },
    .{
        .name = "China_Nuclear_Missile",
        .display_name = "Nuclear Missile Silo",
        .building_type = .China_Nuclear_Missile,
        .cost = 5000,
        .build_time = 90.0,
        .health = 5000,
        .armor = 30,
        .power = -50,
        .vision_range = 300.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Superweapon. Launches a nuclear missile at target location. 6 minute charge time.",
    },
    .{
        .name = "GLA_SCUD_Storm",
        .display_name = "SCUD Storm",
        .building_type = .GLA_SCUD_Storm,
        .cost = 5000,
        .build_time = 90.0,
        .health = 4000,
        .armor = 20,
        .power = 0,
        .vision_range = 300.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "Anthrax_Beta" },
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Superweapon. Launches 9 SCUD missiles in a grid pattern. 5 minute charge time.",
    },
    .{
        .name = "China_Barracks",
        .display_name = "Barracks",
        .building_type = .China_Barracks,
        .cost = 500,
        .build_time = 15.0,
        .health = 2200,
        .armor = 12,
        .power = -5,
        .vision_range = 180.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Red_Guard", "Tank_Hunter", "Hacker", "Black_Lotus" },
        .upgrades = &[_][]const u8{ "Nationalism", "Capture_Building" },
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Trains Chinese infantry units and provides upgrades.",
    },
    .{
        .name = "China_Supply_Center",
        .display_name = "Supply Center",
        .building_type = .China_Supply_Center,
        .cost = 2000,
        .build_time = 25.0,
        .health = 3200,
        .armor = 18,
        .power = 0,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Supply_Truck"},
        .upgrades = &[_][]const u8{},
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Chinese supply depot. More durable than USA equivalent.",
    },
    .{
        .name = "China_War_Factory",
        .display_name = "War Factory",
        .building_type = .China_War_Factory,
        .cost = 2000,
        .build_time = 30.0,
        .health = 3800,
        .armor = 22,
        .power = -10,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Battlemaster", "Gattling_Tank", "Troop_Crawler", "Dragon_Tank", "Inferno_Cannon", "Nuke_Cannon", "Overlord", "ECM_Tank" },
        .upgrades = &[_][]const u8{ "Chain_Guns", "Black_Napalm", "Nuclear_Shells" },
        .size_x = 6.0,
        .size_y = 5.0,
        .description = "Produces Chinese vehicles and upgrades.",
    },
    .{
        .name = "China_Airfield",
        .display_name = "Airfield",
        .building_type = .China_Airfield,
        .cost = 2000,
        .build_time = 32.0,
        .health = 2800,
        .armor = 14,
        .power = -12,
        .vision_range = 220.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "MiG", "Helix" },
        .upgrades = &[_][]const u8{ "Black_Napalm", "Nationalism" },
        .size_x = 8.0,
        .size_y = 6.0,
        .description = "Produces Chinese aircraft. Holds up to 4 aircraft.",
    },
    .{
        .name = "China_Propaganda_Center",
        .display_name = "Propaganda Center",
        .building_type = .China_Propaganda_Center,
        .cost = 2000,
        .build_time = 35.0,
        .health = 2400,
        .armor = 12,
        .power = -8,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "Subliminal_Messaging", "Satellite_Hack_1", "Satellite_Hack_2" },
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Broadcasts propaganda. Heals nearby infantry and provides special powers.",
    },
    .{
        .name = "China_Nuclear_Reactor",
        .display_name = "Nuclear Reactor",
        .building_type = .China_Nuclear_Reactor,
        .cost = 1000,
        .build_time = 20.0,
        .health = 2500,
        .armor = 10,
        .power = 50,
        .vision_range = 180.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "Overcharge" },
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Generates power. Explodes violently when destroyed, causing radiation.",
    },
    .{
        .name = "China_Gattling_Cannon",
        .display_name = "Gattling Cannon",
        .building_type = .China_Gattling_Cannon,
        .cost = 1200,
        .build_time = 22.0,
        .health = 1600,
        .armor = 6,
        .power = -8,
        .vision_range = 210.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Gattling_Gun"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Chain_Guns"},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Anti-air and anti-infantry defense. Fire rate increases over time.",
    },
    .{
        .name = "China_Bunker",
        .display_name = "Bunker",
        .building_type = .China_Bunker,
        .cost = 800,
        .build_time = 15.0,
        .health = 2000,
        .armor = 12,
        .power = -3,
        .vision_range = 200.0,
        .can_attack = true,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Infantry garrison. Holds 5 infantry with firing ports.",
    },

    // ========================================
    // China Buildings - Tech & Support
    // ========================================
    .{
        .name = "China_Internet_Center",
        .display_name = "Internet Center",
        .building_type = .China_Internet_Center,
        .cost = 1000,
        .build_time = 20.0,
        .health = 2000,
        .armor = 10,
        .power = -5,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Hacker"},
        .upgrades = &[_][]const u8{"Subliminal_Messaging"},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Generates income through hacking. Produces Hackers. $5 per second.",
    },
    .{
        .name = "China_Speaker_Tower",
        .display_name = "Speaker Tower",
        .building_type = .China_Speaker_Tower,
        .cost = 500,
        .build_time = 15.0,
        .health = 1500,
        .armor = 8,
        .power = -3,
        .vision_range = 300.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 2.0,
        .size_y = 2.0,
        .description = "Propaganda tower. Heals nearby units over time. Inspires infantry.",
    },
    .{
        .name = "China_Listening_Outpost",
        .display_name = "Listening Outpost",
        .building_type = .China_Listening_Outpost,
        .cost = 800,
        .build_time = 18.0,
        .health = 1800,
        .armor = 10,
        .power = -8,
        .vision_range = 400.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Intelligence building. Reveals enemy positions and detects stealth.",
    },

    // ========================================
    // China Buildings - Tank General
    // ========================================
    .{
        .name = "China_Advanced_War_Factory",
        .display_name = "Advanced War Factory",
        .building_type = .China_Advanced_War_Factory,
        .cost = 2500,
        .build_time = 35.0,
        .health = 4200,
        .armor = 25,
        .power = -15,
        .vision_range = 220.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Battlemaster", "Emperor_Tank", "Overlord_Tank", "Nuke_Cannon" },
        .upgrades = &[_][]const u8{ "Autoloader", "Uranium_Shells" },
        .size_x = 7.0,
        .size_y = 6.0,
        .description = "Tank General's war factory. Produces armored vehicles 25% faster.",
    },
    .{
        .name = "China_Autoloader_Artillery",
        .display_name = "Autoloader Artillery",
        .building_type = .China_Autoloader_Artillery,
        .cost = 1600,
        .build_time = 22.0,
        .health = 2500,
        .armor = 18,
        .power = -12,
        .vision_range = 280.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Autoloader_Cannon"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Tank General's artillery platform. Rapid-fire cannon with splash damage.",
    },
    .{
        .name = "China_Nuclear_Tank_Bunker",
        .display_name = "Nuclear Tank Bunker",
        .building_type = .China_Nuclear_Tank_Bunker,
        .cost = 1200,
        .build_time = 20.0,
        .health = 3000,
        .armor = 20,
        .power = -8,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Tank General's reinforced bunker. Can garrison 2 tanks for defense.",
    },

    // ========================================
    // China Buildings - Nuke General
    // ========================================
    .{
        .name = "China_Advanced_Nuclear_Reactor",
        .display_name = "Advanced Nuclear Reactor",
        .building_type = .China_Advanced_Nuclear_Reactor,
        .cost = 1200,
        .build_time = 25.0,
        .health = 2500,
        .armor = 15,
        .power = 15,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Nuke General's reactor. Provides 15 power. Explodes when destroyed.",
    },
    .{
        .name = "China_Tactical_Nuke_Silo",
        .display_name = "Tactical Nuke Silo",
        .building_type = .China_Tactical_Nuke_Silo,
        .cost = 6000,
        .build_time = 100.0,
        .health = 6000,
        .armor = 35,
        .power = -75,
        .vision_range = 350.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 6.0,
        .size_y = 6.0,
        .description = "Nuke General's superweapon. Enhanced nuclear missile with larger blast radius.",
    },
    .{
        .name = "China_Nuclear_Artillery_Platform",
        .display_name = "Nuclear Artillery Platform",
        .building_type = .China_Nuclear_Artillery_Platform,
        .cost = 1800,
        .build_time = 25.0,
        .health = 2800,
        .armor = 20,
        .power = -15,
        .vision_range = 300.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Nuclear_Artillery_Shell"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Nuke General's artillery. Fires tactical nuclear shells at long range.",
    },

    // ========================================
    // China Buildings - Infantry General
    // ========================================
    .{
        .name = "China_Advanced_Barracks",
        .display_name = "Advanced Barracks",
        .building_type = .China_Advanced_Barracks,
        .cost = 800,
        .build_time = 18.0,
        .health = 2500,
        .armor = 15,
        .power = -8,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Red_Guard", "Tank_Hunter", "Flamethrower", "Minigunner" },
        .upgrades = &[_][]const u8{ "Nationalism", "Titanium_Armor" },
        .size_x = 5.0,
        .size_y = 4.0,
        .description = "Infantry General's barracks. Trains infantry 25% faster.",
    },
    .{
        .name = "China_Fortified_Bunker",
        .display_name = "Fortified Bunker",
        .building_type = .China_Fortified_Bunker,
        .cost = 1000,
        .build_time = 18.0,
        .health = 3000,
        .armor = 20,
        .power = -5,
        .vision_range = 220.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Heavy_MG"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.5,
        .size_y = 3.5,
        .description = "Infantry General's bunker. Holds 8 infantry with heavy weapons.",
    },
    .{
        .name = "China_Minigun_Platform",
        .display_name = "Minigun Platform",
        .building_type = .China_Minigun_Platform,
        .cost = 700,
        .build_time = 15.0,
        .health = 2000,
        .armor = 12,
        .power = -6,
        .vision_range = 200.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Dual_Minigun"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 2.5,
        .size_y = 2.5,
        .description = "Infantry General's defense. Dual miniguns shred infantry and light vehicles.",
    },

    // ========================================
    // China Buildings - Defensive
    // ========================================
    .{
        .name = "China_Advanced_Gattling_Cannon",
        .display_name = "Advanced Gattling Cannon",
        .building_type = .China_Advanced_Gattling_Cannon,
        .cost = 1200,
        .build_time = 20.0,
        .health = 2500,
        .armor = 15,
        .power = -10,
        .vision_range = 250.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Advanced_Gattling_Gun"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Enhanced Gattling cannon. Faster spin-up, effective vs air and ground.",
    },
    .{
        .name = "China_Flame_Turret",
        .display_name = "Flame Turret",
        .building_type = .China_Flame_Turret,
        .cost = 900,
        .build_time = 18.0,
        .health = 2200,
        .armor = 12,
        .power = -8,
        .vision_range = 180.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Dragon_Flamethrower"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 2.5,
        .size_y = 2.5,
        .description = "Defensive flamethrower. Devastating against infantry, clears garrisoned buildings.",
    },
    .{
        .name = "China_Tank_Trap",
        .display_name = "Tank Trap",
        .building_type = .China_Tank_Trap,
        .cost = 250,
        .build_time = 8.0,
        .health = 1000,
        .armor = 25,
        .power = 0,
        .vision_range = 100.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 2.0,
        .size_y = 1.0,
        .description = "Anti-tank obstacle. Blocks vehicle movement, provides cover for infantry.",
    },
    .{
        .name = "China_Laser_Turret",
        .display_name = "Laser Turret",
        .building_type = .China_Laser_Turret,
        .cost = 1400,
        .build_time = 22.0,
        .health = 2000,
        .armor = 18,
        .power = -15,
        .vision_range = 270.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Laser_Beam"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Advanced laser defense. Continuous beam weapon, excellent vs vehicles.",
    },

    // ========================================
    // China Buildings - Support
    // ========================================
    .{
        .name = "China_Helix_Pad",
        .display_name = "Helix Pad",
        .building_type = .China_Helix_Pad,
        .cost = 1200,
        .build_time = 20.0,
        .health = 2200,
        .armor = 12,
        .power = -8,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Helix", "Helix_Gattling", "Helix_Napalm" },
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Secondary airfield for Helix helicopters. Supports cargo operations.",
    },
    .{
        .name = "China_Advanced_Command_Center",
        .display_name = "Advanced Command Center",
        .building_type = .China_Advanced_Command_Center,
        .cost = 3000,
        .build_time = 45.0,
        .health = 6500,
        .armor = 40,
        .power = 0,
        .vision_range = 300.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Dozer"},
        .upgrades = &[_][]const u8{},
        .size_x = 7.0,
        .size_y = 7.0,
        .description = "Upgraded command center. Increased durability and provides radar coverage.",
    },
    .{
        .name = "China_ECM_Station",
        .display_name = "ECM Station",
        .building_type = .China_ECM_Station,
        .cost = 1500,
        .build_time = 25.0,
        .health = 2000,
        .armor = 15,
        .power = -12,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Electronic countermeasures. Jams enemy radar and disrupts guided missiles.",
    },

    // ========================================
    // GLA Buildings
    // ========================================
    .{
        .name = "GLA_Command_Center",
        .display_name = "Command Center",
        .building_type = .GLA_Command_Center,
        .cost = 2000,
        .build_time = 30.0,
        .health = 4000,
        .armor = 20,
        .power = 0,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Worker"},
        .upgrades = &[_][]const u8{},
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "GLA construction yard. Produces workers. Mobile and can be redeployed.",
    },
    .{
        .name = "GLA_Barracks",
        .display_name = "Barracks",
        .building_type = .GLA_Barracks,
        .cost = 500,
        .build_time = 15.0,
        .health = 1500,
        .armor = 5,
        .power = 0,
        .vision_range = 170.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Rebel", "RPG_Trooper", "Terrorist", "Saboteur", "Jarmen_Kell", "Angry_Mob" },
        .upgrades = &[_][]const u8{ "AP_Bullets", "Capture_Building" },
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Trains GLA infantry. Weaker than other factions but cheaper.",
    },
    .{
        .name = "GLA_Supply_Stash",
        .display_name = "Supply Stash",
        .building_type = .GLA_Supply_Stash,
        .cost = 1500,
        .build_time = 20.0,
        .health = 2000,
        .armor = 8,
        .power = 0,
        .vision_range = 180.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Supply collection point. Workers bring supplies here. Can be booby-trapped.",
    },
    .{
        .name = "GLA_Arms_Dealer",
        .display_name = "Arms Dealer",
        .building_type = .GLA_Arms_Dealer,
        .cost = 2500,
        .build_time = 35.0,
        .health = 2500,
        .armor = 12,
        .power = 0,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Technical", "Scorpion", "Marauder", "Quad_Cannon", "Toxin_Tractor", "Rocket_Buggy", "SCUD_Launcher", "Battle_Bus", "Bomb_Truck" },
        .upgrades = &[_][]const u8{ "Salvage_Upgrade", "Scorpion_Rocket_Upgrade", "Junk_Repair" },
        .size_x = 6.0,
        .size_y = 5.0,
        .description = "Produces GLA vehicles. Gets cheaper with each one built (black market discount).",
    },
    .{
        .name = "GLA_Black_Market",
        .display_name = "Black Market",
        .building_type = .GLA_Black_Market,
        .cost = 2500,
        .build_time = 40.0,
        .health = 2000,
        .armor = 10,
        .power = 0,
        .vision_range = 220.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "Anthrax_Beta", "Anthrax_Gamma", "Radar_Van_Scan", "Fake_Buildings" },
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Technology center. Provides upgrades and generates passive income.",
    },
    .{
        .name = "GLA_Palace",
        .display_name = "Palace",
        .building_type = .GLA_Palace,
        .cost = 2500,
        .build_time = 40.0,
        .health = 3000,
        .armor = 15,
        .power = 0,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "Sneak_Attack", "Cash_Bounty", "Worker_Shoes" },
        .size_x = 6.0,
        .size_y = 6.0,
        .description = "Command center. Provides special general powers and abilities.",
    },
    .{
        .name = "GLA_Tunnel_Network",
        .display_name = "Tunnel Network",
        .building_type = .GLA_Tunnel_Network,
        .cost = 800,
        .build_time = 15.0,
        .health = 1200,
        .armor = 4,
        .power = 0,
        .vision_range = 150.0,
        .can_attack = true,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Underground transport network. Units can travel between tunnels. Holds 8 infantry.",
    },
    .{
        .name = "GLA_Stinger_Site",
        .display_name = "Stinger Site",
        .building_type = .GLA_Stinger_Site,
        .cost = 900,
        .build_time = 18.0,
        .health = 1300,
        .armor = 3,
        .power = 0,
        .vision_range = 220.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Stinger_Missile"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{"AP_Rockets"},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Anti-aircraft defense. Fires Stinger missiles at enemy aircraft.",
    },

    // ========================================
    // GLA Buildings - Tech & Support
    // ========================================
    .{
        .name = "GLA_Radar_Van_Station",
        .display_name = "Radar Van Station",
        .building_type = .GLA_Radar_Van_Station,
        .cost = 800,
        .build_time = 18.0,
        .health = 1500,
        .armor = 8,
        .power = 0,
        .vision_range = 350.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Radar_Van"},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Mobile radar production. Produces Radar Vans for battlefield surveillance.",
    },
    .{
        .name = "GLA_Arms_Cache",
        .display_name = "Arms Cache",
        .building_type = .GLA_Arms_Cache,
        .cost = 400,
        .build_time = 12.0,
        .health = 1200,
        .armor = 5,
        .power = 0,
        .vision_range = 150.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 2.0,
        .size_y = 2.0,
        .description = "Hidden weapons cache. Provides salvage when destroyed by enemy. Can be detonated.",
    },
    .{
        .name = "GLA_Fake_Command_Center",
        .display_name = "Fake Command Center",
        .building_type = .GLA_Fake_Command_Center,
        .cost = 500,
        .build_time = 15.0,
        .health = 2000,
        .armor = 10,
        .power = 0,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Decoy structure. Appears as Command Center on radar to confuse enemies.",
    },

    // ========================================
    // GLA Buildings - Demolition General
    // ========================================
    .{
        .name = "GLA_Advanced_Arms_Dealer",
        .display_name = "Advanced Arms Dealer",
        .building_type = .GLA_Advanced_Arms_Dealer,
        .cost = 2200,
        .build_time = 30.0,
        .health = 2500,
        .armor = 15,
        .power = 0,
        .vision_range = 180.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Scorpion", "Rocket_Buggy", "Bomb_Truck", "Demolition_Technical" },
        .upgrades = &[_][]const u8{ "AP_Bullets", "Buggy_Ammo" },
        .size_x = 5.0,
        .size_y = 4.0,
        .description = "Demolition General's vehicle plant. Produces explosive-focused vehicles.",
    },
    .{
        .name = "GLA_Demo_Trap_Factory",
        .display_name = "Demo Trap Factory",
        .building_type = .GLA_Demo_Trap_Factory,
        .cost = 600,
        .build_time = 15.0,
        .health = 1500,
        .armor = 8,
        .power = 0,
        .vision_range = 150.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Demolition General's trap factory. Automatically places demo traps nearby.",
    },
    .{
        .name = "GLA_Explosive_Bunker",
        .display_name = "Explosive Bunker",
        .building_type = .GLA_Explosive_Bunker,
        .cost = 700,
        .build_time = 16.0,
        .health = 1800,
        .armor = 10,
        .power = 0,
        .vision_range = 180.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"RPG_Launcher"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Demolition General's bunker. Explodes violently when destroyed, damaging nearby units.",
    },

    // ========================================
    // GLA Buildings - Toxin General
    // ========================================
    .{
        .name = "GLA_Toxin_Lab",
        .display_name = "Toxin Lab",
        .building_type = .GLA_Toxin_Lab,
        .cost = 1200,
        .build_time = 22.0,
        .health = 2000,
        .armor = 12,
        .power = 0,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "Anthrax_Beta", "Anthrax_Gamma" },
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Toxin General's laboratory. Researches advanced toxin upgrades.",
    },
    .{
        .name = "GLA_Anthrax_Bomb_Silo",
        .display_name = "Anthrax Bomb Silo",
        .building_type = .GLA_Anthrax_Bomb_Silo,
        .cost = 5500,
        .build_time = 95.0,
        .health = 4500,
        .armor = 25,
        .power = 0,
        .vision_range = 300.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Toxin General's superweapon. Launches anthrax bomb with lingering toxin cloud.",
    },
    .{
        .name = "GLA_Toxin_Tunnel",
        .display_name = "Toxin Tunnel Network",
        .building_type = .GLA_Toxin_Tunnel,
        .cost = 1200,
        .build_time = 20.0,
        .health = 2500,
        .armor = 15,
        .power = 0,
        .vision_range = 150.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Terrorist", "Toxin_Rebel", "Angry_Mob" },
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Toxin General's tunnel. Spawns toxin-armed infantry and releases poison when destroyed.",
    },

    // ========================================
    // GLA Buildings - Stealth General
    // ========================================
    .{
        .name = "GLA_Camouflage_Net",
        .display_name = "Camouflage Net",
        .building_type = .GLA_Camouflage_Net,
        .cost = 800,
        .build_time = 18.0,
        .health = 1500,
        .armor = 8,
        .power = 0,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 6.0,
        .size_y = 6.0,
        .description = "Stealth General's camo net. Provides stealth to nearby buildings and units.",
    },
    .{
        .name = "GLA_Stealth_Tunnel",
        .display_name = "Stealth Tunnel",
        .building_type = .GLA_Stealth_Tunnel,
        .cost = 1400,
        .build_time = 22.0,
        .health = 2800,
        .armor = 18,
        .power = 0,
        .vision_range = 150.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Jarmen_Kell", "Hijacker", "Saboteur" },
        .upgrades = &[_][]const u8{ "Camouflage" },
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Stealth General's tunnel. Produces special operatives. Permanently stealthed.",
    },
    .{
        .name = "GLA_GPS_Scrambler",
        .display_name = "GPS Scrambler",
        .building_type = .GLA_GPS_Scrambler,
        .cost = 1000,
        .build_time = 20.0,
        .health = 1800,
        .armor = 10,
        .power = 0,
        .vision_range = 400.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Stealth General's jammer. Creates radar blackout zone, hides friendly units.",
    },

    // ========================================
    // GLA Buildings - Defensive
    // ========================================
    .{
        .name = "GLA_RPG_Trooper_Outpost",
        .display_name = "RPG Trooper Outpost",
        .building_type = .GLA_RPG_Trooper_Outpost,
        .cost = 600,
        .build_time = 15.0,
        .health = 1600,
        .armor = 8,
        .power = 0,
        .vision_range = 200.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"RPG_Launcher"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 2.5,
        .size_y = 2.5,
        .description = "Defensive outpost. Garrisoned with RPG troopers, effective vs vehicles and aircraft.",
    },
    .{
        .name = "GLA_Demo_Trap",
        .display_name = "Demo Trap",
        .building_type = .GLA_Demo_Trap,
        .cost = 200,
        .build_time = 8.0,
        .health = 500,
        .armor = 3,
        .power = 0,
        .vision_range = 100.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 1.5,
        .size_y = 1.5,
        .description = "Explosive trap. Detonates when enemy units approach, causing heavy damage.",
    },
    .{
        .name = "GLA_Tunnel_Entrance",
        .display_name = "Tunnel Entrance",
        .building_type = .GLA_Tunnel_Entrance,
        .cost = 300,
        .build_time = 10.0,
        .health = 1800,
        .armor = 12,
        .power = 0,
        .vision_range = 150.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 2.0,
        .size_y = 2.0,
        .description = "Secondary tunnel entrance. Connects to tunnel network for rapid deployment.",
    },
    .{
        .name = "GLA_Booby_Trap",
        .display_name = "Booby Trap",
        .building_type = .GLA_Booby_Trap,
        .cost = 150,
        .build_time = 6.0,
        .health = 300,
        .armor = 2,
        .power = 0,
        .vision_range = 80.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 1.0,
        .size_y = 1.0,
        .description = "Small explosive trap. Cheap area denial, damages infantry and light vehicles.",
    },

    // ========================================
    // GLA Buildings - Support
    // ========================================
    .{
        .name = "GLA_Repair_Bay",
        .display_name = "Repair Bay",
        .building_type = .GLA_Repair_Bay,
        .cost = 1000,
        .build_time = 20.0,
        .health = 2000,
        .armor = 12,
        .power = 0,
        .vision_range = 180.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Vehicle repair facility. Automatically repairs damaged vehicles in vicinity.",
    },
    .{
        .name = "GLA_Advanced_Black_Market",
        .display_name = "Advanced Black Market",
        .building_type = .GLA_Advanced_Black_Market,
        .cost = 1800,
        .build_time = 25.0,
        .health = 2200,
        .armor = 15,
        .power = 0,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Enhanced black market. Generates more income, unlocks advanced upgrades.",
    },
    .{
        .name = "GLA_Salvage_Yard",
        .display_name = "Salvage Yard",
        .building_type = .GLA_Salvage_Yard,
        .cost = 800,
        .build_time = 18.0,
        .health = 1800,
        .armor = 10,
        .power = 0,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 5.0,
        .size_y = 4.0,
        .description = "Salvage collection center. Increases salvage income from destroyed units by 50%.",
    },
    .{
        .name = "GLA_Worker_Camp",
        .display_name = "Worker Camp",
        .building_type = .GLA_Worker_Camp,
        .cost = 400,
        .build_time = 12.0,
        .health = 1200,
        .armor = 8,
        .power = 0,
        .vision_range = 150.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Worker"},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Worker production facility. Trains additional workers for faster construction.",
    },
};

pub fn getBuildingDef(building_type: BuildingType) *const BuildingDef {
    for (&BUILDING_DATABASE) |*def| {
        if (def.building_type == building_type) return def;
    }
    return &BUILDING_DATABASE[0];
}

pub fn getBuildingCost(building_type: BuildingType) u32 {
    return getBuildingDef(building_type).cost;
}
