// C&C Generals - Building Definitions Database

const std = @import("std");

pub const BuildingType = enum {
    // USA Buildings
    USA_Command_Center,
    USA_Barracks,
    USA_Supply_Center,
    USA_War_Factory,
    USA_Airfield,
    USA_Strategy_Center,
    USA_Detention_Camp,
    USA_Patriot_Battery,
    USA_Fire_Base,
    USA_Particle_Cannon,

    // China Buildings
    China_Command_Center,
    China_Barracks,
    China_Supply_Center,
    China_War_Factory,
    China_Airfield,
    China_Propaganda_Center,
    China_Nuclear_Reactor,
    China_Gattling_Cannon,
    China_Bunker,
    China_Nuclear_Missile,

    // GLA Buildings
    GLA_Command_Center,
    GLA_Barracks,
    GLA_Supply_Stash,
    GLA_Arms_Dealer,
    GLA_Black_Market,
    GLA_Palace,
    GLA_Tunnel_Network,
    GLA_Stinger_Site,
    GLA_SCUD_Storm,

    // More buildings...
};

pub const BuildingDef = struct {
    name: []const u8,
    display_name: []const u8,
    building_type: BuildingType,
    cost: u32,
    build_time: f32,
    health: u32,
    armor: u32,
    power: i32, // Negative = consumes, Positive = generates
    vision_range: f32,
    can_attack: bool,
    weapons: []const []const u8,
    produces: []const []const u8,
    upgrades: []const []const u8,
    size_x: f32,
    size_y: f32,
    description: []const u8,
};

pub const BUILDING_DATABASE = [_]BuildingDef{
    .{
        .name = "USA_Command_Center",
        .display_name = "Command Center",
        .building_type = .USA_Command_Center,
        .cost = 2000,
        .build_time = 30.0,
        .health = 5000,
        .armor = 30,
        .power = 0,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Dozer"},
        .upgrades = &[_][]const u8{},
        .size_x = 6.0,
        .size_y = 6.0,
        .description = "Main construction yard. Produces construction dozers. If destroyed, you cannot build.",
    },
    .{
        .name = "USA_Barracks",
        .display_name = "Barracks",
        .building_type = .USA_Barracks,
        .cost = 500,
        .build_time = 15.0,
        .health = 2000,
        .armor = 10,
        .power = -5,
        .vision_range = 180.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Ranger", "Missile_Defender", "Pathfinder", "Colonel_Burton" },
        .upgrades = &[_][]const u8{ "Advanced_Training", "Capture_Building" },
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Trains infantry units and provides infantry upgrades.",
    },
    .{
        .name = "USA_Supply_Center",
        .display_name = "Supply Center",
        .building_type = .USA_Supply_Center,
        .cost = 2000,
        .build_time = 25.0,
        .health = 3000,
        .armor = 15,
        .power = 0,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Supply_Truck", "Chinook"},
        .upgrades = &[_][]const u8{},
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Generates supplies. Supply trucks collect from here. Can be upgraded with additional supply pads.",
    },
    .{
        .name = "USA_War_Factory",
        .display_name = "War Factory",
        .building_type = .USA_War_Factory,
        .cost = 2000,
        .build_time = 30.0,
        .health = 3500,
        .armor = 20,
        .power = -10,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Humvee", "Tomahawk", "Crusader", "Paladin", "Avenger", "Ambulance" },
        .upgrades = &[_][]const u8{ "Composite_Armor", "TOW_Missile", "Battle_Drone" },
        .size_x = 6.0,
        .size_y = 5.0,
        .description = "Produces vehicles and provides vehicle upgrades.",
    },
    .{
        .name = "USA_Airfield",
        .display_name = "Airfield",
        .building_type = .USA_Airfield,
        .cost = 2500,
        .build_time = 35.0,
        .health = 3000,
        .armor = 15,
        .power = -15,
        .vision_range = 220.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Comanche", "Raptor", "Stealth_Fighter", "Aurora_Alpha" },
        .upgrades = &[_][]const u8{ "Countermeasures", "Laser_Missiles" },
        .size_x = 8.0,
        .size_y = 6.0,
        .description = "Produces aircraft and provides aircraft upgrades. Can hold up to 4 aircraft.",
    },
    .{
        .name = "USA_Patriot_Battery",
        .display_name = "Patriot Missile Battery",
        .building_type = .USA_Patriot_Battery,
        .cost = 1000,
        .build_time = 20.0,
        .health = 1500,
        .armor = 5,
        .power = -10,
        .vision_range = 200.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Patriot_Missile"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Advanced_Control_Rods"},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Anti-aircraft defense. Fires missiles at enemy aircraft.",
    },
    .{
        .name = "USA_Particle_Cannon",
        .display_name = "Particle Cannon",
        .building_type = .USA_Particle_Cannon,
        .cost = 5000,
        .build_time = 90.0,
        .health = 5000,
        .armor = 25,
        .power = -50,
        .vision_range = 300.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 6.0,
        .size_y = 6.0,
        .description = "Superweapon. Fires a devastating particle beam from orbit. 5 minute charge time.",
    },
    .{
        .name = "China_Command_Center",
        .display_name = "Command Center",
        .building_type = .China_Command_Center,
        .cost = 2000,
        .build_time = 30.0,
        .health = 5500,
        .armor = 35,
        .power = 0,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Dozer"},
        .upgrades = &[_][]const u8{},
        .size_x = 6.0,
        .size_y = 6.0,
        .description = "Chinese construction yard. Produces dozers.",
    },
    .{
        .name = "China_Nuclear_Missile",
        .display_name = "Nuclear Missile Silo",
        .building_type = .China_Nuclear_Missile,
        .cost = 5000,
        .build_time = 90.0,
        .health = 5000,
        .armor = 30,
        .power = -50,
        .vision_range = 300.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Superweapon. Launches a nuclear missile at target location. 6 minute charge time.",
    },
    .{
        .name = "GLA_SCUD_Storm",
        .display_name = "SCUD Storm",
        .building_type = .GLA_SCUD_Storm,
        .cost = 5000,
        .build_time = 90.0,
        .health = 4000,
        .armor = 20,
        .power = 0,
        .vision_range = 300.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "Anthrax_Beta" },
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Superweapon. Launches 9 SCUD missiles in a grid pattern. 5 minute charge time.",
    },
    .{
        .name = "USA_Strategy_Center",
        .display_name = "Strategy Center",
        .building_type = .USA_Strategy_Center,
        .cost = 2500,
        .build_time = 40.0,
        .health = 2500,
        .armor = 15,
        .power = -10,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "Hold_The_Line", "Search_And_Destroy", "Bombardment" },
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Advanced tactics building. Provides strategic bonuses to all units.",
    },
    .{
        .name = "USA_Detention_Camp",
        .display_name = "Detention Camp",
        .building_type = .USA_Detention_Camp,
        .cost = 1000,
        .build_time = 20.0,
        .health = 2000,
        .armor = 10,
        .power = -5,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Generates income from captured enemy soldiers. $5 per prisoner.",
    },
    .{
        .name = "USA_Fire_Base",
        .display_name = "Fire Base",
        .building_type = .USA_Fire_Base,
        .cost = 800,
        .build_time = 15.0,
        .health = 1800,
        .armor = 8,
        .power = -5,
        .vision_range = 220.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"M249_SAW"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{"TOW_Missile"},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Defensive bunker. Holds 4 infantry. Can be upgraded with TOW missiles.",
    },
    .{
        .name = "China_Barracks",
        .display_name = "Barracks",
        .building_type = .China_Barracks,
        .cost = 500,
        .build_time = 15.0,
        .health = 2200,
        .armor = 12,
        .power = -5,
        .vision_range = 180.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Red_Guard", "Tank_Hunter", "Hacker", "Black_Lotus" },
        .upgrades = &[_][]const u8{ "Nationalism", "Capture_Building" },
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Trains Chinese infantry units and provides upgrades.",
    },
    .{
        .name = "China_Supply_Center",
        .display_name = "Supply Center",
        .building_type = .China_Supply_Center,
        .cost = 2000,
        .build_time = 25.0,
        .health = 3200,
        .armor = 18,
        .power = 0,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{"Supply_Truck"},
        .upgrades = &[_][]const u8{},
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Chinese supply depot. More durable than USA equivalent.",
    },
    .{
        .name = "China_War_Factory",
        .display_name = "War Factory",
        .building_type = .China_War_Factory,
        .cost = 2000,
        .build_time = 30.0,
        .health = 3800,
        .armor = 22,
        .power = -10,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Battlemaster", "Gattling_Tank", "Troop_Crawler", "Dragon_Tank", "Inferno_Cannon", "Nuke_Cannon", "Overlord", "ECM_Tank" },
        .upgrades = &[_][]const u8{ "Chain_Guns", "Black_Napalm", "Nuclear_Shells" },
        .size_x = 6.0,
        .size_y = 5.0,
        .description = "Produces Chinese vehicles and upgrades.",
    },
    .{
        .name = "China_Airfield",
        .display_name = "Airfield",
        .building_type = .China_Airfield,
        .cost = 2000,
        .build_time = 32.0,
        .health = 2800,
        .armor = 14,
        .power = -12,
        .vision_range = 220.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "MiG", "Helix" },
        .upgrades = &[_][]const u8{ "Black_Napalm", "Nationalism" },
        .size_x = 8.0,
        .size_y = 6.0,
        .description = "Produces Chinese aircraft. Holds up to 4 aircraft.",
    },
    .{
        .name = "China_Propaganda_Center",
        .display_name = "Propaganda Center",
        .building_type = .China_Propaganda_Center,
        .cost = 2000,
        .build_time = 35.0,
        .health = 2400,
        .armor = 12,
        .power = -8,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "Subliminal_Messaging", "Satellite_Hack_1", "Satellite_Hack_2" },
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Broadcasts propaganda. Heals nearby infantry and provides special powers.",
    },
    .{
        .name = "China_Nuclear_Reactor",
        .display_name = "Nuclear Reactor",
        .building_type = .China_Nuclear_Reactor,
        .cost = 1000,
        .build_time = 20.0,
        .health = 2500,
        .armor = 10,
        .power = 50,
        .vision_range = 180.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "Overcharge" },
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Generates power. Explodes violently when destroyed, causing radiation.",
    },
    .{
        .name = "China_Gattling_Cannon",
        .display_name = "Gattling Cannon",
        .building_type = .China_Gattling_Cannon,
        .cost = 1200,
        .build_time = 22.0,
        .health = 1600,
        .armor = 6,
        .power = -8,
        .vision_range = 210.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Gattling_Gun"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Chain_Guns"},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Anti-air and anti-infantry defense. Fire rate increases over time.",
    },
    .{
        .name = "China_Bunker",
        .display_name = "Bunker",
        .building_type = .China_Bunker,
        .cost = 800,
        .build_time = 15.0,
        .health = 2000,
        .armor = 12,
        .power = -3,
        .vision_range = 200.0,
        .can_attack = true,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Infantry garrison. Holds 5 infantry with firing ports.",
    },
    .{
        .name = "GLA_Barracks",
        .display_name = "Barracks",
        .building_type = .GLA_Barracks,
        .cost = 500,
        .build_time = 15.0,
        .health = 1500,
        .armor = 5,
        .power = 0,
        .vision_range = 170.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Rebel", "RPG_Trooper", "Terrorist", "Saboteur", "Jarmen_Kell", "Angry_Mob" },
        .upgrades = &[_][]const u8{ "AP_Bullets", "Capture_Building" },
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Trains GLA infantry. Weaker than other factions but cheaper.",
    },
    .{
        .name = "GLA_Supply_Stash",
        .display_name = "Supply Stash",
        .building_type = .GLA_Supply_Stash,
        .cost = 1500,
        .build_time = 20.0,
        .health = 2000,
        .armor = 8,
        .power = 0,
        .vision_range = 180.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 4.0,
        .size_y = 4.0,
        .description = "Supply collection point. Workers bring supplies here. Can be booby-trapped.",
    },
    .{
        .name = "GLA_Arms_Dealer",
        .display_name = "Arms Dealer",
        .building_type = .GLA_Arms_Dealer,
        .cost = 2500,
        .build_time = 35.0,
        .health = 2500,
        .armor = 12,
        .power = 0,
        .vision_range = 200.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{ "Technical", "Scorpion", "Marauder", "Quad_Cannon", "Toxin_Tractor", "Rocket_Buggy", "SCUD_Launcher", "Battle_Bus", "Bomb_Truck" },
        .upgrades = &[_][]const u8{ "Salvage_Upgrade", "Scorpion_Rocket_Upgrade", "Junk_Repair" },
        .size_x = 6.0,
        .size_y = 5.0,
        .description = "Produces GLA vehicles. Gets cheaper with each one built (black market discount).",
    },
    .{
        .name = "GLA_Black_Market",
        .display_name = "Black Market",
        .building_type = .GLA_Black_Market,
        .cost = 2500,
        .build_time = 40.0,
        .health = 2000,
        .armor = 10,
        .power = 0,
        .vision_range = 220.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "Anthrax_Beta", "Anthrax_Gamma", "Radar_Van_Scan", "Fake_Buildings" },
        .size_x = 5.0,
        .size_y = 5.0,
        .description = "Technology center. Provides upgrades and generates passive income.",
    },
    .{
        .name = "GLA_Palace",
        .display_name = "Palace",
        .building_type = .GLA_Palace,
        .cost = 2500,
        .build_time = 40.0,
        .health = 3000,
        .armor = 15,
        .power = 0,
        .vision_range = 250.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{ "Sneak_Attack", "Cash_Bounty", "Worker_Shoes" },
        .size_x = 6.0,
        .size_y = 6.0,
        .description = "Command center. Provides special general powers and abilities.",
    },
    .{
        .name = "GLA_Tunnel_Network",
        .display_name = "Tunnel Network",
        .building_type = .GLA_Tunnel_Network,
        .cost = 800,
        .build_time = 15.0,
        .health = 1200,
        .armor = 4,
        .power = 0,
        .vision_range = 150.0,
        .can_attack = true,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Underground transport network. Units can travel between tunnels. Holds 8 infantry.",
    },
    .{
        .name = "GLA_Stinger_Site",
        .display_name = "Stinger Site",
        .building_type = .GLA_Stinger_Site,
        .cost = 900,
        .build_time = 18.0,
        .health = 1300,
        .armor = 3,
        .power = 0,
        .vision_range = 220.0,
        .can_attack = true,
        .weapons = &[_][]const u8{"Stinger_Missile"},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{"AP_Rockets"},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Anti-aircraft defense. Fires Stinger missiles at enemy aircraft.",
    },
    .{
        .name = "USA_Cold_Fusion_Reactor",
        .display_name = "Cold Fusion Reactor",
        .building_type = .USA_Command_Center,
        .cost = 800,
        .build_time = 18.0,
        .health = 2000,
        .armor = 8,
        .power = 30,
        .vision_range = 180.0,
        .can_attack = false,
        .weapons = &[_][]const u8{},
        .produces = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size_x = 3.0,
        .size_y = 3.0,
        .description = "Generates power. Clean and efficient power generation.",
    },
};

pub fn getBuildingDef(building_type: BuildingType) *const BuildingDef {
    for (&BUILDING_DATABASE) |*def| {
        if (def.building_type == building_type) return def;
    }
    return &BUILDING_DATABASE[0];
}

pub fn getBuildingCost(building_type: BuildingType) u32 {
    return getBuildingDef(building_type).cost;
}
