// C&C Generals - Maps Database

const std = @import("std");

pub const MapSize = enum {
    Small,      // 2-4 players
    Medium,     // 4-6 players
    Large,      // 6-8 players
};

pub const MapType = enum {
    Skirmish,
    Multiplayer,
    Campaign,
    Challenge,
};

pub const MapDef = struct {
    name: []const u8,
    display_name: []const u8,
    map_type: MapType,
    size: MapSize,
    max_players: u8,
    width: u32,
    height: u32,
    description: []const u8,
    features: []const []const u8,
};

pub const MAP_DATABASE = [_]MapDef{
    // Small Maps
    .{
        .name = "Tournament_Desert",
        .display_name = "Tournament Desert",
        .map_type = .Multiplayer,
        .size = .Small,
        .max_players = 2,
        .width = 256,
        .height = 256,
        .description = "Classic 1v1 tournament map. Symmetrical desert terrain with limited resources.",
        .features = &[_][]const u8{ "Symmetrical", "Limited Resources", "Competitive" },
    },
    .{
        .name = "Tournament_City",
        .display_name = "Tournament City",
        .map_type = .Multiplayer,
        .size = .Small,
        .max_players = 2,
        .width = 256,
        .height = 256,
        .description = "Urban warfare. Buildings provide cover and strategic positions.",
        .features = &[_][]const u8{ "Urban", "Building Garrisons", "Symmetrical" },
    },
    .{
        .name = "Tournament_Island",
        .display_name = "Tournament Island",
        .map_type = .Multiplayer,
        .size = .Small,
        .max_players = 2,
        .width = 256,
        .height = 256,
        .description = "Two islands separated by water. Naval and air units essential.",
        .features = &[_][]const u8{ "Naval Combat", "Island Bases", "Air Superiority" },
    },
    // Medium Maps
    .{
        .name = "Green_Pastures",
        .display_name = "Green Pastures",
        .map_type = .Skirmish,
        .size = .Medium,
        .max_players = 4,
        .width = 512,
        .height = 512,
        .description = "Lush green terrain with plenty of resources. Good for beginners.",
        .features = &[_][]const u8{ "Abundant Resources", "Open Terrain", "Balanced" },
    },
    .{
        .name = "Wasteland_Warlords",
        .display_name = "Wasteland Warlords",
        .map_type = .Skirmish,
        .size = .Medium,
        .max_players = 4,
        .width = 512,
        .height = 512,
        .description = "Post-apocalyptic wasteland. Scarce resources lead to intense competition.",
        .features = &[_][]const u8{ "Scarce Resources", "Desert Terrain", "Aggressive" },
    },
    .{
        .name = "Golden_Oasis",
        .display_name = "Golden Oasis",
        .map_type = .Skirmish,
        .size = .Medium,
        .max_players = 4,
        .width = 512,
        .height = 512,
        .description = "Desert map with central oasis. Control the center to win.",
        .features = &[_][]const u8{ "Central Objective", "Desert", "King of the Hill" },
    },
    .{
        .name = "Urban_Jungle",
        .display_name = "Urban Jungle",
        .map_type = .Multiplayer,
        .size = .Medium,
        .max_players = 4,
        .width = 512,
        .height = 512,
        .description = "Dense urban environment. Buildings everywhere provide cover.",
        .features = &[_][]const u8{ "Urban Warfare", "Building Capture", "Close Quarters" },
    },
    .{
        .name = "Frozen_Fury",
        .display_name = "Frozen Fury",
        .map_type = .Skirmish,
        .size = .Medium,
        .max_players = 4,
        .width = 512,
        .height = 512,
        .description = "Frozen tundra. Icy terrain affects movement speed.",
        .features = &[_][]const u8{ "Snow Terrain", "Slow Movement", "Strategic Choke Points" },
    },
    // Large Maps
    .{
        .name = "Final_Crusade",
        .display_name = "Final Crusade",
        .map_type = .Multiplayer,
        .size = .Large,
        .max_players = 8,
        .width = 1024,
        .height = 1024,
        .description = "Massive 8-player free-for-all. Epic battles with full armies.",
        .features = &[_][]const u8{ "8 Players", "Massive Scale", "Long Games" },
    },
    .{
        .name = "Battle_for_Oil",
        .display_name = "Battle for Oil",
        .map_type = .Multiplayer,
        .size = .Large,
        .max_players = 6,
        .width = 768,
        .height = 768,
        .description = "Oil fields in the center. Control the oil to fund your war machine.",
        .features = &[_][]const u8{ "Resource Control", "Oil Derricks", "Economic Warfare" },
    },
    .{
        .name = "Desert_Fury",
        .display_name = "Desert Fury",
        .map_type = .Skirmish,
        .size = .Large,
        .max_players = 8,
        .width = 1024,
        .height = 1024,
        .description = "Vast desert expanse. Room for massive tank battles.",
        .features = &[_][]const u8{ "Tank Warfare", "Open Terrain", "Air Combat" },
    },
    .{
        .name = "Mountain_Stronghold",
        .display_name = "Mountain Stronghold",
        .map_type = .Multiplayer,
        .size = .Large,
        .max_players = 6,
        .width = 768,
        .height = 768,
        .description = "Mountainous terrain with narrow passes. Defensible positions.",
        .features = &[_][]const u8{ "Mountains", "Choke Points", "Defensive" },
    },
    .{
        .name = "Coastal_Clash",
        .display_name = "Coastal Clash",
        .map_type = .Multiplayer,
        .size = .Large,
        .max_players = 6,
        .width = 768,
        .height = 768,
        .description = "Coastal battleground. Land and sea combat combined.",
        .features = &[_][]const u8{ "Coastal", "Naval Units", "Amphibious" },
    },
    // Campaign Maps
    .{
        .name = "Operation_Desperate_Union",
        .display_name = "Operation: Desperate Union",
        .map_type = .Campaign,
        .size = .Medium,
        .max_players = 1,
        .width = 512,
        .height = 512,
        .description = "USA Campaign Mission 1. Defend the base from GLA attacks.",
        .features = &[_][]const u8{ "Defense Mission", "Tutorial", "Story Mode" },
    },
    .{
        .name = "Operation_Guardian_Angel",
        .display_name = "Operation: Guardian Angel",
        .map_type = .Campaign,
        .size = .Medium,
        .max_players = 1,
        .width = 512,
        .height = 512,
        .description = "USA Campaign Mission 2. Secure the supply convoy.",
        .features = &[_][]const u8{ "Escort Mission", "Limited Units", "Story Mode" },
    },
    .{
        .name = "Operation_Sword_of_Tianzi",
        .display_name = "Operation: Sword of Tianzi",
        .map_type = .Campaign,
        .size = .Large,
        .max_players = 1,
        .width = 768,
        .height = 768,
        .description = "China Campaign Mission 1. Reclaim the nuclear reactor.",
        .features = &[_][]const u8{ "Assault Mission", "Nuclear Threat", "Story Mode" },
    },
    .{
        .name = "Operation_Red_Tide",
        .display_name = "Operation: Red Tide",
        .map_type = .Campaign,
        .size = .Large,
        .max_players = 1,
        .width = 768,
        .height = 768,
        .description = "China Campaign Mission 2. Push back GLA forces.",
        .features = &[_][]const u8{ "Offensive Mission", "Tank Rush", "Story Mode" },
    },
    .{
        .name = "Operation_Black_Gold",
        .display_name = "Operation: Black Gold",
        .map_type = .Campaign,
        .size = .Medium,
        .max_players = 1,
        .width = 512,
        .height = 512,
        .description = "GLA Campaign Mission 1. Capture the oil refinery.",
        .features = &[_][]const u8{ "Stealth Mission", "Guerrilla Tactics", "Story Mode" },
    },
    .{
        .name = "Operation_Scorched_Earth",
        .display_name = "Operation: Scorched Earth",
        .map_type = .Campaign,
        .size = .Large,
        .max_players = 1,
        .width = 768,
        .height = 768,
        .description = "GLA Campaign Mission 2. Destroy the enemy base.",
        .features = &[_][]const u8{ "Destruction Mission", "SCUD Missiles", "Story Mode" },
    },
    // Zero Hour Multiplayer Maps
    .{
        .name = "Twilight_Flame",
        .display_name = "Twilight Flame",
        .map_type = .Multiplayer,
        .size = .Medium,
        .max_players = 4,
        .width = 512,
        .height = 512,
        .description = "Industrial zone at dusk. Oil refineries provide economic advantage.",
        .features = &[_][]const u8{ "Oil Derricks", "Urban Industrial", "Balanced" },
    },
    .{
        .name = "Tournament_Tundra",
        .display_name = "Tournament Tundra",
        .map_type = .Multiplayer,
        .size = .Small,
        .max_players = 2,
        .width = 256,
        .height = 256,
        .description = "Frozen tournament map. Symmetrical with snow terrain.",
        .features = &[_][]const u8{ "Snow", "Symmetrical", "1v1 Competitive" },
    },
    .{
        .name = "Wasteland",
        .display_name = "Wasteland",
        .map_type = .Multiplayer,
        .size = .Large,
        .max_players = 6,
        .width = 768,
        .height = 768,
        .description = "Barren wasteland with scattered resources. Fight for survival.",
        .features = &[_][]const u8{ "Desert", "Scarce Resources", "Brutal" },
    },
    .{
        .name = "Whiteout",
        .display_name = "Whiteout",
        .map_type = .Multiplayer,
        .size = .Medium,
        .max_players = 4,
        .width = 512,
        .height = 512,
        .description = "Complete snow coverage. Visibility reduced in blizzard conditions.",
        .features = &[_][]const u8{ "Heavy Snow", "Limited Visibility", "Arctic" },
    },
    .{
        .name = "Destruction_Station",
        .display_name = "Destruction Station",
        .map_type = .Multiplayer,
        .size = .Medium,
        .max_players = 4,
        .width = 512,
        .height = 512,
        .description = "Abandoned military base. Capture buildings for bonuses.",
        .features = &[_][]const u8{ "Capture Buildings", "Military Base", "Strategic" },
    },
    .{
        .name = "Heartland_Shield",
        .display_name = "Heartland Shield",
        .map_type = .Multiplayer,
        .size = .Large,
        .max_players = 8,
        .width = 1024,
        .height = 1024,
        .description = "Protect the homeland. Large scale warfare across varied terrain.",
        .features = &[_][]const u8{ "Mixed Terrain", "8 Players", "Epic Battles" },
    },
    .{
        .name = "Tournament_Continental",
        .display_name = "Tournament Continental",
        .map_type = .Multiplayer,
        .size = .Small,
        .max_players = 2,
        .width = 256,
        .height = 256,
        .description = "Continental divide. Two sides separated by river.",
        .features = &[_][]const u8{ "River", "Symmetrical", "Bridge Control" },
    },
    .{
        .name = "Dark_Mountain",
        .display_name = "Dark Mountain",
        .map_type = .Multiplayer,
        .size = .Large,
        .max_players = 6,
        .width = 768,
        .height = 768,
        .description = "Mountainous nighttime battlefield. High ground advantage.",
        .features = &[_][]const u8{ "Night", "Mountains", "Height Advantage" },
    },
    .{
        .name = "Tournament_Plains",
        .display_name = "Tournament Plains",
        .map_type = .Multiplayer,
        .size = .Small,
        .max_players = 2,
        .width = 256,
        .height = 256,
        .description = "Open plains tournament map. Tank warfare focused.",
        .features = &[_][]const u8{ "Open Terrain", "Tank Combat", "Symmetrical" },
    },
    .{
        .name = "Flash_Fire",
        .display_name = "Flash Fire",
        .map_type = .Multiplayer,
        .size = .Medium,
        .max_players = 4,
        .width = 512,
        .height = 512,
        .description = "Desert oil fields ablaze. Fire hazards throughout map.",
        .features = &[_][]const u8{ "Fire Hazards", "Oil Fields", "Desert" },
    },
    .{
        .name = "Sand_Serpent",
        .display_name = "Sand Serpent",
        .map_type = .Multiplayer,
        .size = .Large,
        .max_players = 6,
        .width = 768,
        .height = 768,
        .description = "Winding desert canyons. Ambush opportunities everywhere.",
        .features = &[_][]const u8{ "Canyons", "Ambush Points", "Desert Warfare" },
    },
    .{
        .name = "Fallen_Empire",
        .display_name = "Fallen Empire",
        .map_type = .Multiplayer,
        .size = .Large,
        .max_players = 8,
        .width = 1024,
        .height = 1024,
        .description = "Ruins of ancient empire. Capture tech buildings for advantages.",
        .features = &[_][]const u8{ "Ruins", "Tech Buildings", "Historical" },
    },
    .{
        .name = "Scorched_Earth",
        .display_name = "Scorched Earth",
        .map_type = .Multiplayer,
        .size = .Medium,
        .max_players = 4,
        .width = 512,
        .height = 512,
        .description = "Burned battleground. Scorched terrain limits building placement.",
        .features = &[_][]const u8{ "Scorched", "Limited Build Space", "Challenging" },
    },
    .{
        .name = "Winter_Wolf",
        .display_name = "Winter Wolf",
        .map_type = .Multiplayer,
        .size = .Large,
        .max_players = 6,
        .width = 768,
        .height = 768,
        .description = "Frozen forest battlefield. Trees provide cover.",
        .features = &[_][]const u8{ "Snow Forest", "Tree Cover", "Winter" },
    },
    .{
        .name = "Lights_Out",
        .display_name = "Lights Out",
        .map_type = .Multiplayer,
        .size = .Medium,
        .max_players = 4,
        .width = 512,
        .height = 512,
        .description = "Night combat in urban environment. Power plants control lighting.",
        .features = &[_][]const u8{ "Night Urban", "Power Control", "Darkness" },
    },
    .{
        .name = "Tournament_Lake",
        .display_name = "Tournament Lake",
        .map_type = .Multiplayer,
        .size = .Small,
        .max_players = 2,
        .width = 256,
        .height = 256,
        .description = "Lake divides two bases. Naval units or air required.",
        .features = &[_][]const u8{ "Lake", "Naval Combat", "Symmetrical" },
    },
    .{
        .name = "Homeland_Alliance",
        .display_name = "Homeland Alliance",
        .map_type = .Multiplayer,
        .size = .Large,
        .max_players = 8,
        .width = 1024,
        .height = 1024,
        .description = "Team-based map. Work together to control key positions.",
        .features = &[_][]const u8{ "Team Play", "Strategic Points", "Cooperation" },
    },
    .{
        .name = "Dust_Devil",
        .display_name = "Dust Devil",
        .map_type = .Multiplayer,
        .size = .Medium,
        .max_players = 4,
        .width = 512,
        .height = 512,
        .description = "Dust storms reduce visibility. Dynamic weather effects.",
        .features = &[_][]const u8{ "Sandstorm", "Dynamic Weather", "Desert" },
    },
    .{
        .name = "Barrens",
        .display_name = "The Barrens",
        .map_type = .Multiplayer,
        .size = .Large,
        .max_players = 6,
        .width = 768,
        .height = 768,
        .description = "Desolate rocky terrain. Minimal resources force aggression.",
        .features = &[_][]const u8{ "Rocky", "Low Resources", "Aggressive" },
    },
    .{
        .name = "Free_Fire_Zone",
        .display_name = "Free Fire Zone",
        .map_type = .Multiplayer,
        .size = .Large,
        .max_players = 8,
        .width = 1024,
        .height = 1024,
        .description = "No holds barred. Every weapon and tactic is fair game.",
        .features = &[_][]const u8{ "Free for All", "Chaotic", "All Units" },
    },
    .{
        .name = "Defcon_Six",
        .display_name = "DEFCON Six",
        .map_type = .Multiplayer,
        .size = .Medium,
        .max_players = 4,
        .width = 512,
        .height = 512,
        .description = "Military alert level six. Full combat readiness.",
        .features = &[_][]const u8{ "Military Theme", "Fast Paced", "Intense" },
    },
    // Challenge Maps
    .{
        .name = "Challenge_Survival",
        .display_name = "Challenge: Survival",
        .map_type = .Challenge,
        .size = .Small,
        .max_players = 1,
        .width = 256,
        .height = 256,
        .description = "Survive endless waves of enemies. How long can you last?",
        .features = &[_][]const u8{ "Endless Waves", "Survival", "High Score" },
    },
    .{
        .name = "Challenge_Speed_Build",
        .display_name = "Challenge: Speed Build",
        .map_type = .Challenge,
        .size = .Small,
        .max_players = 1,
        .width = 256,
        .height = 256,
        .description = "Build the fastest army possible. Time trial mode.",
        .features = &[_][]const u8{ "Time Trial", "Economic Test", "Speed Run" },
    },
    .{
        .name = "Challenge_Last_Stand",
        .display_name = "Challenge: Last Stand",
        .map_type = .Challenge,
        .size = .Medium,
        .max_players = 1,
        .width = 512,
        .height = 512,
        .description = "Limited resources. Defeat overwhelming enemy forces.",
        .features = &[_][]const u8{ "Limited Resources", "Overwhelming Odds", "Strategic" },
    },
};

pub fn getMapDef(name: []const u8) ?*const MapDef {
    for (&MAP_DATABASE) |*map| {
        if (std.mem.eql(u8, map.name, name)) return map;
    }
    return null;
}

pub fn getMapsByType(map_type: MapType) []const MapDef {
    var count: usize = 0;
    for (MAP_DATABASE) |map| {
        if (map.map_type == map_type) count += 1;
    }
    // Simplified - real implementation would use allocator
    return &[_]MapDef{};
}

pub fn getMapsBySize(size: MapSize) []const MapDef {
    var count: usize = 0;
    for (MAP_DATABASE) |map| {
        if (map.size == size) count += 1;
    }
    return &[_]MapDef{};
}
