// C&C Generals - Unit Definitions Database
// Based on original EA source code

const std = @import("std");

pub const UnitType = enum {
    // USA Units - Infantry
    USA_Ranger,
    USA_Missile_Defender,
    USA_Pathfinder,
    USA_Colonel_Burton,

    // USA Units - Vehicles
    USA_Humvee,
    USA_Tomahawk,
    USA_Crusader_Tank,
    USA_Paladin_Tank,
    USA_Avenger,
    USA_Ambulance,
    USA_Dozer,
    USA_Supply_Truck,

    // USA Units - Aircraft
    USA_Chinook,
    USA_Comanche,
    USA_Raptor,
    USA_Stealth_Fighter,
    USA_Aurora_Alpha,

    // USA Units - General Specific (Air Force)
    USA_Laser_Crusader,
    USA_Microwave_Tank,
    USA_King_Raptor,
    USA_Combat_Chinook,

    // USA Units - General Specific (Superweapon)
    USA_Paladin_Upgraded,
    USA_Particle_Crusader,
    USA_EMP_Patriot,

    // USA Units - General Specific (Infantry)
    USA_Advanced_Ranger,
    USA_Super_Pathfinder,
    USA_Minigunner,

    // USA Units - Zero Hour Additions
    USA_Humvee_Battle_Drone,
    USA_Sentry_Drone,
    USA_Hellfire_Drone,
    USA_Fire_Base_Guardian,
    USA_Repair_Bulldozer,
    USA_MOAB_Bomber,
    USA_A10_Thunderbolt,
    USA_Spectre_Gunship,
    USA_Radar_Van,
    USA_Spy_Drone,
    USA_Rocket_Defender,
    USA_Pilot,

    // USA Units - Additional Variants
    USA_Humvee_TOW,
    USA_Crusader_Battle_Drone,
    USA_Paladin_Battle_Drone,
    USA_Tomahawk_Battle_Drone,
    USA_Avenger_Battle_Drone,
    USA_Burton_Demo_Team,
    USA_Delta_Force,
    USA_Navy_SEAL,
    USA_Medic,
    USA_Engineer,
    USA_Flash_Bang_Ranger,

    // USA Units - Additional Aircraft
    USA_Comanche_Rocket_Pods,
    USA_Raptor_Bomber,
    USA_Stealth_Comanche,
    USA_Transport_Chinook_Rockets,
    USA_Aurora_Beta,

    // USA Units - Additional Vehicles
    USA_Humvee_Scout,
    USA_Humvee_Ambulance,
    USA_Bradley_IFV,
    USA_M1A2_Abrams,
    USA_HEMTT_Supply,
    USA_Paladin_Artillery,
    USA_MLRS_Rocket,
    USA_Patriot_Mobile,
    USA_Command_Vehicle,
    USA_EMP_Tank,
    USA_Laser_Tank,
    USA_Microwave_Vehicle,
    USA_Repair_Vehicle,

    // China Units
    China_Red_Guard,
    China_Tank_Hunter,
    China_Black_Lotus,
    China_Battlemast,
    China_Overlord,
    China_Gattling_Tank,
    China_Troop_Crawler,
    China_Dragon_Tank,
    China_Inferno_Cannon,
    China_Nuke_Cannon,
    China_ECM_Tank,
    China_Dozer,
    China_Supply_Truck,
    China_Helix,
    China_MiG,

    // GLA Units
    GLA_Rebel,
    GLA_RPG_Trooper,
    GLA_Terrorist,
    GLA_Saboteur,
    GLA_Jarmen_Kell,
    GLA_Technical,
    GLA_Scorpion,
    GLA_Marauder,
    GLA_Quad_Cannon,
    GLA_Toxin_Tractor,
    GLA_Rocket_Buggy,
    GLA_SCUD_Launcher,
    GLA_Battle_Bus,
    GLA_Bomb_Truck,
    GLA_Worker,

    // Add more units...
};

pub const UnitDef = struct {
    name: []const u8,
    display_name: []const u8,
    unit_type: UnitType,
    cost: u32,
    build_time: f32,
    health: u32,
    armor: u32,
    speed: f32,
    vision_range: f32,
    can_attack_ground: bool,
    can_attack_air: bool,
    weapons: []const []const u8,
    upgrades: []const []const u8,
    size: f32,
    experience_value: u32,
    description: []const u8,
};

// Full unit database - this adds significant size to the executable
pub const UNIT_DATABASE = [_]UnitDef{
    .{
        .name = "USA_Ranger",
        .display_name = "Ranger",
        .unit_type = .USA_Ranger,
        .cost = 225,
        .build_time = 5.0,
        .health = 50,
        .armor = 0,
        .speed = 5.0,
        .vision_range = 150.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"M16_Rifle"},
        .upgrades = &[_][]const u8{"Advanced_Training", "Capture_Building"},
        .size = 1.0,
        .experience_value = 5,
        .description = "Basic American infantry unit armed with an M16 assault rifle. Can capture buildings when upgraded.",
    },
    .{
        .name = "USA_Missile_Defender",
        .display_name = "Missile Defender",
        .unit_type = .USA_Missile_Defender,
        .cost = 300,
        .build_time = 6.0,
        .health = 50,
        .armor = 0,
        .speed = 4.5,
        .vision_range = 180.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Stinger_Missile"},
        .upgrades = &[_][]const u8{"Advanced_Training", "Laser_Lock"},
        .size = 1.0,
        .experience_value = 8,
        .description = "Anti-aircraft infantry equipped with Stinger missiles. Effective against aircraft and light vehicles.",
    },
    .{
        .name = "USA_Pathfinder",
        .display_name = "Pathfinder",
        .unit_type = .USA_Pathfinder,
        .cost = 600,
        .build_time = 8.0,
        .health = 45,
        .armor = 0,
        .speed = 4.0,
        .vision_range = 300.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Sniper_Rifle"},
        .upgrades = &[_][]const u8{"Advanced_Training"},
        .size = 1.0,
        .experience_value = 15,
        .description = "Elite sniper with stealth detection and long range. Can instantly kill infantry.",
    },
    .{
        .name = "USA_Colonel_Burton",
        .display_name = "Colonel Burton",
        .unit_type = .USA_Colonel_Burton,
        .cost = 1500,
        .build_time = 20.0,
        .health = 100,
        .armor = 5,
        .speed = 5.5,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Assault_Rifle", "C4_Explosive"},
        .upgrades = &[_][]const u8{},
        .size = 1.0,
        .experience_value = 50,
        .description = "Hero unit. Commando with demolition capabilities and stealth detection.",
    },
    .{
        .name = "USA_Humvee",
        .display_name = "Humvee",
        .unit_type = .USA_Humvee,
        .cost = 700,
        .build_time = 10.0,
        .health = 220,
        .armor = 2,
        .speed = 8.0,
        .vision_range = 150.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"M249_SAW"},
        .upgrades = &[_][]const u8{"TOW_Missile", "Battle_Drone"},
        .size = 2.0,
        .experience_value = 10,
        .description = "Fast scout and transport vehicle. Can be upgraded with TOW missiles or battle drone.",
    },
    .{
        .name = "USA_Crusader_Tank",
        .display_name = "Crusader Tank",
        .unit_type = .USA_Crusader_Tank,
        .cost = 900,
        .build_time = 12.0,
        .health = 400,
        .armor = 10,
        .speed = 6.0,
        .vision_range = 180.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"120mm_Cannon"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone"},
        .size = 3.0,
        .experience_value = 20,
        .description = "Main battle tank with high speed and firepower. Core of USA armor force.",
    },
    .{
        .name = "USA_Paladin_Tank",
        .display_name = "Paladin Tank",
        .unit_type = .USA_Paladin_Tank,
        .cost = 1100,
        .build_time = 14.0,
        .health = 500,
        .armor = 15,
        .speed = 5.0,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"155mm_Cannon", "Point_Defense_Laser"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone"},
        .size = 3.5,
        .experience_value = 30,
        .description = "Heavy tank with point defense laser that shoots down incoming missiles.",
    },
    .{
        .name = "China_Red_Guard",
        .display_name = "Red Guard",
        .unit_type = .China_Red_Guard,
        .cost = 200,
        .build_time = 4.5,
        .health = 60,
        .armor = 0,
        .speed = 4.8,
        .vision_range = 140.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"AK-47"},
        .upgrades = &[_][]const u8{"Nationalism", "Capture_Building"},
        .size = 1.0,
        .experience_value = 5,
        .description = "Chinese basic infantry armed with AK-47. Cheap and numerous.",
    },
    .{
        .name = "China_Battlemast",
        .display_name = "Battlemaster",
        .unit_type = .China_Battlemast,
        .cost = 800,
        .build_time = 11.0,
        .health = 420,
        .armor = 12,
        .speed = 5.5,
        .vision_range = 170.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"125mm_Cannon"},
        .upgrades = &[_][]const u8{"Chain_Guns", "Nationalism", "Nuclear_Shells"},
        .size = 3.2,
        .experience_value = 20,
        .description = "Chinese main battle tank. Can be upgraded with nuclear shells for extra damage.",
    },
    .{
        .name = "China_Overlord",
        .display_name = "Overlord Tank",
        .unit_type = .China_Overlord,
        .cost = 2000,
        .build_time = 25.0,
        .health = 850,
        .armor = 25,
        .speed = 3.5,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Twin_125mm_Cannons"},
        .upgrades = &[_][]const u8{"Chain_Guns", "Nationalism", "Gattling_Cannon", "Propaganda_Tower", "Nuclear_Shells"},
        .size = 5.0,
        .experience_value = 50,
        .description = "Massive super-heavy tank. Can crush other vehicles and be upgraded with various weapons.",
    },
    .{
        .name = "GLA_Rebel",
        .display_name = "Rebel",
        .unit_type = .GLA_Rebel,
        .cost = 150,
        .build_time = 3.0,
        .health = 45,
        .armor = 0,
        .speed = 5.2,
        .vision_range = 130.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"AK-47"},
        .upgrades = &[_][]const u8{"AP_Bullets", "Capture_Building"},
        .size = 1.0,
        .experience_value = 4,
        .description = "GLA basic infantry. Cheap and fast, but weak.",
    },
    .{
        .name = "GLA_Scorpion",
        .display_name = "Scorpion Tank",
        .unit_type = .GLA_Scorpion,
        .cost = 600,
        .build_time = 9.0,
        .health = 300,
        .armor = 8,
        .speed = 7.0,
        .vision_range = 160.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Scorpion_Rocket"},
        .upgrades = &[_][]const u8{"Scorpion_Rocket_Upgrade"},
        .size = 2.5,
        .experience_value = 15,
        .description = "Fast attack tank. Can hide by digging into the ground (stealth).",
    },
    .{
        .name = "USA_Tomahawk",
        .display_name = "Tomahawk Launcher",
        .unit_type = .USA_Tomahawk,
        .cost = 1200,
        .build_time = 15.0,
        .health = 180,
        .armor = 3,
        .speed = 5.5,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Tomahawk_Missile"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone"},
        .size = 2.5,
        .experience_value = 25,
        .description = "Long-range missile launcher. Devastating against buildings and slow units.",
    },
    .{
        .name = "USA_Avenger",
        .display_name = "Avenger",
        .unit_type = .USA_Avenger,
        .cost = 800,
        .build_time = 10.0,
        .health = 200,
        .armor = 2,
        .speed = 7.0,
        .vision_range = 250.0,
        .can_attack_ground = false,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Stinger_Missile"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Laser_Lock", "Battle_Drone"},
        .size = 2.0,
        .experience_value = 15,
        .description = "Mobile anti-aircraft platform. Uses advanced Stinger missiles.",
    },
    .{
        .name = "USA_Ambulance",
        .display_name = "Ambulance",
        .unit_type = .USA_Ambulance,
        .cost = 600,
        .build_time = 8.0,
        .health = 250,
        .armor = 1,
        .speed = 7.5,
        .vision_range = 150.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Composite_Armor"},
        .size = 2.0,
        .experience_value = 5,
        .description = "Medical vehicle. Heals nearby infantry and can pick up wounded soldiers.",
    },
    .{
        .name = "USA_Dozer",
        .display_name = "Construction Dozer",
        .unit_type = .USA_Dozer,
        .cost = 1000,
        .build_time = 20.0,
        .health = 300,
        .armor = 0,
        .speed = 4.0,
        .vision_range = 150.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 3.0,
        .experience_value = 0,
        .description = "Constructs buildings. Essential for base expansion.",
    },
    .{
        .name = "USA_Supply_Truck",
        .display_name = "Supply Truck",
        .unit_type = .USA_Supply_Truck,
        .cost = 600,
        .build_time = 10.0,
        .health = 150,
        .armor = 0,
        .speed = 6.5,
        .vision_range = 120.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 2.5,
        .experience_value = 0,
        .description = "Collects supplies and brings them to Supply Center. Primary economy unit.",
    },
    .{
        .name = "USA_Chinook",
        .display_name = "Chinook Transport",
        .unit_type = .USA_Chinook,
        .cost = 1200,
        .build_time = 15.0,
        .health = 400,
        .armor = 2,
        .speed = 9.0,
        .vision_range = 200.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Countermeasures"},
        .size = 4.0,
        .experience_value = 10,
        .description = "Heavy transport helicopter. Can carry infantry and vehicles. Collects supplies.",
    },
    .{
        .name = "USA_Comanche",
        .display_name = "Comanche",
        .unit_type = .USA_Comanche,
        .cost = 1500,
        .build_time = 18.0,
        .health = 320,
        .armor = 5,
        .speed = 10.0,
        .vision_range = 250.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Hellfire_Missile", "Vulcan_Cannon"},
        .upgrades = &[_][]const u8{"Countermeasures", "Laser_Missiles"},
        .size = 3.5,
        .experience_value = 30,
        .description = "Attack helicopter with stealth technology. Versatile anti-armor platform.",
    },
    .{
        .name = "USA_Raptor",
        .display_name = "F-22 Raptor",
        .unit_type = .USA_Raptor,
        .cost = 1400,
        .build_time = 16.0,
        .health = 280,
        .armor = 3,
        .speed = 15.0,
        .vision_range = 300.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Sidewinder_Missile"},
        .upgrades = &[_][]const u8{"Countermeasures", "Laser_Missiles"},
        .size = 3.0,
        .experience_value = 25,
        .description = "Air superiority fighter. Fast and deadly against air and ground targets.",
    },
    .{
        .name = "USA_Stealth_Fighter",
        .display_name = "Stealth Fighter",
        .unit_type = .USA_Stealth_Fighter,
        .cost = 1600,
        .build_time = 20.0,
        .health = 260,
        .armor = 2,
        .speed = 12.0,
        .vision_range = 250.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"JDAM_Bomb"},
        .upgrades = &[_][]const u8{"Countermeasures"},
        .size = 3.5,
        .experience_value = 35,
        .description = "Stealth bomber. Invisible to enemy radar. Devastating against structures.",
    },
    .{
        .name = "USA_Aurora_Alpha",
        .display_name = "Aurora Alpha",
        .unit_type = .USA_Aurora_Alpha,
        .cost = 2500,
        .build_time = 25.0,
        .health = 300,
        .armor = 4,
        .speed = 20.0,
        .vision_range = 350.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Fuel_Air_Bomb"},
        .upgrades = &[_][]const u8{},
        .size = 4.0,
        .experience_value = 50,
        .description = "Hypersonic bomber. Extremely fast, drops devastating fuel-air bombs.",
    },
    // ========== USA General-Specific Units (Air Force General) ==========
    .{
        .name = "USA_Laser_Crusader",
        .display_name = "Crusader (Laser)",
        .unit_type = .USA_Laser_Crusader,
        .cost = 1200,
        .build_time = 14.0,
        .health = 400,
        .armor = 10,
        .speed = 6.0,
        .vision_range = 180.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Point_Defense_Laser"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone"},
        .size = 3.0,
        .experience_value = 25,
        .description = "Air Force General's Crusader with point defense laser that shoots down missiles and aircraft.",
    },
    .{
        .name = "USA_Microwave_Tank",
        .display_name = "Microwave Tank",
        .unit_type = .USA_Microwave_Tank,
        .cost = 800,
        .build_time = 11.0,
        .health = 300,
        .armor = 8,
        .speed = 6.5,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Microwave_Beam"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone"},
        .size = 3.0,
        .experience_value = 20,
        .description = "Experimental vehicle. Microwave beam disables enemy vehicles and clears mines.",
    },
    .{
        .name = "USA_King_Raptor",
        .display_name = "King Raptor",
        .unit_type = .USA_King_Raptor,
        .cost = 1600,
        .build_time = 18.0,
        .health = 320,
        .armor = 5,
        .speed = 16.0,
        .vision_range = 350.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Bunker_Buster_Missile", "Sidewinder_Missile"},
        .upgrades = &[_][]const u8{"Countermeasures", "Laser_Missiles"},
        .size = 3.5,
        .experience_value = 35,
        .description = "Air Force General's enhanced Raptor with bunker-buster missiles.",
    },
    .{
        .name = "USA_Combat_Chinook",
        .display_name = "Combat Chinook",
        .unit_type = .USA_Combat_Chinook,
        .cost = 1400,
        .build_time = 16.0,
        .health = 450,
        .armor = 4,
        .speed = 9.0,
        .vision_range = 220.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Vulcan_Cannon"},
        .upgrades = &[_][]const u8{"Countermeasures"},
        .size = 4.5,
        .experience_value = 30,
        .description = "Armed Chinook with door guns. Can transport troops and provide fire support.",
    },
    // ========== USA General-Specific Units (Superweapon General) ==========
    .{
        .name = "USA_Paladin_Upgraded",
        .display_name = "Paladin (Advanced)",
        .unit_type = .USA_Paladin_Upgraded,
        .cost = 1300,
        .build_time = 16.0,
        .health = 550,
        .armor = 18,
        .speed = 5.5,
        .vision_range = 220.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"155mm_Cannon", "Point_Defense_Laser", "TOW_Missile"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone"},
        .size = 3.8,
        .experience_value = 35,
        .description = "Superweapon General's enhanced Paladin with additional weapons systems.",
    },
    .{
        .name = "USA_Particle_Crusader",
        .display_name = "Particle Cannon Crusader",
        .unit_type = .USA_Particle_Crusader,
        .cost = 1400,
        .build_time = 15.0,
        .health = 420,
        .armor = 12,
        .speed = 5.8,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Miniature_Particle_Beam"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone"},
        .size = 3.2,
        .experience_value = 30,
        .description = "Experimental tank armed with miniature particle beam cannon.",
    },
    .{
        .name = "USA_EMP_Patriot",
        .display_name = "EMP Patriot Battery",
        .unit_type = .USA_EMP_Patriot,
        .cost = 1000,
        .build_time = 12.0,
        .health = 200,
        .armor = 5,
        .speed = 4.0,
        .vision_range = 250.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"EMP_Missile"},
        .upgrades = &[_][]const u8{},
        .size = 3.5,
        .experience_value = 25,
        .description = "Mobile Patriot system with EMP missiles. Disables vehicles and aircraft.",
    },
    // ========== USA General-Specific Units (Infantry General) ==========
    .{
        .name = "USA_Advanced_Ranger",
        .display_name = "Advanced Ranger",
        .unit_type = .USA_Advanced_Ranger,
        .cost = 300,
        .build_time = 6.0,
        .health = 60,
        .armor = 1,
        .speed = 5.5,
        .vision_range = 170.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"M16_Rifle", "Flashbang_Grenade"},
        .upgrades = &[_][]const u8{"Advanced_Training", "Capture_Building", "AP_Bullets"},
        .size = 1.0,
        .experience_value = 8,
        .description = "Infantry General's improved Ranger with flashbang grenades.",
    },
    .{
        .name = "USA_Super_Pathfinder",
        .display_name = "Super Pathfinder",
        .unit_type = .USA_Super_Pathfinder,
        .cost = 800,
        .build_time = 10.0,
        .health = 55,
        .armor = 0,
        .speed = 4.5,
        .vision_range = 350.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Advanced_Sniper_Rifle"},
        .upgrades = &[_][]const u8{"Advanced_Training"},
        .size = 1.0,
        .experience_value = 20,
        .description = "Elite sniper with enhanced optics. Can kill drivers to capture vehicles.",
    },
    .{
        .name = "USA_Minigunner",
        .display_name = "Minigunner",
        .unit_type = .USA_Minigunner,
        .cost = 350,
        .build_time = 7.0,
        .health = 50,
        .armor = 0,
        .speed = 5.0,
        .vision_range = 150.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Minigun"},
        .upgrades = &[_][]const u8{"Advanced_Training"},
        .size = 1.0,
        .experience_value = 10,
        .description = "Heavy weapons infantry with minigun. Effective against infantry and aircraft.",
    },
    // ========== USA Zero Hour Additions ==========
    .{
        .name = "USA_Humvee_Battle_Drone",
        .display_name = "Humvee (Battle Drone)",
        .unit_type = .USA_Humvee_Battle_Drone,
        .cost = 900,
        .build_time = 12.0,
        .health = 240,
        .armor = 3,
        .speed = 8.0,
        .vision_range = 170.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"M249_SAW", "Drone_Machine_Gun"},
        .upgrades = &[_][]const u8{"TOW_Missile"},
        .size = 2.5,
        .experience_value = 15,
        .description = "Humvee with integrated battle drone for additional firepower and repairs.",
    },
    .{
        .name = "USA_Sentry_Drone",
        .display_name = "Sentry Drone",
        .unit_type = .USA_Sentry_Drone,
        .cost = 500,
        .build_time = 8.0,
        .health = 80,
        .armor = 0,
        .speed = 12.0,
        .vision_range = 250.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Machine_Gun"},
        .upgrades = &[_][]const u8{},
        .size = 0.8,
        .experience_value = 5,
        .description = "Autonomous sentry drone. Provides reconnaissance and light fire support.",
    },
    .{
        .name = "USA_Hellfire_Drone",
        .display_name = "Hellfire Drone",
        .unit_type = .USA_Hellfire_Drone,
        .cost = 800,
        .build_time = 10.0,
        .health = 100,
        .armor = 1,
        .speed = 10.0,
        .vision_range = 220.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Hellfire_Missile"},
        .upgrades = &[_][]const u8{},
        .size = 1.0,
        .experience_value = 15,
        .description = "Attack drone armed with Hellfire missiles. Deadly against vehicles.",
    },
    .{
        .name = "USA_Fire_Base_Guardian",
        .display_name = "Fire Base Guardian",
        .unit_type = .USA_Fire_Base_Guardian,
        .cost = 400,
        .build_time = 6.0,
        .health = 50,
        .armor = 0,
        .speed = 5.2,
        .vision_range = 160.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"M16_Rifle"},
        .upgrades = &[_][]const u8{"Advanced_Training"},
        .size = 1.0,
        .experience_value = 10,
        .description = "Garrison infantry for Fire Bases. Better trained than regular Rangers.",
    },
    .{
        .name = "USA_Repair_Bulldozer",
        .display_name = "Repair Bulldozer",
        .unit_type = .USA_Repair_Bulldozer,
        .cost = 1200,
        .build_time = 22.0,
        .health = 350,
        .armor = 0,
        .speed = 3.5,
        .vision_range = 150.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 3.2,
        .experience_value = 0,
        .description = "Heavy construction vehicle. Can build AND repair structures during construction.",
    },
    .{
        .name = "USA_MOAB_Bomber",
        .display_name = "MOAB Bomber",
        .unit_type = .USA_MOAB_Bomber,
        .cost = 3000,
        .build_time = 30.0,
        .health = 400,
        .armor = 8,
        .speed = 14.0,
        .vision_range = 400.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"MOAB"},
        .upgrades = &[_][]const u8{},
        .size = 5.0,
        .experience_value = 60,
        .description = "Massive Ordnance Air Blast. Drops the Mother Of All Bombs. One-time use.",
    },
    .{
        .name = "USA_A10_Thunderbolt",
        .display_name = "A-10 Thunderbolt",
        .unit_type = .USA_A10_Thunderbolt,
        .cost = 1800,
        .build_time = 20.0,
        .health = 350,
        .armor = 10,
        .speed = 12.0,
        .vision_range = 300.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"GAU_8_Avenger"},
        .upgrades = &[_][]const u8{},
        .size = 4.0,
        .experience_value = 40,
        .description = "Tank buster. Heavily armored ground attack aircraft with 30mm cannon.",
    },
    .{
        .name = "USA_Spectre_Gunship",
        .display_name = "AC-130 Spectre",
        .unit_type = .USA_Spectre_Gunship,
        .cost = 2200,
        .build_time = 24.0,
        .health = 500,
        .armor = 12,
        .speed = 8.0,
        .vision_range = 350.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"105mm_Howitzer", "40mm_Bofors", "25mm_Gatling"},
        .upgrades = &[_][]const u8{},
        .size = 6.0,
        .experience_value = 50,
        .description = "Flying fortress. Multiple weapons provide devastating ground support.",
    },
    .{
        .name = "USA_Radar_Van",
        .display_name = "Radar Van",
        .unit_type = .USA_Radar_Van,
        .cost = 800,
        .build_time = 12.0,
        .health = 200,
        .armor = 1,
        .speed = 6.0,
        .vision_range = 400.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 2.5,
        .experience_value = 5,
        .description = "Mobile radar. Detects stealth units and provides radar coverage.",
    },
    .{
        .name = "USA_Spy_Drone",
        .display_name = "Spy Drone",
        .unit_type = .USA_Spy_Drone,
        .cost = 600,
        .build_time = 8.0,
        .health = 60,
        .armor = 0,
        .speed = 14.0,
        .vision_range = 300.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 0.5,
        .experience_value = 0,
        .description = "Stealth reconnaissance drone. Invisible to enemy radar. Provides vision.",
    },
    .{
        .name = "USA_Rocket_Defender",
        .display_name = "Rocket Defender",
        .unit_type = .USA_Rocket_Defender,
        .cost = 400,
        .build_time = 7.0,
        .health = 50,
        .armor = 0,
        .speed = 4.5,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Multi_Rocket_Launcher"},
        .upgrades = &[_][]const u8{"Advanced_Training", "Laser_Lock"},
        .size = 1.0,
        .experience_value = 12,
        .description = "Enhanced Missile Defender with rapid-fire rocket launcher. Anti-air specialist.",
    },
    .{
        .name = "USA_Pilot",
        .display_name = "Pilot",
        .unit_type = .USA_Pilot,
        .cost = 0,
        .build_time = 0.0,
        .health = 25,
        .armor = 0,
        .speed = 4.0,
        .vision_range = 120.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Pistol"},
        .upgrades = &[_][]const u8{},
        .size = 1.0,
        .experience_value = 0,
        .description = "Ejected pilot. Weak but can be rescued. Returns to base when picked up.",
    },
    // ========== USA Additional Variants ==========
    .{
        .name = "USA_Humvee_TOW",
        .display_name = "Humvee (TOW)",
        .unit_type = .USA_Humvee_TOW,
        .cost = 900,
        .build_time = 12.0,
        .health = 220,
        .armor = 2,
        .speed = 8.0,
        .vision_range = 180.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"TOW_Missile"},
        .upgrades = &[_][]const u8{"Battle_Drone"},
        .size = 2.0,
        .experience_value = 15,
        .description = "Humvee upgraded with TOW anti-tank missile launcher.",
    },
    .{
        .name = "USA_Crusader_Battle_Drone",
        .display_name = "Crusader (Drone)",
        .unit_type = .USA_Crusader_Battle_Drone,
        .cost = 1100,
        .build_time = 14.0,
        .health = 420,
        .armor = 10,
        .speed = 6.0,
        .vision_range = 180.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"120mm_Cannon", "Drone_Machine_Gun"},
        .upgrades = &[_][]const u8{"Composite_Armor"},
        .size = 3.0,
        .experience_value = 22,
        .description = "Crusader tank with integrated battle drone for repairs and support fire.",
    },
    .{
        .name = "USA_Paladin_Battle_Drone",
        .display_name = "Paladin (Drone)",
        .unit_type = .USA_Paladin_Battle_Drone,
        .cost = 1300,
        .build_time = 16.0,
        .health = 520,
        .armor = 15,
        .speed = 5.0,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"155mm_Cannon", "Point_Defense_Laser", "Drone_Machine_Gun"},
        .upgrades = &[_][]const u8{"Composite_Armor"},
        .size = 3.5,
        .experience_value = 32,
        .description = "Paladin tank with battle drone providing additional firepower and repairs.",
    },
    .{
        .name = "USA_Tomahawk_Battle_Drone",
        .display_name = "Tomahawk (Drone)",
        .unit_type = .USA_Tomahawk_Battle_Drone,
        .cost = 1400,
        .build_time = 17.0,
        .health = 200,
        .armor = 3,
        .speed = 5.5,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Tomahawk_Missile", "Drone_Machine_Gun"},
        .upgrades = &[_][]const u8{"Composite_Armor"},
        .size = 2.5,
        .experience_value = 27,
        .description = "Tomahawk launcher with battle drone for close-range defense.",
    },
    .{
        .name = "USA_Avenger_Battle_Drone",
        .display_name = "Avenger (Drone)",
        .unit_type = .USA_Avenger_Battle_Drone,
        .cost = 1000,
        .build_time = 12.0,
        .health = 220,
        .armor = 2,
        .speed = 7.0,
        .vision_range = 250.0,
        .can_attack_ground = false,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Stinger_Missile", "Drone_Machine_Gun"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Laser_Lock"},
        .size = 2.0,
        .experience_value = 18,
        .description = "Avenger with battle drone providing ground defense capability.",
    },
    .{
        .name = "USA_Burton_Demo_Team",
        .display_name = "Burton's Demo Team",
        .unit_type = .USA_Burton_Demo_Team,
        .cost = 800,
        .build_time = 12.0,
        .health = 70,
        .armor = 3,
        .speed = 5.5,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Assault_Rifle", "Demo_Charge"},
        .upgrades = &[_][]const u8{},
        .size = 1.0,
        .experience_value = 25,
        .description = "Elite demolitions expert. Can plant timed charges on buildings. Limited availability.",
    },
    .{
        .name = "USA_Delta_Force",
        .display_name = "Delta Force",
        .unit_type = .USA_Delta_Force,
        .cost = 900,
        .build_time = 14.0,
        .health = 80,
        .armor = 2,
        .speed = 5.8,
        .vision_range = 220.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Advanced_Carbine", "Flashbang_Grenade"},
        .upgrades = &[_][]const u8{"Advanced_Training"},
        .size = 1.0,
        .experience_value = 30,
        .description = "Elite special forces. Superior combat abilities and can rappel from buildings.",
    },
    .{
        .name = "USA_Navy_SEAL",
        .display_name = "Navy SEAL",
        .unit_type = .USA_Navy_SEAL,
        .cost = 1000,
        .build_time = 15.0,
        .health = 85,
        .armor = 2,
        .speed = 6.0,
        .vision_range = 240.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"SEAL_Carbine", "C4_Explosive"},
        .upgrades = &[_][]const u8{},
        .size = 1.0,
        .experience_value = 35,
        .description = "Naval special warfare operator. Can swim and plant C4 charges. Excellent vs buildings.",
    },
    .{
        .name = "USA_Medic",
        .display_name = "Combat Medic",
        .unit_type = .USA_Medic,
        .cost = 300,
        .build_time = 5.0,
        .health = 40,
        .armor = 0,
        .speed = 5.0,
        .vision_range = 140.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Advanced_Training"},
        .size = 1.0,
        .experience_value = 0,
        .description = "Heals nearby infantry. Unarmed. Essential for keeping infantry alive.",
    },
    .{
        .name = "USA_Engineer",
        .display_name = "Engineer",
        .unit_type = .USA_Engineer,
        .cost = 500,
        .build_time = 8.0,
        .health = 50,
        .armor = 0,
        .speed = 4.5,
        .vision_range = 150.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 1.0,
        .experience_value = 0,
        .description = "Repairs vehicles and buildings. Can capture tech structures.",
    },
    .{
        .name = "USA_Flash_Bang_Ranger",
        .display_name = "Flashbang Ranger",
        .unit_type = .USA_Flash_Bang_Ranger,
        .cost = 275,
        .build_time = 6.0,
        .health = 55,
        .armor = 0,
        .speed = 5.2,
        .vision_range = 160.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"M16_Rifle", "Flashbang_Grenade"},
        .upgrades = &[_][]const u8{"Advanced_Training", "Capture_Building"},
        .size = 1.0,
        .experience_value = 7,
        .description = "Ranger with flashbang grenades to stun enemies.",
    },
    // ========== USA Additional Aircraft ==========
    .{
        .name = "USA_Comanche_Rocket_Pods",
        .display_name = "Comanche (Rockets)",
        .unit_type = .USA_Comanche_Rocket_Pods,
        .cost = 1700,
        .build_time = 20.0,
        .health = 340,
        .armor = 5,
        .speed = 11.0,
        .vision_range = 260.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Hellfire_Missile", "Rocket_Pod"},
        .upgrades = &[_][]const u8{"Countermeasures", "Laser_Missiles"},
        .size = 3.5,
        .experience_value = 35,
        .description = "Comanche with additional rocket pods for area suppression.",
    },
    .{
        .name = "USA_Raptor_Bomber",
        .display_name = "Raptor (Bomber)",
        .unit_type = .USA_Raptor_Bomber,
        .cost = 1600,
        .build_time = 18.0,
        .health = 300,
        .armor = 4,
        .speed = 15.0,
        .vision_range = 320.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Cluster_Bomb"},
        .upgrades = &[_][]const u8{"Countermeasures"},
        .size = 3.5,
        .experience_value = 30,
        .description = "F-22 configured for ground attack with cluster bombs.",
    },
    .{
        .name = "USA_Stealth_Comanche",
        .display_name = "Stealth Comanche",
        .unit_type = .USA_Stealth_Comanche,
        .cost = 1800,
        .build_time = 22.0,
        .health = 320,
        .armor = 5,
        .speed = 10.0,
        .vision_range = 250.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Hellfire_Missile", "Vulcan_Cannon"},
        .upgrades = &[_][]const u8{"Countermeasures", "Laser_Missiles"},
        .size = 3.5,
        .experience_value = 40,
        .description = "Enhanced stealth variant with improved radar invisibility.",
    },
    .{
        .name = "USA_Transport_Chinook_Rockets",
        .display_name = "Chinook (Armed)",
        .unit_type = .USA_Transport_Chinook_Rockets,
        .cost = 1500,
        .build_time = 18.0,
        .health = 450,
        .armor = 4,
        .speed = 9.5,
        .vision_range = 220.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Rocket_Pod", "Door_Gun"},
        .upgrades = &[_][]const u8{"Countermeasures"},
        .size = 4.5,
        .experience_value = 35,
        .description = "Chinook with rocket pods and door guns for fire support during transport.",
    },
    .{
        .name = "USA_Aurora_Beta",
        .display_name = "Aurora Beta",
        .unit_type = .USA_Aurora_Beta,
        .cost = 2800,
        .build_time = 28.0,
        .health = 320,
        .armor = 5,
        .speed = 22.0,
        .vision_range = 370.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Fuel_Air_Bomb", "Cluster_Bomb"},
        .upgrades = &[_][]const u8{},
        .size = 4.5,
        .experience_value = 60,
        .description = "Enhanced Aurora with dual payload capability. Even faster than Alpha variant.",
    },
    // ========== USA Additional Vehicles ==========
    .{
        .name = "USA_Humvee_Scout",
        .display_name = "Humvee (Scout)",
        .unit_type = .USA_Humvee_Scout,
        .cost = 600,
        .build_time = 9.0,
        .health = 200,
        .armor = 1,
        .speed = 9.0,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"M249_SAW"},
        .upgrades = &[_][]const u8{},
        .size = 2.0,
        .experience_value = 8,
        .description = "Lightly armed reconnaissance vehicle. Fast with extended vision range.",
    },
    .{
        .name = "USA_Humvee_Ambulance",
        .display_name = "Humvee (Ambulance)",
        .unit_type = .USA_Humvee_Ambulance,
        .cost = 700,
        .build_time = 10.0,
        .health = 240,
        .armor = 2,
        .speed = 7.5,
        .vision_range = 150.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Composite_Armor"},
        .size = 2.0,
        .experience_value = 5,
        .description = "Medical transport. Heals infantry and evacuates wounded.",
    },
    .{
        .name = "USA_Bradley_IFV",
        .display_name = "Bradley Fighting Vehicle",
        .unit_type = .USA_Bradley_IFV,
        .cost = 1100,
        .build_time = 14.0,
        .health = 380,
        .armor = 8,
        .speed = 6.5,
        .vision_range = 190.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"25mm_Cannon", "TOW_Missile"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone"},
        .size = 3.0,
        .experience_value = 25,
        .description = "Infantry fighting vehicle. Transports troops and provides fire support.",
    },
    .{
        .name = "USA_M1A2_Abrams",
        .display_name = "M1A2 Abrams",
        .unit_type = .USA_M1A2_Abrams,
        .cost = 1000,
        .build_time = 13.0,
        .health = 450,
        .armor = 12,
        .speed = 5.8,
        .vision_range = 185.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"120mm_Cannon", "Coaxial_MG"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone", "Depleted_Uranium_Shells"},
        .size = 3.2,
        .experience_value = 25,
        .description = "Advanced main battle tank. Excellent armor and firepower.",
    },
    .{
        .name = "USA_HEMTT_Supply",
        .display_name = "HEMTT Supply Truck",
        .unit_type = .USA_HEMTT_Supply,
        .cost = 700,
        .build_time = 11.0,
        .health = 180,
        .armor = 0,
        .speed = 6.0,
        .vision_range = 120.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 3.0,
        .experience_value = 0,
        .description = "Heavy supply truck. Carries more supplies than standard supply truck.",
    },
    .{
        .name = "USA_Paladin_Artillery",
        .display_name = "M109 Paladin Artillery",
        .unit_type = .USA_Paladin_Artillery,
        .cost = 1400,
        .build_time = 18.0,
        .health = 280,
        .armor = 4,
        .speed = 4.5,
        .vision_range = 250.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"155mm_Howitzer"},
        .upgrades = &[_][]const u8{},
        .size = 3.5,
        .experience_value = 30,
        .description = "Self-propelled artillery. Long range indirect fire support.",
    },
    .{
        .name = "USA_MLRS_Rocket",
        .display_name = "MLRS",
        .unit_type = .USA_MLRS_Rocket,
        .cost = 1600,
        .build_time = 20.0,
        .health = 260,
        .armor = 3,
        .speed = 5.0,
        .vision_range = 270.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"MLRS_Rockets"},
        .upgrades = &[_][]const u8{},
        .size = 3.8,
        .experience_value = 35,
        .description = "Multiple Launch Rocket System. Devastating area saturation fire.",
    },
    .{
        .name = "USA_Patriot_Mobile",
        .display_name = "Mobile Patriot",
        .unit_type = .USA_Patriot_Mobile,
        .cost = 1200,
        .build_time = 16.0,
        .health = 240,
        .armor = 4,
        .speed = 5.5,
        .vision_range = 280.0,
        .can_attack_ground = false,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Patriot_Missile"},
        .upgrades = &[_][]const u8{},
        .size = 3.5,
        .experience_value = 28,
        .description = "Mobile Patriot missile system. Provides anti-aircraft coverage on the move.",
    },
    .{
        .name = "USA_Command_Vehicle",
        .display_name = "Command Vehicle",
        .unit_type = .USA_Command_Vehicle,
        .cost = 2000,
        .build_time = 25.0,
        .health = 400,
        .armor = 10,
        .speed = 5.0,
        .vision_range = 350.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 4.0,
        .experience_value = 10,
        .description = "Mobile command center. Provides radar and increases nearby unit effectiveness.",
    },
    .{
        .name = "USA_EMP_Tank",
        .display_name = "EMP Tank",
        .unit_type = .USA_EMP_Tank,
        .cost = 1500,
        .build_time = 18.0,
        .health = 350,
        .armor = 9,
        .speed = 5.5,
        .vision_range = 210.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"EMP_Cannon"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone"},
        .size = 3.3,
        .experience_value = 30,
        .description = "Electromagnetic pulse weapon. Disables vehicles and electronics temporarily.",
    },
    .{
        .name = "USA_Laser_Tank",
        .display_name = "Laser Tank",
        .unit_type = .USA_Laser_Tank,
        .cost = 1600,
        .build_time = 19.0,
        .health = 370,
        .armor = 10,
        .speed = 5.8,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Tactical_Laser"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone"},
        .size = 3.2,
        .experience_value = 32,
        .description = "Advanced energy weapon platform. Laser beam melts through armor.",
    },
    .{
        .name = "USA_Microwave_Vehicle",
        .display_name = "Microwave Vehicle",
        .unit_type = .USA_Microwave_Vehicle,
        .cost = 900,
        .build_time = 12.0,
        .health = 320,
        .armor = 8,
        .speed = 6.2,
        .vision_range = 195.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Microwave_Beam"},
        .upgrades = &[_][]const u8{"Composite_Armor"},
        .size = 3.0,
        .experience_value = 22,
        .description = "Microwave emitter disables vehicles and clears mines. Non-lethal weapon.",
    },
    .{
        .name = "USA_Repair_Vehicle",
        .display_name = "Repair Vehicle",
        .unit_type = .USA_Repair_Vehicle,
        .cost = 800,
        .build_time = 11.0,
        .health = 300,
        .armor = 2,
        .speed = 5.5,
        .vision_range = 150.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 2.8,
        .experience_value = 0,
        .description = "Mobile repair platform. Repairs vehicles in the field.",
    },
    .{
        .name = "China_Tank_Hunter",
        .display_name = "Tank Hunter",
        .unit_type = .China_Tank_Hunter,
        .cost = 300,
        .build_time = 6.0,
        .health = 50,
        .armor = 0,
        .speed = 4.8,
        .vision_range = 160.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Dragon_Anti_Tank_Missile"},
        .upgrades = &[_][]const u8{"Nationalism"},
        .size = 1.0,
        .experience_value = 10,
        .description = "Anti-tank infantry. Effective against vehicles, weak against infantry.",
    },
    .{
        .name = "China_Black_Lotus",
        .display_name = "Black Lotus",
        .unit_type = .China_Black_Lotus,
        .cost = 1500,
        .build_time = 20.0,
        .health = 100,
        .armor = 0,
        .speed = 5.5,
        .vision_range = 200.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 1.0,
        .experience_value = 50,
        .description = "Hero unit. Stealth infiltrator. Can hack buildings and vehicles to steal cash.",
    },
    .{
        .name = "China_Gattling_Tank",
        .display_name = "Gattling Tank",
        .unit_type = .China_Gattling_Tank,
        .cost = 800,
        .build_time = 11.0,
        .health = 350,
        .armor = 8,
        .speed = 6.0,
        .vision_range = 180.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Gattling_Gun"},
        .upgrades = &[_][]const u8{"Chain_Guns", "Nationalism"},
        .size = 2.8,
        .experience_value = 18,
        .description = "Anti-infantry and anti-air tank. Fire rate increases over time when attacking.",
    },
    .{
        .name = "China_Troop_Crawler",
        .display_name = "Troop Crawler",
        .unit_type = .China_Troop_Crawler,
        .cost = 1400,
        .build_time = 16.0,
        .health = 500,
        .armor = 12,
        .speed = 5.0,
        .vision_range = 170.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Napalm_Cannon"},
        .upgrades = &[_][]const u8{"Nationalism"},
        .size = 3.5,
        .experience_value = 25,
        .description = "Armored transport. Can carry infantry and has bunker slots for fire ports.",
    },
    .{
        .name = "China_Dragon_Tank",
        .display_name = "Dragon Tank",
        .unit_type = .China_Dragon_Tank,
        .cost = 800,
        .build_time = 11.0,
        .health = 330,
        .armor = 6,
        .speed = 5.5,
        .vision_range = 150.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Flamethrower"},
        .upgrades = &[_][]const u8{"Black_Napalm", "Nationalism"},
        .size = 2.7,
        .experience_value = 18,
        .description = "Flame tank. Excellent against infantry and buildings. Leaves fire trails.",
    },
    .{
        .name = "China_Inferno_Cannon",
        .display_name = "Inferno Cannon",
        .unit_type = .China_Inferno_Cannon,
        .cost = 900,
        .build_time = 12.0,
        .health = 280,
        .armor = 4,
        .speed = 4.5,
        .vision_range = 220.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Inferno_Shell"},
        .upgrades = &[_][]const u8{"Black_Napalm", "Nationalism"},
        .size = 3.0,
        .experience_value = 22,
        .description = "Artillery. Fires napalm shells over long distances. Effective vs structures.",
    },
    .{
        .name = "China_Nuke_Cannon",
        .display_name = "Nuke Cannon",
        .unit_type = .China_Nuke_Cannon,
        .cost = 1600,
        .build_time = 20.0,
        .health = 300,
        .armor = 5,
        .speed = 4.0,
        .vision_range = 250.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Tactical_Nuke"},
        .upgrades = &[_][]const u8{"Nationalism"},
        .size = 3.5,
        .experience_value = 40,
        .description = "Nuclear artillery. Fires tactical nukes. Leaves radiation. Devastating.",
    },
    .{
        .name = "China_ECM_Tank",
        .display_name = "ECM Tank",
        .unit_type = .China_ECM_Tank,
        .cost = 800,
        .build_time = 10.0,
        .health = 350,
        .armor = 7,
        .speed = 6.0,
        .vision_range = 200.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Nationalism"},
        .size = 2.5,
        .experience_value = 12,
        .description = "Electronic countermeasures. Jams enemy radar and missiles in area.",
    },
    .{
        .name = "China_Dozer",
        .display_name = "Dozer",
        .unit_type = .China_Dozer,
        .cost = 1000,
        .build_time = 20.0,
        .health = 320,
        .armor = 0,
        .speed = 4.0,
        .vision_range = 150.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 3.0,
        .experience_value = 0,
        .description = "Chinese construction vehicle. Builds structures.",
    },
    .{
        .name = "China_Supply_Truck",
        .display_name = "Supply Truck",
        .unit_type = .China_Supply_Truck,
        .cost = 600,
        .build_time = 10.0,
        .health = 170,
        .armor = 0,
        .speed = 6.0,
        .vision_range = 120.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 2.5,
        .experience_value = 0,
        .description = "Gathers supplies from Supply Center. Core economy unit.",
    },
    .{
        .name = "China_Helix",
        .display_name = "Helix",
        .unit_type = .China_Helix,
        .cost = 1500,
        .build_time = 18.0,
        .health = 500,
        .armor = 8,
        .speed = 8.0,
        .vision_range = 220.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Napalm_Bomb"},
        .upgrades = &[_][]const u8{"Gattling_Cannon", "Bunker", "Propaganda_Tower", "Nationalism"},
        .size = 4.5,
        .experience_value = 30,
        .description = "Heavy assault helicopter. Can be upgraded with weapons or troop bunker.",
    },
    .{
        .name = "China_MiG",
        .display_name = "MiG",
        .unit_type = .China_MiG,
        .cost = 1200,
        .build_time = 14.0,
        .health = 260,
        .armor = 3,
        .speed = 14.0,
        .vision_range = 280.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"AA_Missile", "Napalm_Bomb"},
        .upgrades = &[_][]const u8{"Black_Napalm", "Nationalism"},
        .size = 3.0,
        .experience_value = 25,
        .description = "Multi-role fighter. Can engage air and ground targets.",
    },
    .{
        .name = "GLA_RPG_Trooper",
        .display_name = "RPG Trooper",
        .unit_type = .GLA_RPG_Trooper,
        .cost = 225,
        .build_time = 4.5,
        .health = 50,
        .armor = 0,
        .speed = 4.5,
        .vision_range = 150.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"RPG"},
        .upgrades = &[_][]const u8{"AP_Rockets"},
        .size = 1.0,
        .experience_value = 8,
        .description = "Anti-vehicle infantry. RPG effective against vehicles and aircraft.",
    },
    .{
        .name = "GLA_Terrorist",
        .display_name = "Terrorist",
        .unit_type = .GLA_Terrorist,
        .cost = 200,
        .build_time = 3.5,
        .health = 50,
        .armor = 0,
        .speed = 5.5,
        .vision_range = 140.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Explosive_Vest"},
        .upgrades = &[_][]const u8{"Anthrax_Gamma"},
        .size = 1.0,
        .experience_value = 10,
        .description = "Suicide bomber. Runs at enemies and explodes. Can enter buildings.",
    },
    .{
        .name = "GLA_Saboteur",
        .display_name = "Saboteur",
        .unit_type = .GLA_Saboteur,
        .cost = 800,
        .build_time = 10.0,
        .health = 80,
        .armor = 0,
        .speed = 5.8,
        .vision_range = 180.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 1.0,
        .experience_value = 20,
        .description = "Stealth unit. Can plant explosives on buildings and vehicles.",
    },
    .{
        .name = "GLA_Jarmen_Kell",
        .display_name = "Jarmen Kell",
        .unit_type = .GLA_Jarmen_Kell,
        .cost = 1500,
        .build_time = 20.0,
        .health = 100,
        .armor = 0,
        .speed = 4.5,
        .vision_range = 350.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Sniper_Rifle"},
        .upgrades = &[_][]const u8{},
        .size = 1.0,
        .experience_value = 50,
        .description = "Hero sniper. Kills vehicle drivers, allowing capture. Long range.",
    },
    .{
        .name = "GLA_Technical",
        .display_name = "Technical",
        .unit_type = .GLA_Technical,
        .cost = 500,
        .build_time = 8.0,
        .health = 180,
        .armor = 1,
        .speed = 8.5,
        .vision_range = 150.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Machine_Gun"},
        .upgrades = &[_][]const u8{"AP_Bullets", "Salvage_Upgrade"},
        .size = 2.0,
        .experience_value = 8,
        .description = "Fast attack vehicle with machine gun. Can transport 5 infantry.",
    },
    .{
        .name = "GLA_Marauder",
        .display_name = "Marauder Tank",
        .unit_type = .GLA_Marauder,
        .cost = 800,
        .build_time = 11.0,
        .health = 380,
        .armor = 10,
        .speed = 6.5,
        .vision_range = 170.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Tank_Cannon"},
        .upgrades = &[_][]const u8{"Salvage_Upgrade"},
        .size = 3.0,
        .experience_value = 20,
        .description = "Main battle tank. Upgraded version of Scorpion with better armor.",
    },
    .{
        .name = "GLA_Quad_Cannon",
        .display_name = "Quad Cannon",
        .unit_type = .GLA_Quad_Cannon,
        .cost = 700,
        .build_time = 9.0,
        .health = 220,
        .armor = 3,
        .speed = 7.5,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Quad_Machine_Gun"},
        .upgrades = &[_][]const u8{"AP_Bullets", "Salvage_Upgrade"},
        .size = 2.3,
        .experience_value = 15,
        .description = "Anti-aircraft vehicle. Four-barreled machine gun effective vs infantry and aircraft.",
    },
    .{
        .name = "GLA_Toxin_Tractor",
        .display_name = "Toxin Tractor",
        .unit_type = .GLA_Toxin_Tractor,
        .cost = 900,
        .build_time = 12.0,
        .health = 250,
        .armor = 5,
        .speed = 5.0,
        .vision_range = 140.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Anthrax_Spray"},
        .upgrades = &[_][]const u8{"Anthrax_Beta", "Salvage_Upgrade"},
        .size = 2.8,
        .experience_value = 20,
        .description = "Chemical weapons vehicle. Sprays toxic clouds. Deadly to infantry.",
    },
    .{
        .name = "GLA_Rocket_Buggy",
        .display_name = "Rocket Buggy",
        .unit_type = .GLA_Rocket_Buggy,
        .cost = 900,
        .build_time = 11.0,
        .health = 200,
        .armor = 2,
        .speed = 8.0,
        .vision_range = 210.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Artillery_Rocket"},
        .upgrades = &[_][]const u8{"Salvage_Upgrade"},
        .size = 2.5,
        .experience_value = 18,
        .description = "Mobile artillery. Long range rockets. Must deploy to fire.",
    },
    .{
        .name = "GLA_SCUD_Launcher",
        .display_name = "SCUD Launcher",
        .unit_type = .GLA_SCUD_Launcher,
        .cost = 1200,
        .build_time = 15.0,
        .health = 280,
        .armor = 4,
        .speed = 5.5,
        .vision_range = 230.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"SCUD_Missile"},
        .upgrades = &[_][]const u8{"Anthrax_Beta", "Salvage_Upgrade"},
        .size = 3.2,
        .experience_value = 30,
        .description = "Ballistic missile launcher. Can be loaded with explosives, anthrax, or toxins.",
    },
    .{
        .name = "GLA_Battle_Bus",
        .display_name = "Battle Bus",
        .unit_type = .GLA_Battle_Bus,
        .cost = 800,
        .build_time = 10.0,
        .health = 400,
        .armor = 8,
        .speed = 6.0,
        .vision_range = 160.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Salvage_Upgrade"},
        .size = 3.0,
        .experience_value = 15,
        .description = "Armored transport. Holds 8 infantry with firing ports. Can be suicide detonated.",
    },
    .{
        .name = "GLA_Bomb_Truck",
        .display_name = "Bomb Truck",
        .unit_type = .GLA_Bomb_Truck,
        .cost = 1200,
        .build_time = 15.0,
        .health = 300,
        .armor = 2,
        .speed = 6.5,
        .vision_range = 150.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Vehicle_Bomb"},
        .upgrades = &[_][]const u8{"Anthrax_Gamma"},
        .size = 2.8,
        .experience_value = 25,
        .description = "Suicide vehicle loaded with explosives. Can disguise as enemy vehicles.",
    },
    .{
        .name = "GLA_Worker",
        .display_name = "Worker",
        .unit_type = .GLA_Worker,
        .cost = 200,
        .build_time = 8.0,
        .health = 100,
        .armor = 0,
        .speed = 5.0,
        .vision_range = 120.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 1.5,
        .experience_value = 0,
        .description = "Builds structures. Gathers supplies. Can repair buildings while inside.",
    },
};

// Additional data structures that add to executable size
pub const UNIT_EXPERIENCE_LEVELS = [_]u32{ 0, 100, 300, 600, 1000, 1500, 2100, 2800, 3600 };

pub const VETERANCY_BONUSES = struct {
    health_bonus: [9]f32 = .{ 0.0, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5 },
    damage_bonus: [9]f32 = .{ 0.0, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5 },
    armor_bonus: [9]u32 = .{ 0, 1, 2, 3, 4, 5, 6, 7, 10 },
};

pub fn getUnitDef(unit_type: UnitType) *const UnitDef {
    for (&UNIT_DATABASE) |*def| {
        if (def.unit_type == unit_type) return def;
    }
    return &UNIT_DATABASE[0];
}

pub fn getUnitCost(unit_type: UnitType) u32 {
    return getUnitDef(unit_type).cost;
}

pub fn getUnitBuildTime(unit_type: UnitType) f32 {
    return getUnitDef(unit_type).build_time;
}
