// C&C Generals - Unit Definitions Database
// Based on original EA source code

const std = @import("std");

pub const UnitType = enum {
    // USA Units
    USA_Ranger,
    USA_Missile_Defender,
    USA_Pathfinder,
    USA_Colonel_Burton,
    USA_Humvee,
    USA_Tomahawk,
    USA_Crusader_Tank,
    USA_Paladin_Tank,
    USA_Avenger,
    USA_Ambulance,
    USA_Dozer,
    USA_Supply_Truck,
    USA_Chinook,
    USA_Comanche,
    USA_Raptor,
    USA_Stealth_Fighter,
    USA_Aurora_Alpha,

    // China Units
    China_Red_Guard,
    China_Tank_Hunter,
    China_Black_Lotus,
    China_Battlemast,
    China_Overlord,
    China_Gattling_Tank,
    China_Troop_Crawler,
    China_Dragon_Tank,
    China_Inferno_Cannon,
    China_Nuke_Cannon,
    China_ECM_Tank,
    China_Dozer,
    China_Supply_Truck,
    China_Helix,
    China_MiG,

    // GLA Units
    GLA_Rebel,
    GLA_RPG_Trooper,
    GLA_Terrorist,
    GLA_Saboteur,
    GLA_Jarmen_Kell,
    GLA_Technical,
    GLA_Scorpion,
    GLA_Marauder,
    GLA_Quad_Cannon,
    GLA_Toxin_Tractor,
    GLA_Rocket_Buggy,
    GLA_SCUD_Launcher,
    GLA_Battle_Bus,
    GLA_Bomb_Truck,
    GLA_Worker,

    // Add more units...
};

pub const UnitDef = struct {
    name: []const u8,
    display_name: []const u8,
    unit_type: UnitType,
    cost: u32,
    build_time: f32,
    health: u32,
    armor: u32,
    speed: f32,
    vision_range: f32,
    can_attack_ground: bool,
    can_attack_air: bool,
    weapons: []const []const u8,
    upgrades: []const []const u8,
    size: f32,
    experience_value: u32,
    description: []const u8,
};

// Full unit database - this adds significant size to the executable
pub const UNIT_DATABASE = [_]UnitDef{
    .{
        .name = "USA_Ranger",
        .display_name = "Ranger",
        .unit_type = .USA_Ranger,
        .cost = 225,
        .build_time = 5.0,
        .health = 50,
        .armor = 0,
        .speed = 5.0,
        .vision_range = 150.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"M16_Rifle"},
        .upgrades = &[_][]const u8{"Advanced_Training", "Capture_Building"},
        .size = 1.0,
        .experience_value = 5,
        .description = "Basic American infantry unit armed with an M16 assault rifle. Can capture buildings when upgraded.",
    },
    .{
        .name = "USA_Missile_Defender",
        .display_name = "Missile Defender",
        .unit_type = .USA_Missile_Defender,
        .cost = 300,
        .build_time = 6.0,
        .health = 50,
        .armor = 0,
        .speed = 4.5,
        .vision_range = 180.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Stinger_Missile"},
        .upgrades = &[_][]const u8{"Advanced_Training", "Laser_Lock"},
        .size = 1.0,
        .experience_value = 8,
        .description = "Anti-aircraft infantry equipped with Stinger missiles. Effective against aircraft and light vehicles.",
    },
    .{
        .name = "USA_Pathfinder",
        .display_name = "Pathfinder",
        .unit_type = .USA_Pathfinder,
        .cost = 600,
        .build_time = 8.0,
        .health = 45,
        .armor = 0,
        .speed = 4.0,
        .vision_range = 300.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Sniper_Rifle"},
        .upgrades = &[_][]const u8{"Advanced_Training"},
        .size = 1.0,
        .experience_value = 15,
        .description = "Elite sniper with stealth detection and long range. Can instantly kill infantry.",
    },
    .{
        .name = "USA_Colonel_Burton",
        .display_name = "Colonel Burton",
        .unit_type = .USA_Colonel_Burton,
        .cost = 1500,
        .build_time = 20.0,
        .health = 100,
        .armor = 5,
        .speed = 5.5,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Assault_Rifle", "C4_Explosive"},
        .upgrades = &[_][]const u8{},
        .size = 1.0,
        .experience_value = 50,
        .description = "Hero unit. Commando with demolition capabilities and stealth detection.",
    },
    .{
        .name = "USA_Humvee",
        .display_name = "Humvee",
        .unit_type = .USA_Humvee,
        .cost = 700,
        .build_time = 10.0,
        .health = 220,
        .armor = 2,
        .speed = 8.0,
        .vision_range = 150.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"M249_SAW"},
        .upgrades = &[_][]const u8{"TOW_Missile", "Battle_Drone"},
        .size = 2.0,
        .experience_value = 10,
        .description = "Fast scout and transport vehicle. Can be upgraded with TOW missiles or battle drone.",
    },
    .{
        .name = "USA_Crusader_Tank",
        .display_name = "Crusader Tank",
        .unit_type = .USA_Crusader_Tank,
        .cost = 900,
        .build_time = 12.0,
        .health = 400,
        .armor = 10,
        .speed = 6.0,
        .vision_range = 180.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"120mm_Cannon"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone"},
        .size = 3.0,
        .experience_value = 20,
        .description = "Main battle tank with high speed and firepower. Core of USA armor force.",
    },
    .{
        .name = "USA_Paladin_Tank",
        .display_name = "Paladin Tank",
        .unit_type = .USA_Paladin_Tank,
        .cost = 1100,
        .build_time = 14.0,
        .health = 500,
        .armor = 15,
        .speed = 5.0,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"155mm_Cannon", "Point_Defense_Laser"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone"},
        .size = 3.5,
        .experience_value = 30,
        .description = "Heavy tank with point defense laser that shoots down incoming missiles.",
    },
    .{
        .name = "China_Red_Guard",
        .display_name = "Red Guard",
        .unit_type = .China_Red_Guard,
        .cost = 200,
        .build_time = 4.5,
        .health = 60,
        .armor = 0,
        .speed = 4.8,
        .vision_range = 140.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"AK-47"},
        .upgrades = &[_][]const u8{"Nationalism", "Capture_Building"},
        .size = 1.0,
        .experience_value = 5,
        .description = "Chinese basic infantry armed with AK-47. Cheap and numerous.",
    },
    .{
        .name = "China_Battlemast",
        .display_name = "Battlemaster",
        .unit_type = .China_Battlemast,
        .cost = 800,
        .build_time = 11.0,
        .health = 420,
        .armor = 12,
        .speed = 5.5,
        .vision_range = 170.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"125mm_Cannon"},
        .upgrades = &[_][]const u8{"Chain_Guns", "Nationalism", "Nuclear_Shells"},
        .size = 3.2,
        .experience_value = 20,
        .description = "Chinese main battle tank. Can be upgraded with nuclear shells for extra damage.",
    },
    .{
        .name = "China_Overlord",
        .display_name = "Overlord Tank",
        .unit_type = .China_Overlord,
        .cost = 2000,
        .build_time = 25.0,
        .health = 850,
        .armor = 25,
        .speed = 3.5,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Twin_125mm_Cannons"},
        .upgrades = &[_][]const u8{"Chain_Guns", "Nationalism", "Gattling_Cannon", "Propaganda_Tower", "Nuclear_Shells"},
        .size = 5.0,
        .experience_value = 50,
        .description = "Massive super-heavy tank. Can crush other vehicles and be upgraded with various weapons.",
    },
    .{
        .name = "GLA_Rebel",
        .display_name = "Rebel",
        .unit_type = .GLA_Rebel,
        .cost = 150,
        .build_time = 3.0,
        .health = 45,
        .armor = 0,
        .speed = 5.2,
        .vision_range = 130.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"AK-47"},
        .upgrades = &[_][]const u8{"AP_Bullets", "Capture_Building"},
        .size = 1.0,
        .experience_value = 4,
        .description = "GLA basic infantry. Cheap and fast, but weak.",
    },
    .{
        .name = "GLA_Scorpion",
        .display_name = "Scorpion Tank",
        .unit_type = .GLA_Scorpion,
        .cost = 600,
        .build_time = 9.0,
        .health = 300,
        .armor = 8,
        .speed = 7.0,
        .vision_range = 160.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Scorpion_Rocket"},
        .upgrades = &[_][]const u8{"Scorpion_Rocket_Upgrade"},
        .size = 2.5,
        .experience_value = 15,
        .description = "Fast attack tank. Can hide by digging into the ground (stealth).",
    },
    .{
        .name = "USA_Tomahawk",
        .display_name = "Tomahawk Launcher",
        .unit_type = .USA_Tomahawk,
        .cost = 1200,
        .build_time = 15.0,
        .health = 180,
        .armor = 3,
        .speed = 5.5,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Tomahawk_Missile"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Battle_Drone"},
        .size = 2.5,
        .experience_value = 25,
        .description = "Long-range missile launcher. Devastating against buildings and slow units.",
    },
    .{
        .name = "USA_Avenger",
        .display_name = "Avenger",
        .unit_type = .USA_Avenger,
        .cost = 800,
        .build_time = 10.0,
        .health = 200,
        .armor = 2,
        .speed = 7.0,
        .vision_range = 250.0,
        .can_attack_ground = false,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Stinger_Missile"},
        .upgrades = &[_][]const u8{"Composite_Armor", "Laser_Lock", "Battle_Drone"},
        .size = 2.0,
        .experience_value = 15,
        .description = "Mobile anti-aircraft platform. Uses advanced Stinger missiles.",
    },
    .{
        .name = "USA_Ambulance",
        .display_name = "Ambulance",
        .unit_type = .USA_Ambulance,
        .cost = 600,
        .build_time = 8.0,
        .health = 250,
        .armor = 1,
        .speed = 7.5,
        .vision_range = 150.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Composite_Armor"},
        .size = 2.0,
        .experience_value = 5,
        .description = "Medical vehicle. Heals nearby infantry and can pick up wounded soldiers.",
    },
    .{
        .name = "USA_Dozer",
        .display_name = "Construction Dozer",
        .unit_type = .USA_Dozer,
        .cost = 1000,
        .build_time = 20.0,
        .health = 300,
        .armor = 0,
        .speed = 4.0,
        .vision_range = 150.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 3.0,
        .experience_value = 0,
        .description = "Constructs buildings. Essential for base expansion.",
    },
    .{
        .name = "USA_Supply_Truck",
        .display_name = "Supply Truck",
        .unit_type = .USA_Supply_Truck,
        .cost = 600,
        .build_time = 10.0,
        .health = 150,
        .armor = 0,
        .speed = 6.5,
        .vision_range = 120.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 2.5,
        .experience_value = 0,
        .description = "Collects supplies and brings them to Supply Center. Primary economy unit.",
    },
    .{
        .name = "USA_Chinook",
        .display_name = "Chinook Transport",
        .unit_type = .USA_Chinook,
        .cost = 1200,
        .build_time = 15.0,
        .health = 400,
        .armor = 2,
        .speed = 9.0,
        .vision_range = 200.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Countermeasures"},
        .size = 4.0,
        .experience_value = 10,
        .description = "Heavy transport helicopter. Can carry infantry and vehicles. Collects supplies.",
    },
    .{
        .name = "USA_Comanche",
        .display_name = "Comanche",
        .unit_type = .USA_Comanche,
        .cost = 1500,
        .build_time = 18.0,
        .health = 320,
        .armor = 5,
        .speed = 10.0,
        .vision_range = 250.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Hellfire_Missile", "Vulcan_Cannon"},
        .upgrades = &[_][]const u8{"Countermeasures", "Laser_Missiles"},
        .size = 3.5,
        .experience_value = 30,
        .description = "Attack helicopter with stealth technology. Versatile anti-armor platform.",
    },
    .{
        .name = "USA_Raptor",
        .display_name = "F-22 Raptor",
        .unit_type = .USA_Raptor,
        .cost = 1400,
        .build_time = 16.0,
        .health = 280,
        .armor = 3,
        .speed = 15.0,
        .vision_range = 300.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Sidewinder_Missile"},
        .upgrades = &[_][]const u8{"Countermeasures", "Laser_Missiles"},
        .size = 3.0,
        .experience_value = 25,
        .description = "Air superiority fighter. Fast and deadly against air and ground targets.",
    },
    .{
        .name = "USA_Stealth_Fighter",
        .display_name = "Stealth Fighter",
        .unit_type = .USA_Stealth_Fighter,
        .cost = 1600,
        .build_time = 20.0,
        .health = 260,
        .armor = 2,
        .speed = 12.0,
        .vision_range = 250.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"JDAM_Bomb"},
        .upgrades = &[_][]const u8{"Countermeasures"},
        .size = 3.5,
        .experience_value = 35,
        .description = "Stealth bomber. Invisible to enemy radar. Devastating against structures.",
    },
    .{
        .name = "USA_Aurora_Alpha",
        .display_name = "Aurora Alpha",
        .unit_type = .USA_Aurora_Alpha,
        .cost = 2500,
        .build_time = 25.0,
        .health = 300,
        .armor = 4,
        .speed = 20.0,
        .vision_range = 350.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Fuel_Air_Bomb"},
        .upgrades = &[_][]const u8{},
        .size = 4.0,
        .experience_value = 50,
        .description = "Hypersonic bomber. Extremely fast, drops devastating fuel-air bombs.",
    },
    .{
        .name = "China_Tank_Hunter",
        .display_name = "Tank Hunter",
        .unit_type = .China_Tank_Hunter,
        .cost = 300,
        .build_time = 6.0,
        .health = 50,
        .armor = 0,
        .speed = 4.8,
        .vision_range = 160.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Dragon_Anti_Tank_Missile"},
        .upgrades = &[_][]const u8{"Nationalism"},
        .size = 1.0,
        .experience_value = 10,
        .description = "Anti-tank infantry. Effective against vehicles, weak against infantry.",
    },
    .{
        .name = "China_Black_Lotus",
        .display_name = "Black Lotus",
        .unit_type = .China_Black_Lotus,
        .cost = 1500,
        .build_time = 20.0,
        .health = 100,
        .armor = 0,
        .speed = 5.5,
        .vision_range = 200.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 1.0,
        .experience_value = 50,
        .description = "Hero unit. Stealth infiltrator. Can hack buildings and vehicles to steal cash.",
    },
    .{
        .name = "China_Gattling_Tank",
        .display_name = "Gattling Tank",
        .unit_type = .China_Gattling_Tank,
        .cost = 800,
        .build_time = 11.0,
        .health = 350,
        .armor = 8,
        .speed = 6.0,
        .vision_range = 180.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Gattling_Gun"},
        .upgrades = &[_][]const u8{"Chain_Guns", "Nationalism"},
        .size = 2.8,
        .experience_value = 18,
        .description = "Anti-infantry and anti-air tank. Fire rate increases over time when attacking.",
    },
    .{
        .name = "China_Troop_Crawler",
        .display_name = "Troop Crawler",
        .unit_type = .China_Troop_Crawler,
        .cost = 1400,
        .build_time = 16.0,
        .health = 500,
        .armor = 12,
        .speed = 5.0,
        .vision_range = 170.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Napalm_Cannon"},
        .upgrades = &[_][]const u8{"Nationalism"},
        .size = 3.5,
        .experience_value = 25,
        .description = "Armored transport. Can carry infantry and has bunker slots for fire ports.",
    },
    .{
        .name = "China_Dragon_Tank",
        .display_name = "Dragon Tank",
        .unit_type = .China_Dragon_Tank,
        .cost = 800,
        .build_time = 11.0,
        .health = 330,
        .armor = 6,
        .speed = 5.5,
        .vision_range = 150.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Flamethrower"},
        .upgrades = &[_][]const u8{"Black_Napalm", "Nationalism"},
        .size = 2.7,
        .experience_value = 18,
        .description = "Flame tank. Excellent against infantry and buildings. Leaves fire trails.",
    },
    .{
        .name = "China_Inferno_Cannon",
        .display_name = "Inferno Cannon",
        .unit_type = .China_Inferno_Cannon,
        .cost = 900,
        .build_time = 12.0,
        .health = 280,
        .armor = 4,
        .speed = 4.5,
        .vision_range = 220.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Inferno_Shell"},
        .upgrades = &[_][]const u8{"Black_Napalm", "Nationalism"},
        .size = 3.0,
        .experience_value = 22,
        .description = "Artillery. Fires napalm shells over long distances. Effective vs structures.",
    },
    .{
        .name = "China_Nuke_Cannon",
        .display_name = "Nuke Cannon",
        .unit_type = .China_Nuke_Cannon,
        .cost = 1600,
        .build_time = 20.0,
        .health = 300,
        .armor = 5,
        .speed = 4.0,
        .vision_range = 250.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Tactical_Nuke"},
        .upgrades = &[_][]const u8{"Nationalism"},
        .size = 3.5,
        .experience_value = 40,
        .description = "Nuclear artillery. Fires tactical nukes. Leaves radiation. Devastating.",
    },
    .{
        .name = "China_ECM_Tank",
        .display_name = "ECM Tank",
        .unit_type = .China_ECM_Tank,
        .cost = 800,
        .build_time = 10.0,
        .health = 350,
        .armor = 7,
        .speed = 6.0,
        .vision_range = 200.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Nationalism"},
        .size = 2.5,
        .experience_value = 12,
        .description = "Electronic countermeasures. Jams enemy radar and missiles in area.",
    },
    .{
        .name = "China_Dozer",
        .display_name = "Dozer",
        .unit_type = .China_Dozer,
        .cost = 1000,
        .build_time = 20.0,
        .health = 320,
        .armor = 0,
        .speed = 4.0,
        .vision_range = 150.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 3.0,
        .experience_value = 0,
        .description = "Chinese construction vehicle. Builds structures.",
    },
    .{
        .name = "China_Supply_Truck",
        .display_name = "Supply Truck",
        .unit_type = .China_Supply_Truck,
        .cost = 600,
        .build_time = 10.0,
        .health = 170,
        .armor = 0,
        .speed = 6.0,
        .vision_range = 120.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 2.5,
        .experience_value = 0,
        .description = "Gathers supplies from Supply Center. Core economy unit.",
    },
    .{
        .name = "China_Helix",
        .display_name = "Helix",
        .unit_type = .China_Helix,
        .cost = 1500,
        .build_time = 18.0,
        .health = 500,
        .armor = 8,
        .speed = 8.0,
        .vision_range = 220.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Napalm_Bomb"},
        .upgrades = &[_][]const u8{"Gattling_Cannon", "Bunker", "Propaganda_Tower", "Nationalism"},
        .size = 4.5,
        .experience_value = 30,
        .description = "Heavy assault helicopter. Can be upgraded with weapons or troop bunker.",
    },
    .{
        .name = "China_MiG",
        .display_name = "MiG",
        .unit_type = .China_MiG,
        .cost = 1200,
        .build_time = 14.0,
        .health = 260,
        .armor = 3,
        .speed = 14.0,
        .vision_range = 280.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"AA_Missile", "Napalm_Bomb"},
        .upgrades = &[_][]const u8{"Black_Napalm", "Nationalism"},
        .size = 3.0,
        .experience_value = 25,
        .description = "Multi-role fighter. Can engage air and ground targets.",
    },
    .{
        .name = "GLA_RPG_Trooper",
        .display_name = "RPG Trooper",
        .unit_type = .GLA_RPG_Trooper,
        .cost = 225,
        .build_time = 4.5,
        .health = 50,
        .armor = 0,
        .speed = 4.5,
        .vision_range = 150.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"RPG"},
        .upgrades = &[_][]const u8{"AP_Rockets"},
        .size = 1.0,
        .experience_value = 8,
        .description = "Anti-vehicle infantry. RPG effective against vehicles and aircraft.",
    },
    .{
        .name = "GLA_Terrorist",
        .display_name = "Terrorist",
        .unit_type = .GLA_Terrorist,
        .cost = 200,
        .build_time = 3.5,
        .health = 50,
        .armor = 0,
        .speed = 5.5,
        .vision_range = 140.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Explosive_Vest"},
        .upgrades = &[_][]const u8{"Anthrax_Gamma"},
        .size = 1.0,
        .experience_value = 10,
        .description = "Suicide bomber. Runs at enemies and explodes. Can enter buildings.",
    },
    .{
        .name = "GLA_Saboteur",
        .display_name = "Saboteur",
        .unit_type = .GLA_Saboteur,
        .cost = 800,
        .build_time = 10.0,
        .health = 80,
        .armor = 0,
        .speed = 5.8,
        .vision_range = 180.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 1.0,
        .experience_value = 20,
        .description = "Stealth unit. Can plant explosives on buildings and vehicles.",
    },
    .{
        .name = "GLA_Jarmen_Kell",
        .display_name = "Jarmen Kell",
        .unit_type = .GLA_Jarmen_Kell,
        .cost = 1500,
        .build_time = 20.0,
        .health = 100,
        .armor = 0,
        .speed = 4.5,
        .vision_range = 350.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Sniper_Rifle"},
        .upgrades = &[_][]const u8{},
        .size = 1.0,
        .experience_value = 50,
        .description = "Hero sniper. Kills vehicle drivers, allowing capture. Long range.",
    },
    .{
        .name = "GLA_Technical",
        .display_name = "Technical",
        .unit_type = .GLA_Technical,
        .cost = 500,
        .build_time = 8.0,
        .health = 180,
        .armor = 1,
        .speed = 8.5,
        .vision_range = 150.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Machine_Gun"},
        .upgrades = &[_][]const u8{"AP_Bullets", "Salvage_Upgrade"},
        .size = 2.0,
        .experience_value = 8,
        .description = "Fast attack vehicle with machine gun. Can transport 5 infantry.",
    },
    .{
        .name = "GLA_Marauder",
        .display_name = "Marauder Tank",
        .unit_type = .GLA_Marauder,
        .cost = 800,
        .build_time = 11.0,
        .health = 380,
        .armor = 10,
        .speed = 6.5,
        .vision_range = 170.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Tank_Cannon"},
        .upgrades = &[_][]const u8{"Salvage_Upgrade"},
        .size = 3.0,
        .experience_value = 20,
        .description = "Main battle tank. Upgraded version of Scorpion with better armor.",
    },
    .{
        .name = "GLA_Quad_Cannon",
        .display_name = "Quad Cannon",
        .unit_type = .GLA_Quad_Cannon,
        .cost = 700,
        .build_time = 9.0,
        .health = 220,
        .armor = 3,
        .speed = 7.5,
        .vision_range = 200.0,
        .can_attack_ground = true,
        .can_attack_air = true,
        .weapons = &[_][]const u8{"Quad_Machine_Gun"},
        .upgrades = &[_][]const u8{"AP_Bullets", "Salvage_Upgrade"},
        .size = 2.3,
        .experience_value = 15,
        .description = "Anti-aircraft vehicle. Four-barreled machine gun effective vs infantry and aircraft.",
    },
    .{
        .name = "GLA_Toxin_Tractor",
        .display_name = "Toxin Tractor",
        .unit_type = .GLA_Toxin_Tractor,
        .cost = 900,
        .build_time = 12.0,
        .health = 250,
        .armor = 5,
        .speed = 5.0,
        .vision_range = 140.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Anthrax_Spray"},
        .upgrades = &[_][]const u8{"Anthrax_Beta", "Salvage_Upgrade"},
        .size = 2.8,
        .experience_value = 20,
        .description = "Chemical weapons vehicle. Sprays toxic clouds. Deadly to infantry.",
    },
    .{
        .name = "GLA_Rocket_Buggy",
        .display_name = "Rocket Buggy",
        .unit_type = .GLA_Rocket_Buggy,
        .cost = 900,
        .build_time = 11.0,
        .health = 200,
        .armor = 2,
        .speed = 8.0,
        .vision_range = 210.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Artillery_Rocket"},
        .upgrades = &[_][]const u8{"Salvage_Upgrade"},
        .size = 2.5,
        .experience_value = 18,
        .description = "Mobile artillery. Long range rockets. Must deploy to fire.",
    },
    .{
        .name = "GLA_SCUD_Launcher",
        .display_name = "SCUD Launcher",
        .unit_type = .GLA_SCUD_Launcher,
        .cost = 1200,
        .build_time = 15.0,
        .health = 280,
        .armor = 4,
        .speed = 5.5,
        .vision_range = 230.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"SCUD_Missile"},
        .upgrades = &[_][]const u8{"Anthrax_Beta", "Salvage_Upgrade"},
        .size = 3.2,
        .experience_value = 30,
        .description = "Ballistic missile launcher. Can be loaded with explosives, anthrax, or toxins.",
    },
    .{
        .name = "GLA_Battle_Bus",
        .display_name = "Battle Bus",
        .unit_type = .GLA_Battle_Bus,
        .cost = 800,
        .build_time = 10.0,
        .health = 400,
        .armor = 8,
        .speed = 6.0,
        .vision_range = 160.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{"Salvage_Upgrade"},
        .size = 3.0,
        .experience_value = 15,
        .description = "Armored transport. Holds 8 infantry with firing ports. Can be suicide detonated.",
    },
    .{
        .name = "GLA_Bomb_Truck",
        .display_name = "Bomb Truck",
        .unit_type = .GLA_Bomb_Truck,
        .cost = 1200,
        .build_time = 15.0,
        .health = 300,
        .armor = 2,
        .speed = 6.5,
        .vision_range = 150.0,
        .can_attack_ground = true,
        .can_attack_air = false,
        .weapons = &[_][]const u8{"Vehicle_Bomb"},
        .upgrades = &[_][]const u8{"Anthrax_Gamma"},
        .size = 2.8,
        .experience_value = 25,
        .description = "Suicide vehicle loaded with explosives. Can disguise as enemy vehicles.",
    },
    .{
        .name = "GLA_Worker",
        .display_name = "Worker",
        .unit_type = .GLA_Worker,
        .cost = 200,
        .build_time = 8.0,
        .health = 100,
        .armor = 0,
        .speed = 5.0,
        .vision_range = 120.0,
        .can_attack_ground = false,
        .can_attack_air = false,
        .weapons = &[_][]const u8{},
        .upgrades = &[_][]const u8{},
        .size = 1.5,
        .experience_value = 0,
        .description = "Builds structures. Gathers supplies. Can repair buildings while inside.",
    },
};

// Additional data structures that add to executable size
pub const UNIT_EXPERIENCE_LEVELS = [_]u32{ 0, 100, 300, 600, 1000, 1500, 2100, 2800, 3600 };

pub const VETERANCY_BONUSES = struct {
    health_bonus: [9]f32 = .{ 0.0, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5 },
    damage_bonus: [9]f32 = .{ 0.0, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5 },
    armor_bonus: [9]u32 = .{ 0, 1, 2, 3, 4, 5, 6, 7, 10 },
};

pub fn getUnitDef(unit_type: UnitType) *const UnitDef {
    for (&UNIT_DATABASE) |*def| {
        if (def.unit_type == unit_type) return def;
    }
    return &UNIT_DATABASE[0];
}

pub fn getUnitCost(unit_type: UnitType) u32 {
    return getUnitDef(unit_type).cost;
}

pub fn getUnitBuildTime(unit_type: UnitType) f32 {
    return getUnitDef(unit_type).build_time;
}
