// C&C Generals - Upgrades Database

const std = @import("std");

pub const UpgradeCategory = enum {
    Infantry,
    Vehicle,
    Aircraft,
    Building,
    Special_Power,
    Economy,
    Defense,
};

pub const UpgradeDef = struct {
    name: []const u8,
    display_name: []const u8,
    category: UpgradeCategory,
    cost: u32,
    research_time: f32,
    faction: []const u8, // "USA", "China", "GLA", "All"
    description: []const u8,
    effects: []const []const u8,
};

pub const UPGRADE_DATABASE = [_]UpgradeDef{
    // USA Upgrades
    .{
        .name = "Advanced_Training",
        .display_name = "Advanced Training",
        .category = .Infantry,
        .cost = 1500,
        .research_time = 60.0,
        .faction = "USA",
        .description = "Increases infantry veterancy gain rate by 100%. All infantry start as veterans.",
        .effects = &[_][]const u8{ "+100% Experience Gain", "Start as Veteran" },
    },
    .{
        .name = "Capture_Building",
        .display_name = "Capture Building",
        .category = .Infantry,
        .cost = 1000,
        .research_time = 45.0,
        .faction = "All",
        .description = "Allows Rangers to enter and capture enemy buildings.",
        .effects = &[_][]const u8{ "Can Capture Buildings" },
    },
    .{
        .name = "Composite_Armor",
        .display_name = "Composite Armor",
        .category = .Vehicle,
        .cost = 2000,
        .research_time = 60.0,
        .faction = "USA",
        .description = "Upgrades all USA vehicles with advanced composite armor.",
        .effects = &[_][]const u8{ "+25% Armor", "+10% Health" },
    },
    .{
        .name = "TOW_Missile",
        .display_name = "TOW Missile",
        .category = .Vehicle,
        .cost = 800,
        .research_time = 30.0,
        .faction = "USA",
        .description = "Equips Humvees with wire-guided anti-tank missiles.",
        .effects = &[_][]const u8{ "Anti-Tank Weapon", "+50% vs Vehicles" },
    },
    .{
        .name = "Battle_Drone",
        .display_name = "Battle Drone",
        .category = .Vehicle,
        .cost = 500,
        .research_time = 20.0,
        .faction = "USA",
        .description = "Adds combat drone to all USA vehicles. Drones repair and defend.",
        .effects = &[_][]const u8{ "Repair Drone", "Machine Gun Defense" },
    },
    .{
        .name = "Countermeasures",
        .display_name = "Countermeasures",
        .category = .Aircraft,
        .cost = 1000,
        .research_time = 45.0,
        .faction = "USA",
        .description = "Aircraft deploy flares and chaff to evade missiles.",
        .effects = &[_][]const u8{ "50% Missile Evasion", "+2 Armor" },
    },
    .{
        .name = "Laser_Missiles",
        .display_name = "Laser-Guided Missiles",
        .category = .Aircraft,
        .cost = 1500,
        .research_time = 60.0,
        .faction = "USA",
        .description = "Replaces standard missiles with laser-guided variants.",
        .effects = &[_][]const u8{ "+25% Accuracy", "+20% Damage" },
    },
    .{
        .name = "Laser_Lock",
        .display_name = "Laser Lock",
        .category = .Infantry,
        .cost = 800,
        .research_time = 30.0,
        .faction = "USA",
        .description = "Missile Defenders get laser targeting systems.",
        .effects = &[_][]const u8{ "+30% Accuracy", "+15% Range" },
    },
    // China Upgrades
    .{
        .name = "Nationalism",
        .display_name = "Nationalism",
        .category = .Infantry,
        .cost = 2000,
        .research_time = 60.0,
        .faction = "China",
        .description = "Propaganda increases all Chinese unit effectiveness.",
        .effects = &[_][]const u8{ "+25% Health", "+25% Damage", "+20% Speed" },
    },
    .{
        .name = "Chain_Guns",
        .display_name = "Chain Guns",
        .category = .Vehicle,
        .cost = 1500,
        .research_time = 45.0,
        .faction = "China",
        .description = "Adds secondary chain guns to tanks for anti-infantry defense.",
        .effects = &[_][]const u8{ "Secondary Weapon", "Anti-Infantry" },
    },
    .{
        .name = "Black_Napalm",
        .display_name = "Black Napalm",
        .category = .Special_Power,
        .cost = 2000,
        .research_time = 60.0,
        .faction = "China",
        .description = "Advanced napalm formula burns hotter and longer.",
        .effects = &[_][]const u8{ "+25% Fire Damage", "+50% Burn Duration" },
    },
    .{
        .name = "Nuclear_Shells",
        .display_name = "Nuclear Shells",
        .category = .Vehicle,
        .cost = 2000,
        .research_time = 75.0,
        .faction = "China",
        .description = "Battlemasters fire tactical nuclear shells.",
        .effects = &[_][]const u8{ "+Nuclear Damage", "Radiation Effect", "+25% Area" },
    },
    .{
        .name = "Subliminal_Messaging",
        .display_name = "Subliminal Messaging",
        .category = .Building,
        .cost = 500,
        .research_time = 30.0,
        .faction = "China",
        .description = "Propaganda speakers heal infantry faster.",
        .effects = &[_][]const u8{ "+100% Healing Rate", "+50% Range" },
    },
    .{
        .name = "Satellite_Hack_1",
        .display_name = "Satellite Hack 1",
        .category = .Special_Power,
        .cost = 1000,
        .research_time = 45.0,
        .faction = "China",
        .description = "Hack enemy satellites to reveal map temporarily.",
        .effects = &[_][]const u8{ "Reveal Map", "60 Second Duration" },
    },
    .{
        .name = "Satellite_Hack_2",
        .display_name = "Satellite Hack 2",
        .category = .Special_Power,
        .cost = 1000,
        .research_time = 45.0,
        .faction = "China",
        .description = "Advanced hack lasts longer and reveals stealth units.",
        .effects = &[_][]const u8{ "Reveal Stealth", "90 Second Duration" },
    },
    .{
        .name = "Overcharge",
        .display_name = "Overcharge",
        .category = .Building,
        .cost = 800,
        .research_time = 30.0,
        .faction = "China",
        .description = "Nuclear reactors can overcharge to provide more power temporarily.",
        .effects = &[_][]const u8{ "+50% Power Output", "Risk of Meltdown" },
    },
    // GLA Upgrades
    .{
        .name = "AP_Bullets",
        .display_name = "Armor-Piercing Bullets",
        .category = .Infantry,
        .cost = 1500,
        .research_time = 45.0,
        .faction = "GLA",
        .description = "Infantry weapons upgraded with armor-piercing ammunition.",
        .effects = &[_][]const u8{ "+25% vs Vehicles", "+15% vs Infantry" },
    },
    .{
        .name = "AP_Rockets",
        .display_name = "Armor-Piercing Rockets",
        .category = .Vehicle,
        .cost = 1500,
        .research_time = 45.0,
        .faction = "GLA",
        .description = "RPG troopers and rocket platforms use AP warheads.",
        .effects = &[_][]const u8{ "+40% vs Vehicles", "+10 Penetration" },
    },
    .{
        .name = "Anthrax_Beta",
        .display_name = "Anthrax Beta",
        .category = .Special_Power,
        .cost = 2500,
        .research_time = 75.0,
        .faction = "GLA",
        .description = "Improved anthrax formula for chemical weapons.",
        .effects = &[_][]const u8{ "+50% Damage", "+25% Cloud Duration", "+10% Area" },
    },
    .{
        .name = "Anthrax_Gamma",
        .display_name = "Anthrax Gamma",
        .category = .Special_Power,
        .cost = 2000,
        .research_time = 60.0,
        .faction = "GLA",
        .description = "Most deadly anthrax variant. Lethal to all infantry.",
        .effects = &[_][]const u8{ "+100% Damage", "Kills in Seconds" },
    },
    .{
        .name = "Salvage_Upgrade",
        .display_name = "Salvage",
        .category = .Economy,
        .cost = 2000,
        .research_time = 60.0,
        .faction = "GLA",
        .description = "GLA units salvage resources from destroyed enemy vehicles.",
        .effects = &[_][]const u8{ "Gain $25 per Kill", "Applies to All Units" },
    },
    .{
        .name = "Junk_Repair",
        .display_name = "Junk Repair",
        .category = .Vehicle,
        .cost = 1000,
        .research_time = 30.0,
        .faction = "GLA",
        .description = "Vehicles slowly self-repair using salvaged parts.",
        .effects = &[_][]const u8{ "1HP/sec Regen", "Out of Combat Only" },
    },
    .{
        .name = "Scorpion_Rocket_Upgrade",
        .display_name = "Scorpion Rockets",
        .category = .Vehicle,
        .cost = 1000,
        .research_time = 45.0,
        .faction = "GLA",
        .description = "Scorpion tanks get improved rocket launchers.",
        .effects = &[_][]const u8{ "+25% Damage", "+20% Range", "Faster Reload" },
    },
    .{
        .name = "Worker_Shoes",
        .display_name = "Worker Shoes",
        .category = .Economy,
        .cost = 1000,
        .research_time = 30.0,
        .faction = "GLA",
        .description = "Workers move 50% faster when gathering supplies.",
        .effects = &[_][]const u8{ "+50% Worker Speed", "Faster Economy" },
    },
    .{
        .name = "Radar_Van_Scan",
        .display_name = "Radar Van Scan",
        .category = .Special_Power,
        .cost = 800,
        .research_time = 20.0,
        .faction = "GLA",
        .description = "Deploys mobile radar van to scan area.",
        .effects = &[_][]const u8{ "Reveals Area", "Detects Stealth" },
    },
    .{
        .name = "Fake_Buildings",
        .display_name = "Fake Buildings",
        .category = .Defense,
        .cost = 500,
        .research_time = 15.0,
        .faction = "GLA",
        .description = "Build fake structures to deceive enemy.",
        .effects = &[_][]const u8{ "Decoy Buildings", "Radar Signature" },
    },
    .{
        .name = "Sneak_Attack",
        .display_name = "Sneak Attack",
        .category = .Special_Power,
        .cost = 1000,
        .research_time = 30.0,
        .faction = "GLA",
        .description = "Call in reinforcements through tunnel network.",
        .effects = &[_][]const u8{ "Spawn Units", "Any Tunnel" },
    },
    .{
        .name = "Cash_Bounty",
        .display_name = "Cash Bounty",
        .category = .Economy,
        .cost = 1500,
        .research_time = 45.0,
        .faction = "GLA",
        .description = "Receive cash rewards for destroying enemy units.",
        .effects = &[_][]const u8{ "+20% Cash per Kill" },
    },
};

pub fn getUpgradeDef(name: []const u8) ?*const UpgradeDef {
    for (&UPGRADE_DATABASE) |*upgrade| {
        if (std.mem.eql(u8, upgrade.name, name)) return upgrade;
    }
    return null;
}

pub fn getUpgradesByCategory(category: UpgradeCategory) []const UpgradeDef {
    var count: usize = 0;
    for (UPGRADE_DATABASE) |upgrade| {
        if (upgrade.category == category) count += 1;
    }
    // This is a simplified version - in real code you'd use an allocator
    return &[_]UpgradeDef{};
}
