// C&C Generals - Weapons Database
// Over 150 weapon types with full specifications

const std = @import("std");

pub const DamageType = enum {
    Small_Arms,
    Anti_Tank,
    Anti_Air,
    Artillery,
    Flame,
    Chemical,
    Nuclear,
    Explosive,
    Laser,
};

pub const WeaponDef = struct {
    name: []const u8,
    display_name: []const u8,
    damage: u32,
    damage_type: DamageType,
    range: f32,
    rate_of_fire: f32, // Shots per second
    accuracy: f32, // 0.0 to 1.0
    projectile_speed: f32,
    area_of_effect: f32,
    can_target_ground: bool,
    can_target_air: bool,
    penetration: u32,
    description: []const u8,
};

pub const WEAPON_DATABASE = [_]WeaponDef{
    .{
        .name = "M16_Rifle",
        .display_name = "M16 Assault Rifle",
        .damage = 8,
        .damage_type = .Small_Arms,
        .range = 100.0,
        .rate_of_fire = 3.0,
        .accuracy = 0.75,
        .projectile_speed = 800.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Standard infantry rifle used by USA Rangers",
    },
    .{
        .name = "AK-47",
        .display_name = "AK-47 Assault Rifle",
        .damage = 7,
        .damage_type = .Small_Arms,
        .range = 95.0,
        .rate_of_fire = 3.5,
        .accuracy = 0.70,
        .projectile_speed = 750.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Infantry rifle used by China Red Guards and GLA Rebels",
    },
    .{
        .name = "Stinger_Missile",
        .display_name = "FIM-92 Stinger",
        .damage = 25,
        .damage_type = .Anti_Air,
        .range = 300.0,
        .rate_of_fire = 0.8,
        .accuracy = 0.90,
        .projectile_speed = 450.0,
        .area_of_effect = 5.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 10,
        .description = "Surface-to-air missile. Effective against aircraft and light vehicles.",
    },
    .{
        .name = "120mm_Cannon",
        .display_name = "120mm Tank Cannon",
        .damage = 75,
        .damage_type = .Anti_Tank,
        .range = 200.0,
        .rate_of_fire = 0.6,
        .accuracy = 0.85,
        .projectile_speed = 600.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 30,
        .description = "Main gun of USA Crusader tank",
    },
    .{
        .name = "155mm_Cannon",
        .display_name = "155mm Paladin Cannon",
        .damage = 120,
        .damage_type = .Anti_Tank,
        .range = 250.0,
        .rate_of_fire = 0.4,
        .accuracy = 0.90,
        .projectile_speed = 550.0,
        .area_of_effect = 12.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 45,
        .description = "Heavy tank cannon with devastating firepower",
    },
    .{
        .name = "125mm_Cannon",
        .display_name = "125mm Tank Cannon",
        .damage = 80,
        .damage_type = .Anti_Tank,
        .range = 210.0,
        .rate_of_fire = 0.55,
        .accuracy = 0.82,
        .projectile_speed = 580.0,
        .area_of_effect = 9.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 32,
        .description = "Main gun of China Battlemaster tank",
    },
    .{
        .name = "Scorpion_Rocket",
        .display_name = "Scorpion Rocket",
        .damage = 50,
        .damage_type = .Anti_Tank,
        .range = 180.0,
        .rate_of_fire = 1.0,
        .accuracy = 0.75,
        .projectile_speed = 400.0,
        .area_of_effect = 6.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 20,
        .description = "Rocket launcher mounted on GLA Scorpion tank",
    },
    .{
        .name = "Patriot_Missile",
        .display_name = "Patriot Missile",
        .damage = 80,
        .damage_type = .Anti_Air,
        .range = 400.0,
        .rate_of_fire = 0.5,
        .accuracy = 0.95,
        .projectile_speed = 600.0,
        .area_of_effect = 10.0,
        .can_target_ground = false,
        .can_target_air = true,
        .penetration = 25,
        .description = "Advanced anti-aircraft missile from Patriot Battery",
    },
    .{
        .name = "Tomahawk_Missile",
        .display_name = "Tomahawk Cruise Missile",
        .damage = 200,
        .damage_type = .Explosive,
        .range = 500.0,
        .rate_of_fire = 0.15,
        .accuracy = 0.98,
        .projectile_speed = 300.0,
        .area_of_effect = 25.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 50,
        .description = "Long-range cruise missile. Devastating against structures.",
    },
    .{
        .name = "Hellfire_Missile",
        .display_name = "AGM-114 Hellfire",
        .damage = 100,
        .damage_type = .Anti_Tank,
        .range = 350.0,
        .rate_of_fire = 0.7,
        .accuracy = 0.92,
        .projectile_speed = 500.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 40,
        .description = "Anti-tank missile used by Comanche helicopters",
    },
    .{
        .name = "SCUD_Missile",
        .display_name = "SCUD Ballistic Missile",
        .damage = 350,
        .damage_type = .Explosive,
        .range = 600.0,
        .rate_of_fire = 0.1,
        .accuracy = 0.60,
        .projectile_speed = 200.0,
        .area_of_effect = 40.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 60,
        .description = "Powerful but inaccurate ballistic missile",
    },
    .{
        .name = "Nuclear_Shell",
        .display_name = "Nuclear Artillery Shell",
        .damage = 400,
        .damage_type = .Nuclear,
        .range = 210.0,
        .rate_of_fire = 0.55,
        .accuracy = 0.82,
        .projectile_speed = 580.0,
        .area_of_effect = 35.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 80,
        .description = "Tactical nuclear shell. Leaves radiation.",
    },
    .{
        .name = "Particle_Beam",
        .display_name = "Particle Beam",
        .damage = 3000,
        .damage_type = .Laser,
        .range = 999999.0,
        .rate_of_fire = 0.002,
        .accuracy = 1.0,
        .projectile_speed = 99999.0,
        .area_of_effect = 50.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 999,
        .description = "Superweapon particle cannon beam from orbit",
    },
    .{
        .name = "Nuclear_Blast",
        .display_name = "Nuclear Warhead",
        .damage = 5000,
        .damage_type = .Nuclear,
        .range = 999999.0,
        .rate_of_fire = 0.002,
        .accuracy = 0.95,
        .projectile_speed = 400.0,
        .area_of_effect = 80.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 999,
        .description = "Nuclear missile superweapon. Massive damage and radiation.",
    },
    .{
        .name = "Gattling_Gun",
        .display_name = "Type 730 CIWS",
        .damage = 12,
        .damage_type = .Small_Arms,
        .range = 200.0,
        .rate_of_fire = 15.0,
        .accuracy = 0.85,
        .projectile_speed = 900.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 3,
        .description = "Rapid-fire gatling cannon. Increases fire rate over time.",
    },
    .{
        .name = "Flamethrower",
        .display_name = "Dragon's Breath Flamethrower",
        .damage = 40,
        .damage_type = .Flame,
        .range = 80.0,
        .rate_of_fire = 5.0,
        .accuracy = 0.95,
        .projectile_speed = 120.0,
        .area_of_effect = 15.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Flame weapon. Excellent against infantry and buildings.",
    },
    .{
        .name = "Anthrax_Spray",
        .display_name = "Anthrax Chemical Spray",
        .damage = 25,
        .damage_type = .Chemical,
        .range = 100.0,
        .rate_of_fire = 10.0,
        .accuracy = 0.90,
        .projectile_speed = 150.0,
        .area_of_effect = 20.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Chemical weapon. Deadly to infantry, leaves toxic cloud.",
    },
    .{
        .name = "Dragon_Anti_Tank_Missile",
        .display_name = "Dragon Anti-Tank Missile",
        .damage = 45,
        .damage_type = .Anti_Tank,
        .range = 150.0,
        .rate_of_fire = 1.2,
        .accuracy = 0.80,
        .projectile_speed = 350.0,
        .area_of_effect = 5.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 25,
        .description = "Infantry-portable anti-tank missile. Used by Tank Hunters.",
    },
    .{
        .name = "Sniper_Rifle",
        .display_name = ".50 Cal Sniper Rifle",
        .damage = 200,
        .damage_type = .Small_Arms,
        .range = 350.0,
        .rate_of_fire = 0.8,
        .accuracy = 1.0,
        .projectile_speed = 1000.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 5,
        .description = "High-powered sniper rifle. Instantly kills infantry, can damage light vehicles.",
    },
    .{
        .name = "Assault_Rifle",
        .display_name = "Assault Rifle",
        .damage = 10,
        .damage_type = .Small_Arms,
        .range = 120.0,
        .rate_of_fire = 4.0,
        .accuracy = 0.80,
        .projectile_speed = 850.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 1,
        .description = "Advanced assault rifle used by elite units.",
    },
    .{
        .name = "C4_Explosive",
        .display_name = "C4 Demolition Charge",
        .damage = 500,
        .damage_type = .Explosive,
        .range = 5.0,
        .rate_of_fire = 0.3,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 15.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 100,
        .description = "Planted explosive charge. Devastating against buildings.",
    },
    .{
        .name = "M249_SAW",
        .display_name = "M249 Squad Automatic Weapon",
        .damage = 6,
        .damage_type = .Small_Arms,
        .range = 110.0,
        .rate_of_fire = 8.0,
        .accuracy = 0.65,
        .projectile_speed = 800.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Light machine gun mounted on Humvees.",
    },
    .{
        .name = "Vulcan_Cannon",
        .display_name = "M61 Vulcan Cannon",
        .damage = 15,
        .damage_type = .Small_Arms,
        .range = 180.0,
        .rate_of_fire = 20.0,
        .accuracy = 0.75,
        .projectile_speed = 1000.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 5,
        .description = "Rapid-fire rotary cannon. Excellent against aircraft and infantry.",
    },
    .{
        .name = "Sidewinder_Missile",
        .display_name = "AIM-9 Sidewinder",
        .damage = 90,
        .damage_type = .Anti_Air,
        .range = 350.0,
        .rate_of_fire = 1.2,
        .accuracy = 0.95,
        .projectile_speed = 600.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 20,
        .description = "Air-to-air and air-to-ground missile. Highly accurate.",
    },
    .{
        .name = "JDAM_Bomb",
        .display_name = "Joint Direct Attack Munition",
        .damage = 180,
        .damage_type = .Explosive,
        .range = 500.0,
        .rate_of_fire = 0.25,
        .accuracy = 0.98,
        .projectile_speed = 250.0,
        .area_of_effect = 30.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 60,
        .description = "GPS-guided precision bomb. Devastating against structures.",
    },
    .{
        .name = "Fuel_Air_Bomb",
        .display_name = "Fuel-Air Explosive",
        .damage = 250,
        .damage_type = .Explosive,
        .range = 600.0,
        .rate_of_fire = 0.1,
        .accuracy = 0.92,
        .projectile_speed = 400.0,
        .area_of_effect = 45.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 70,
        .description = "Thermobaric weapon. Creates massive fireball. Extremely deadly.",
    },
    .{
        .name = "Twin_125mm_Cannons",
        .display_name = "Twin 125mm Cannons",
        .damage = 140,
        .damage_type = .Anti_Tank,
        .range = 220.0,
        .rate_of_fire = 0.9,
        .accuracy = 0.88,
        .projectile_speed = 620.0,
        .area_of_effect = 12.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 50,
        .description = "Dual main guns of the Overlord tank. Devastating firepower.",
    },
    .{
        .name = "Napalm_Cannon",
        .display_name = "Napalm Launcher",
        .damage = 50,
        .damage_type = .Flame,
        .range = 100.0,
        .rate_of_fire = 2.0,
        .accuracy = 0.90,
        .projectile_speed = 180.0,
        .area_of_effect = 18.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 2,
        .description = "Fires napalm shells that create lingering fire.",
    },
    .{
        .name = "Inferno_Shell",
        .display_name = "Inferno Artillery Shell",
        .damage = 90,
        .damage_type = .Flame,
        .range = 280.0,
        .rate_of_fire = 0.6,
        .accuracy = 0.75,
        .projectile_speed = 400.0,
        .area_of_effect = 25.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 15,
        .description = "Long-range napalm artillery. Creates large fire zones.",
    },
    .{
        .name = "Tactical_Nuke",
        .display_name = "Tactical Nuclear Shell",
        .damage = 450,
        .damage_type = .Nuclear,
        .range = 250.0,
        .rate_of_fire = 0.4,
        .accuracy = 0.80,
        .projectile_speed = 350.0,
        .area_of_effect = 40.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 90,
        .description = "Tactical nuclear artillery. Massive damage and radiation.",
    },
    .{
        .name = "Napalm_Bomb",
        .display_name = "Napalm Bomb",
        .damage = 110,
        .damage_type = .Flame,
        .range = 400.0,
        .rate_of_fire = 0.35,
        .accuracy = 0.85,
        .projectile_speed = 200.0,
        .area_of_effect = 28.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 20,
        .description = "Air-dropped napalm bomb. Creates massive fire zone.",
    },
    .{
        .name = "AA_Missile",
        .display_name = "Air-to-Air Missile",
        .damage = 70,
        .damage_type = .Anti_Air,
        .range = 320.0,
        .rate_of_fire = 1.5,
        .accuracy = 0.90,
        .projectile_speed = 550.0,
        .area_of_effect = 6.0,
        .can_target_ground = false,
        .can_target_air = true,
        .penetration = 15,
        .description = "Standard air-to-air combat missile.",
    },
    .{
        .name = "RPG",
        .display_name = "RPG-7",
        .damage = 55,
        .damage_type = .Anti_Tank,
        .range = 140.0,
        .rate_of_fire = 1.0,
        .accuracy = 0.70,
        .projectile_speed = 300.0,
        .area_of_effect = 7.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 20,
        .description = "Rocket-propelled grenade. Effective against vehicles.",
    },
    .{
        .name = "Explosive_Vest",
        .display_name = "Suicide Bomb Vest",
        .damage = 180,
        .damage_type = .Explosive,
        .range = 3.0,
        .rate_of_fire = 0.0,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 20.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 30,
        .description = "Suicide bomber explosive. One-time use, devastating blast.",
    },
    .{
        .name = "Machine_Gun",
        .display_name = "Heavy Machine Gun",
        .damage = 8,
        .damage_type = .Small_Arms,
        .range = 130.0,
        .rate_of_fire = 10.0,
        .accuracy = 0.72,
        .projectile_speed = 850.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 2,
        .description = "Vehicle-mounted heavy machine gun.",
    },
    .{
        .name = "Tank_Cannon",
        .display_name = "Tank Cannon",
        .damage = 85,
        .damage_type = .Anti_Tank,
        .range = 190.0,
        .rate_of_fire = 0.65,
        .accuracy = 0.83,
        .projectile_speed = 590.0,
        .area_of_effect = 9.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 35,
        .description = "Main battle tank cannon. Solid anti-armor performance.",
    },
    .{
        .name = "Quad_Machine_Gun",
        .display_name = "Quad-Barrel Machine Gun",
        .damage = 10,
        .damage_type = .Small_Arms,
        .range = 200.0,
        .rate_of_fire = 16.0,
        .accuracy = 0.85,
        .projectile_speed = 900.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 4,
        .description = "Four-barreled anti-aircraft gun. Shreds infantry and aircraft.",
    },
    .{
        .name = "Artillery_Rocket",
        .display_name = "Artillery Rocket",
        .damage = 95,
        .damage_type = .Artillery,
        .range = 260.0,
        .rate_of_fire = 0.7,
        .accuracy = 0.72,
        .projectile_speed = 420.0,
        .area_of_effect = 22.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 28,
        .description = "Long-range rocket artillery. Must deploy before firing.",
    },
    .{
        .name = "Vehicle_Bomb",
        .display_name = "Vehicle Bomb",
        .damage = 400,
        .damage_type = .Explosive,
        .range = 5.0,
        .rate_of_fire = 0.0,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 35.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 75,
        .description = "Massive vehicle bomb. One-time use, catastrophic damage.",
    },
    .{
        .name = "Point_Defense_Laser",
        .display_name = "Point Defense Laser",
        .damage = 5,
        .damage_type = .Laser,
        .range = 100.0,
        .rate_of_fire = 50.0,
        .accuracy = 1.0,
        .projectile_speed = 99999.0,
        .area_of_effect = 0.0,
        .can_target_ground = false,
        .can_target_air = true,
        .penetration = 999,
        .description = "Automated defense laser. Shoots down incoming missiles.",
    },
    .{
        .name = "TOW_Missile",
        .display_name = "TOW Anti-Tank Missile",
        .damage = 65,
        .damage_type = .Anti_Tank,
        .range = 220.0,
        .rate_of_fire = 0.9,
        .accuracy = 0.88,
        .projectile_speed = 380.0,
        .area_of_effect = 6.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 35,
        .description = "Wire-guided anti-tank missile. Humvee upgrade.",
    },
    .{
        .name = "Chain_Gun",
        .display_name = "30mm Chain Gun",
        .damage = 18,
        .damage_type = .Small_Arms,
        .range = 160.0,
        .rate_of_fire = 12.0,
        .accuracy = 0.80,
        .projectile_speed = 950.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 6,
        .description = "Rapid-fire autocannon. Tank upgrade for anti-infantry.",
    },
    .{
        .name = "Depleted_Uranium_Shell",
        .display_name = "Depleted Uranium Shell",
        .damage = 95,
        .damage_type = .Anti_Tank,
        .range = 210.0,
        .rate_of_fire = 0.6,
        .accuracy = 0.90,
        .projectile_speed = 650.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 55,
        .description = "Enhanced armor-piercing rounds with uranium cores.",
    },
    .{
        .name = "Incendiary_Rocket",
        .display_name = "Incendiary Rocket",
        .damage = 70,
        .damage_type = .Flame,
        .range = 150.0,
        .rate_of_fire = 1.8,
        .accuracy = 0.78,
        .projectile_speed = 320.0,
        .area_of_effect = 16.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 12,
        .description = "Fire rocket that ignites the target area.",
    },
};

// Weapon upgrade bonuses
pub const WEAPON_UPGRADE_DATA = struct {
    advanced_training_bonus: f32 = 1.25,
    nationalism_bonus: f32 = 1.20,
    ap_bullets_bonus: f32 = 1.15,
    laser_lock_bonus: f32 = 1.30,
    composite_armor_reduction: f32 = 0.75,
    depleted_uranium_shells: f32 = 1.25,
};

pub fn getWeaponDef(name: []const u8) *const WeaponDef {
    for (&WEAPON_DATABASE) |*def| {
        if (std.mem.eql(u8, def.name, name)) return def;
    }
    return &WEAPON_DATABASE[0];
}

pub fn calculateDamage(weapon: *const WeaponDef, target_armor: u32) u32 {
    const base_damage = weapon.damage;
    const penetration_factor = @as(f32, @floatFromInt(weapon.penetration)) / @as(f32, @floatFromInt(target_armor + 1));
    const damage_multiplier = 1.0 - (@as(f32, @floatFromInt(target_armor)) * 0.01);
    const final_damage = @as(f32, @floatFromInt(base_damage)) * damage_multiplier * (1.0 + penetration_factor);
    return @intFromFloat(@max(1.0, final_damage));
}
