// C&C Generals - Weapons Database
// Over 150 weapon types with full specifications

const std = @import("std");

pub const DamageType = enum {
    Small_Arms,
    Anti_Tank,
    Anti_Air,
    Artillery,
    Flame,
    Chemical,
    Nuclear,
    Explosive,
    Laser,
};

pub const WeaponDef = struct {
    name: []const u8,
    display_name: []const u8,
    damage: u32,
    damage_type: DamageType,
    range: f32,
    rate_of_fire: f32, // Shots per second
    accuracy: f32, // 0.0 to 1.0
    projectile_speed: f32,
    area_of_effect: f32,
    can_target_ground: bool,
    can_target_air: bool,
    penetration: u32,
    description: []const u8,
};

pub const WEAPON_DATABASE = [_]WeaponDef{
    .{
        .name = "M16_Rifle",
        .display_name = "M16 Assault Rifle",
        .damage = 8,
        .damage_type = .Small_Arms,
        .range = 100.0,
        .rate_of_fire = 3.0,
        .accuracy = 0.75,
        .projectile_speed = 800.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Standard infantry rifle used by USA Rangers",
    },
    .{
        .name = "AK-47",
        .display_name = "AK-47 Assault Rifle",
        .damage = 7,
        .damage_type = .Small_Arms,
        .range = 95.0,
        .rate_of_fire = 3.5,
        .accuracy = 0.70,
        .projectile_speed = 750.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Infantry rifle used by China Red Guards and GLA Rebels",
    },
    .{
        .name = "Stinger_Missile",
        .display_name = "FIM-92 Stinger",
        .damage = 25,
        .damage_type = .Anti_Air,
        .range = 300.0,
        .rate_of_fire = 0.8,
        .accuracy = 0.90,
        .projectile_speed = 450.0,
        .area_of_effect = 5.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 10,
        .description = "Surface-to-air missile. Effective against aircraft and light vehicles.",
    },
    .{
        .name = "120mm_Cannon",
        .display_name = "120mm Tank Cannon",
        .damage = 75,
        .damage_type = .Anti_Tank,
        .range = 200.0,
        .rate_of_fire = 0.6,
        .accuracy = 0.85,
        .projectile_speed = 600.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 30,
        .description = "Main gun of USA Crusader tank",
    },
    .{
        .name = "155mm_Cannon",
        .display_name = "155mm Paladin Cannon",
        .damage = 120,
        .damage_type = .Anti_Tank,
        .range = 250.0,
        .rate_of_fire = 0.4,
        .accuracy = 0.90,
        .projectile_speed = 550.0,
        .area_of_effect = 12.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 45,
        .description = "Heavy tank cannon with devastating firepower",
    },
    .{
        .name = "125mm_Cannon",
        .display_name = "125mm Tank Cannon",
        .damage = 80,
        .damage_type = .Anti_Tank,
        .range = 210.0,
        .rate_of_fire = 0.55,
        .accuracy = 0.82,
        .projectile_speed = 580.0,
        .area_of_effect = 9.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 32,
        .description = "Main gun of China Battlemaster tank",
    },
    .{
        .name = "Scorpion_Rocket",
        .display_name = "Scorpion Rocket",
        .damage = 50,
        .damage_type = .Anti_Tank,
        .range = 180.0,
        .rate_of_fire = 1.0,
        .accuracy = 0.75,
        .projectile_speed = 400.0,
        .area_of_effect = 6.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 20,
        .description = "Rocket launcher mounted on GLA Scorpion tank",
    },
    .{
        .name = "Patriot_Missile",
        .display_name = "Patriot Missile",
        .damage = 80,
        .damage_type = .Anti_Air,
        .range = 400.0,
        .rate_of_fire = 0.5,
        .accuracy = 0.95,
        .projectile_speed = 600.0,
        .area_of_effect = 10.0,
        .can_target_ground = false,
        .can_target_air = true,
        .penetration = 25,
        .description = "Advanced anti-aircraft missile from Patriot Battery",
    },
    .{
        .name = "Tomahawk_Missile",
        .display_name = "Tomahawk Cruise Missile",
        .damage = 200,
        .damage_type = .Explosive,
        .range = 500.0,
        .rate_of_fire = 0.15,
        .accuracy = 0.98,
        .projectile_speed = 300.0,
        .area_of_effect = 25.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 50,
        .description = "Long-range cruise missile. Devastating against structures.",
    },
    .{
        .name = "Hellfire_Missile",
        .display_name = "AGM-114 Hellfire",
        .damage = 100,
        .damage_type = .Anti_Tank,
        .range = 350.0,
        .rate_of_fire = 0.7,
        .accuracy = 0.92,
        .projectile_speed = 500.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 40,
        .description = "Anti-tank missile used by Comanche helicopters",
    },
    .{
        .name = "SCUD_Missile",
        .display_name = "SCUD Ballistic Missile",
        .damage = 350,
        .damage_type = .Explosive,
        .range = 600.0,
        .rate_of_fire = 0.1,
        .accuracy = 0.60,
        .projectile_speed = 200.0,
        .area_of_effect = 40.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 60,
        .description = "Powerful but inaccurate ballistic missile",
    },
    .{
        .name = "Nuclear_Shell",
        .display_name = "Nuclear Artillery Shell",
        .damage = 400,
        .damage_type = .Nuclear,
        .range = 210.0,
        .rate_of_fire = 0.55,
        .accuracy = 0.82,
        .projectile_speed = 580.0,
        .area_of_effect = 35.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 80,
        .description = "Tactical nuclear shell. Leaves radiation.",
    },
    .{
        .name = "Particle_Beam",
        .display_name = "Particle Beam",
        .damage = 3000,
        .damage_type = .Laser,
        .range = 999999.0,
        .rate_of_fire = 0.002,
        .accuracy = 1.0,
        .projectile_speed = 99999.0,
        .area_of_effect = 50.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 999,
        .description = "Superweapon particle cannon beam from orbit",
    },
    .{
        .name = "Nuclear_Blast",
        .display_name = "Nuclear Warhead",
        .damage = 5000,
        .damage_type = .Nuclear,
        .range = 999999.0,
        .rate_of_fire = 0.002,
        .accuracy = 0.95,
        .projectile_speed = 400.0,
        .area_of_effect = 80.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 999,
        .description = "Nuclear missile superweapon. Massive damage and radiation.",
    },
    .{
        .name = "Gattling_Gun",
        .display_name = "Type 730 CIWS",
        .damage = 12,
        .damage_type = .Small_Arms,
        .range = 200.0,
        .rate_of_fire = 15.0,
        .accuracy = 0.85,
        .projectile_speed = 900.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 3,
        .description = "Rapid-fire gatling cannon. Increases fire rate over time.",
    },
    .{
        .name = "Flamethrower",
        .display_name = "Dragon's Breath Flamethrower",
        .damage = 40,
        .damage_type = .Flame,
        .range = 80.0,
        .rate_of_fire = 5.0,
        .accuracy = 0.95,
        .projectile_speed = 120.0,
        .area_of_effect = 15.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Flame weapon. Excellent against infantry and buildings.",
    },
    .{
        .name = "Anthrax_Spray",
        .display_name = "Anthrax Chemical Spray",
        .damage = 25,
        .damage_type = .Chemical,
        .range = 100.0,
        .rate_of_fire = 10.0,
        .accuracy = 0.90,
        .projectile_speed = 150.0,
        .area_of_effect = 20.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Chemical weapon. Deadly to infantry, leaves toxic cloud.",
    },
    .{
        .name = "Dragon_Anti_Tank_Missile",
        .display_name = "Dragon Anti-Tank Missile",
        .damage = 45,
        .damage_type = .Anti_Tank,
        .range = 150.0,
        .rate_of_fire = 1.2,
        .accuracy = 0.80,
        .projectile_speed = 350.0,
        .area_of_effect = 5.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 25,
        .description = "Infantry-portable anti-tank missile. Used by Tank Hunters.",
    },
    .{
        .name = "Sniper_Rifle",
        .display_name = ".50 Cal Sniper Rifle",
        .damage = 200,
        .damage_type = .Small_Arms,
        .range = 350.0,
        .rate_of_fire = 0.8,
        .accuracy = 1.0,
        .projectile_speed = 1000.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 5,
        .description = "High-powered sniper rifle. Instantly kills infantry, can damage light vehicles.",
    },
    .{
        .name = "Assault_Rifle",
        .display_name = "Assault Rifle",
        .damage = 10,
        .damage_type = .Small_Arms,
        .range = 120.0,
        .rate_of_fire = 4.0,
        .accuracy = 0.80,
        .projectile_speed = 850.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 1,
        .description = "Advanced assault rifle used by elite units.",
    },
    .{
        .name = "C4_Explosive",
        .display_name = "C4 Demolition Charge",
        .damage = 500,
        .damage_type = .Explosive,
        .range = 5.0,
        .rate_of_fire = 0.3,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 15.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 100,
        .description = "Planted explosive charge. Devastating against buildings.",
    },
    .{
        .name = "M249_SAW",
        .display_name = "M249 Squad Automatic Weapon",
        .damage = 6,
        .damage_type = .Small_Arms,
        .range = 110.0,
        .rate_of_fire = 8.0,
        .accuracy = 0.65,
        .projectile_speed = 800.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Light machine gun mounted on Humvees.",
    },
    .{
        .name = "Vulcan_Cannon",
        .display_name = "M61 Vulcan Cannon",
        .damage = 15,
        .damage_type = .Small_Arms,
        .range = 180.0,
        .rate_of_fire = 20.0,
        .accuracy = 0.75,
        .projectile_speed = 1000.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 5,
        .description = "Rapid-fire rotary cannon. Excellent against aircraft and infantry.",
    },
    .{
        .name = "Sidewinder_Missile",
        .display_name = "AIM-9 Sidewinder",
        .damage = 90,
        .damage_type = .Anti_Air,
        .range = 350.0,
        .rate_of_fire = 1.2,
        .accuracy = 0.95,
        .projectile_speed = 600.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 20,
        .description = "Air-to-air and air-to-ground missile. Highly accurate.",
    },
    .{
        .name = "JDAM_Bomb",
        .display_name = "Joint Direct Attack Munition",
        .damage = 180,
        .damage_type = .Explosive,
        .range = 500.0,
        .rate_of_fire = 0.25,
        .accuracy = 0.98,
        .projectile_speed = 250.0,
        .area_of_effect = 30.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 60,
        .description = "GPS-guided precision bomb. Devastating against structures.",
    },
    .{
        .name = "Fuel_Air_Bomb",
        .display_name = "Fuel-Air Explosive",
        .damage = 250,
        .damage_type = .Explosive,
        .range = 600.0,
        .rate_of_fire = 0.1,
        .accuracy = 0.92,
        .projectile_speed = 400.0,
        .area_of_effect = 45.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 70,
        .description = "Thermobaric weapon. Creates massive fireball. Extremely deadly.",
    },
    .{
        .name = "Twin_125mm_Cannons",
        .display_name = "Twin 125mm Cannons",
        .damage = 140,
        .damage_type = .Anti_Tank,
        .range = 220.0,
        .rate_of_fire = 0.9,
        .accuracy = 0.88,
        .projectile_speed = 620.0,
        .area_of_effect = 12.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 50,
        .description = "Dual main guns of the Overlord tank. Devastating firepower.",
    },
    .{
        .name = "Napalm_Cannon",
        .display_name = "Napalm Launcher",
        .damage = 50,
        .damage_type = .Flame,
        .range = 100.0,
        .rate_of_fire = 2.0,
        .accuracy = 0.90,
        .projectile_speed = 180.0,
        .area_of_effect = 18.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 2,
        .description = "Fires napalm shells that create lingering fire.",
    },
    .{
        .name = "Inferno_Shell",
        .display_name = "Inferno Artillery Shell",
        .damage = 90,
        .damage_type = .Flame,
        .range = 280.0,
        .rate_of_fire = 0.6,
        .accuracy = 0.75,
        .projectile_speed = 400.0,
        .area_of_effect = 25.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 15,
        .description = "Long-range napalm artillery. Creates large fire zones.",
    },
    .{
        .name = "Tactical_Nuke",
        .display_name = "Tactical Nuclear Shell",
        .damage = 450,
        .damage_type = .Nuclear,
        .range = 250.0,
        .rate_of_fire = 0.4,
        .accuracy = 0.80,
        .projectile_speed = 350.0,
        .area_of_effect = 40.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 90,
        .description = "Tactical nuclear artillery. Massive damage and radiation.",
    },
    .{
        .name = "Napalm_Bomb",
        .display_name = "Napalm Bomb",
        .damage = 110,
        .damage_type = .Flame,
        .range = 400.0,
        .rate_of_fire = 0.35,
        .accuracy = 0.85,
        .projectile_speed = 200.0,
        .area_of_effect = 28.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 20,
        .description = "Air-dropped napalm bomb. Creates massive fire zone.",
    },
    .{
        .name = "AA_Missile",
        .display_name = "Air-to-Air Missile",
        .damage = 70,
        .damage_type = .Anti_Air,
        .range = 320.0,
        .rate_of_fire = 1.5,
        .accuracy = 0.90,
        .projectile_speed = 550.0,
        .area_of_effect = 6.0,
        .can_target_ground = false,
        .can_target_air = true,
        .penetration = 15,
        .description = "Standard air-to-air combat missile.",
    },
    .{
        .name = "RPG",
        .display_name = "RPG-7",
        .damage = 55,
        .damage_type = .Anti_Tank,
        .range = 140.0,
        .rate_of_fire = 1.0,
        .accuracy = 0.70,
        .projectile_speed = 300.0,
        .area_of_effect = 7.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 20,
        .description = "Rocket-propelled grenade. Effective against vehicles.",
    },
    .{
        .name = "Explosive_Vest",
        .display_name = "Suicide Bomb Vest",
        .damage = 180,
        .damage_type = .Explosive,
        .range = 3.0,
        .rate_of_fire = 0.0,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 20.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 30,
        .description = "Suicide bomber explosive. One-time use, devastating blast.",
    },
    .{
        .name = "Machine_Gun",
        .display_name = "Heavy Machine Gun",
        .damage = 8,
        .damage_type = .Small_Arms,
        .range = 130.0,
        .rate_of_fire = 10.0,
        .accuracy = 0.72,
        .projectile_speed = 850.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 2,
        .description = "Vehicle-mounted heavy machine gun.",
    },
    .{
        .name = "Tank_Cannon",
        .display_name = "Tank Cannon",
        .damage = 85,
        .damage_type = .Anti_Tank,
        .range = 190.0,
        .rate_of_fire = 0.65,
        .accuracy = 0.83,
        .projectile_speed = 590.0,
        .area_of_effect = 9.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 35,
        .description = "Main battle tank cannon. Solid anti-armor performance.",
    },
    .{
        .name = "Quad_Machine_Gun",
        .display_name = "Quad-Barrel Machine Gun",
        .damage = 10,
        .damage_type = .Small_Arms,
        .range = 200.0,
        .rate_of_fire = 16.0,
        .accuracy = 0.85,
        .projectile_speed = 900.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 4,
        .description = "Four-barreled anti-aircraft gun. Shreds infantry and aircraft.",
    },
    .{
        .name = "Artillery_Rocket",
        .display_name = "Artillery Rocket",
        .damage = 95,
        .damage_type = .Artillery,
        .range = 260.0,
        .rate_of_fire = 0.7,
        .accuracy = 0.72,
        .projectile_speed = 420.0,
        .area_of_effect = 22.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 28,
        .description = "Long-range rocket artillery. Must deploy before firing.",
    },
    .{
        .name = "Vehicle_Bomb",
        .display_name = "Vehicle Bomb",
        .damage = 400,
        .damage_type = .Explosive,
        .range = 5.0,
        .rate_of_fire = 0.0,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 35.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 75,
        .description = "Massive vehicle bomb. One-time use, catastrophic damage.",
    },
    .{
        .name = "Point_Defense_Laser",
        .display_name = "Point Defense Laser",
        .damage = 5,
        .damage_type = .Laser,
        .range = 100.0,
        .rate_of_fire = 50.0,
        .accuracy = 1.0,
        .projectile_speed = 99999.0,
        .area_of_effect = 0.0,
        .can_target_ground = false,
        .can_target_air = true,
        .penetration = 999,
        .description = "Automated defense laser. Shoots down incoming missiles.",
    },
    .{
        .name = "TOW_Missile",
        .display_name = "TOW Anti-Tank Missile",
        .damage = 65,
        .damage_type = .Anti_Tank,
        .range = 220.0,
        .rate_of_fire = 0.9,
        .accuracy = 0.88,
        .projectile_speed = 380.0,
        .area_of_effect = 6.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 35,
        .description = "Wire-guided anti-tank missile. Humvee upgrade.",
    },
    .{
        .name = "Chain_Gun",
        .display_name = "30mm Chain Gun",
        .damage = 18,
        .damage_type = .Small_Arms,
        .range = 160.0,
        .rate_of_fire = 12.0,
        .accuracy = 0.80,
        .projectile_speed = 950.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 6,
        .description = "Rapid-fire autocannon. Tank upgrade for anti-infantry.",
    },
    .{
        .name = "Depleted_Uranium_Shell",
        .display_name = "Depleted Uranium Shell",
        .damage = 95,
        .damage_type = .Anti_Tank,
        .range = 210.0,
        .rate_of_fire = 0.6,
        .accuracy = 0.90,
        .projectile_speed = 650.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 55,
        .description = "Enhanced armor-piercing rounds with uranium cores.",
    },
    .{
        .name = "Incendiary_Rocket",
        .display_name = "Incendiary Rocket",
        .damage = 70,
        .damage_type = .Flame,
        .range = 150.0,
        .rate_of_fire = 1.8,
        .accuracy = 0.78,
        .projectile_speed = 320.0,
        .area_of_effect = 16.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 12,
        .description = "Fire rocket that ignites the target area.",
    },

    // ========================================
    // USA Infantry Weapons
    // ========================================
    .{
        .name = "M249_SAW",
        .display_name = "M249 SAW",
        .damage = 12,
        .damage_type = .Small_Arms,
        .range = 110.0,
        .rate_of_fire = 5.0,
        .accuracy = 0.72,
        .projectile_speed = 850.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Squad automatic weapon used by USA infantry.",
    },
    .{
        .name = "AT4_Rocket",
        .display_name = "AT4 Anti-Tank Rocket",
        .damage = 65,
        .damage_type = .Anti_Tank,
        .range = 150.0,
        .rate_of_fire = 1.0,
        .accuracy = 0.80,
        .projectile_speed = 380.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 25,
        .description = "Missile launcher carried by USA Missile Defenders.",
    },
    .{
        .name = "Flash_Bang_Grenade",
        .display_name = "Flash Bang Grenade",
        .damage = 15,
        .damage_type = .Explosive,
        .range = 80.0,
        .rate_of_fire = 0.5,
        .accuracy = 0.75,
        .projectile_speed = 200.0,
        .area_of_effect = 18.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Stun grenade used by USA Colonel Burton.",
    },
    .{
        .name = "Demolition_Charge",
        .display_name = "C4 Demolition Charge",
        .damage = 200,
        .damage_type = .Explosive,
        .range = 5.0,
        .rate_of_fire = 0.3,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 20.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 50,
        .description = "Placed explosive charge for destroying buildings.",
    },

    // ========================================
    // USA Vehicle Weapons
    // ========================================
    .{
        .name = "TOW_Missile",
        .display_name = "BGM-71 TOW Missile",
        .damage = 85,
        .damage_type = .Anti_Tank,
        .range = 220.0,
        .rate_of_fire = 0.7,
        .accuracy = 0.88,
        .projectile_speed = 420.0,
        .area_of_effect = 6.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 35,
        .description = "Wire-guided anti-tank missile mounted on Humvees.",
    },
    .{
        .name = "Bushmaster_Cannon",
        .display_name = "25mm Bushmaster Cannon",
        .damage = 18,
        .damage_type = .Small_Arms,
        .range = 180.0,
        .rate_of_fire = 8.0,
        .accuracy = 0.82,
        .projectile_speed = 900.0,
        .area_of_effect = 2.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 8,
        .description = "Autocannon used by USA Avenger and Bradley vehicles.",
    },
    .{
        .name = "Hellfire_Missile",
        .display_name = "AGM-114 Hellfire",
        .damage = 95,
        .damage_type = .Anti_Tank,
        .range = 240.0,
        .rate_of_fire = 0.6,
        .accuracy = 0.92,
        .projectile_speed = 480.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 40,
        .description = "Air-to-ground missile fired by USA Comanche helicopters.",
    },
    .{
        .name = "Dual_Patriot_Missile",
        .display_name = "Dual Patriot Missiles",
        .damage = 45,
        .damage_type = .Anti_Air,
        .range = 320.0,
        .rate_of_fire = 1.2,
        .accuracy = 0.94,
        .projectile_speed = 520.0,
        .area_of_effect = 6.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 15,
        .description = "Advanced Patriot system with dual launchers.",
    },

    // ========================================
    // USA Aircraft Weapons
    // ========================================
    .{
        .name = "AMRAAM_Missile",
        .display_name = "AIM-120 AMRAAM",
        .damage = 55,
        .damage_type = .Anti_Air,
        .range = 280.0,
        .rate_of_fire = 1.0,
        .accuracy = 0.90,
        .projectile_speed = 550.0,
        .area_of_effect = 5.0,
        .can_target_ground = false,
        .can_target_air = true,
        .penetration = 12,
        .description = "Air-to-air missile used by USA Raptors.",
    },
    .{
        .name = "JDAM_Bomb",
        .display_name = "JDAM Guided Bomb",
        .damage = 180,
        .damage_type = .Explosive,
        .range = 350.0,
        .rate_of_fire = 0.4,
        .accuracy = 0.95,
        .projectile_speed = 250.0,
        .area_of_effect = 28.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 45,
        .description = "Precision-guided bomb dropped by USA aircraft.",
    },
    .{
        .name = "Fuel_Air_Bomb",
        .display_name = "Fuel Air Explosive",
        .damage = 220,
        .damage_type = .Explosive,
        .range = 400.0,
        .rate_of_fire = 0.3,
        .accuracy = 0.88,
        .projectile_speed = 200.0,
        .area_of_effect = 35.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 30,
        .description = "Massive area-effect bomb used by USA Aurora bombers.",
    },
    .{
        .name = "Vulcan_Cannon",
        .display_name = "20mm Vulcan Cannon",
        .damage = 22,
        .damage_type = .Small_Arms,
        .range = 200.0,
        .rate_of_fire = 12.0,
        .accuracy = 0.75,
        .projectile_speed = 1000.0,
        .area_of_effect = 1.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 5,
        .description = "Gatling gun mounted on USA aircraft.",
    },

    // ========================================
    // USA General-Specific Weapons
    // ========================================
    .{
        .name = "Point_Defense_Laser",
        .display_name = "Point Defense Laser",
        .damage = 30,
        .damage_type = .Laser,
        .range = 260.0,
        .rate_of_fire = 4.0,
        .accuracy = 0.98,
        .projectile_speed = 9999.0,
        .area_of_effect = 0.0,
        .can_target_ground = false,
        .can_target_air = true,
        .penetration = 20,
        .description = "Air Force General's anti-missile laser system.",
    },
    .{
        .name = "EMP_Patriot_Missile",
        .display_name = "EMP Patriot Missile",
        .damage = 25,
        .damage_type = .Anti_Air,
        .range = 300.0,
        .rate_of_fire = 1.0,
        .accuracy = 0.92,
        .projectile_speed = 500.0,
        .area_of_effect = 10.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 10,
        .description = "Superweapon General's EMP-armed Patriot missile.",
    },
    .{
        .name = "Particle_Beam",
        .display_name = "Particle Beam Cannon",
        .damage = 500,
        .damage_type = .Laser,
        .range = 9999.0,
        .rate_of_fire = 0.01,
        .accuracy = 1.0,
        .projectile_speed = 9999.0,
        .area_of_effect = 40.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 100,
        .description = "USA superweapon. Devastating orbital particle beam.",
    },

    // ========================================
    // China Infantry Weapons
    // ========================================
    .{
        .name = "Type_95_Rifle",
        .display_name = "Type 95 Rifle",
        .damage = 9,
        .damage_type = .Small_Arms,
        .range = 105.0,
        .rate_of_fire = 3.2,
        .accuracy = 0.76,
        .projectile_speed = 820.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Advanced rifle used by elite China infantry.",
    },
    .{
        .name = "HJ-8_Missile",
        .display_name = "HJ-8 Anti-Tank Missile",
        .damage = 70,
        .damage_type = .Anti_Tank,
        .range = 160.0,
        .rate_of_fire = 0.9,
        .accuracy = 0.84,
        .projectile_speed = 400.0,
        .area_of_effect = 7.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 28,
        .description = "Wire-guided missile used by China Tank Hunters.",
    },
    .{
        .name = "Minigun",
        .display_name = "Minigun",
        .damage = 15,
        .damage_type = .Small_Arms,
        .range = 120.0,
        .rate_of_fire = 10.0,
        .accuracy = 0.70,
        .projectile_speed = 900.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Gatling gun carried by China Minigunners.",
    },
    .{
        .name = "Dual_Minigun",
        .display_name = "Dual Minigun System",
        .damage = 20,
        .damage_type = .Small_Arms,
        .range = 130.0,
        .rate_of_fire = 15.0,
        .accuracy = 0.68,
        .projectile_speed = 920.0,
        .area_of_effect = 1.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 2,
        .description = "Infantry General's dual minigun platform.",
    },

    // ========================================
    // China Vehicle Weapons
    // ========================================
    .{
        .name = "Battlemaster_Cannon",
        .display_name = "125mm Smoothbore Cannon",
        .damage = 78,
        .damage_type = .Anti_Tank,
        .range = 210.0,
        .rate_of_fire = 0.65,
        .accuracy = 0.86,
        .projectile_speed = 620.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 32,
        .description = "Main gun of China Battlemaster tank.",
    },
    .{
        .name = "Overlord_Cannon",
        .display_name = "Overlord Tank Cannon",
        .damage = 95,
        .damage_type = .Anti_Tank,
        .range = 220.0,
        .rate_of_fire = 0.55,
        .accuracy = 0.88,
        .projectile_speed = 640.0,
        .area_of_effect = 10.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 38,
        .description = "Heavy cannon mounted on China Overlord tanks.",
    },
    .{
        .name = "Autoloader_Cannon",
        .display_name = "Autoloader Artillery Cannon",
        .damage = 85,
        .damage_type = .Artillery,
        .range = 300.0,
        .rate_of_fire = 1.2,
        .accuracy = 0.80,
        .projectile_speed = 450.0,
        .area_of_effect = 18.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 20,
        .description = "Tank General's rapid-fire artillery.",
    },
    .{
        .name = "Gattling_Cannon",
        .display_name = "Gattling Cannon",
        .damage = 18,
        .damage_type = .Small_Arms,
        .range = 160.0,
        .rate_of_fire = 8.0,
        .accuracy = 0.78,
        .projectile_speed = 880.0,
        .area_of_effect = 2.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 6,
        .description = "Spinning barrel gun used by China Gattling tanks.",
    },
    .{
        .name = "Advanced_Gattling_Gun",
        .display_name = "Advanced Gattling Gun",
        .damage = 24,
        .damage_type = .Small_Arms,
        .range = 180.0,
        .rate_of_fire = 10.0,
        .accuracy = 0.82,
        .projectile_speed = 920.0,
        .area_of_effect = 3.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 8,
        .description = "Enhanced Gattling system with faster spin-up.",
    },

    // ========================================
    // China Aircraft & Missiles
    // ========================================
    .{
        .name = "Napalm_Bomb",
        .display_name = "Napalm Bomb",
        .damage = 140,
        .damage_type = .Flame,
        .range = 320.0,
        .rate_of_fire = 0.5,
        .accuracy = 0.82,
        .projectile_speed = 220.0,
        .area_of_effect = 30.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 15,
        .description = "Incendiary bomb that creates lingering fire.",
    },
    .{
        .name = "PL-12_Missile",
        .display_name = "PL-12 Air-to-Air Missile",
        .damage = 52,
        .damage_type = .Anti_Air,
        .range = 270.0,
        .rate_of_fire = 1.1,
        .accuracy = 0.88,
        .projectile_speed = 540.0,
        .area_of_effect = 5.0,
        .can_target_ground = false,
        .can_target_air = true,
        .penetration = 10,
        .description = "China's advanced air-to-air missile.",
    },
    .{
        .name = "Nuclear_Missile",
        .display_name = "Nuclear Ballistic Missile",
        .damage = 800,
        .damage_type = .Nuclear,
        .range = 9999.0,
        .rate_of_fire = 0.01,
        .accuracy = 1.0,
        .projectile_speed = 300.0,
        .area_of_effect = 60.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 100,
        .description = "China superweapon. Massive nuclear explosion.",
    },
    .{
        .name = "Tactical_Nuke",
        .display_name = "Tactical Nuclear Shell",
        .damage = 250,
        .damage_type = .Nuclear,
        .range = 350.0,
        .rate_of_fire = 0.2,
        .accuracy = 0.90,
        .projectile_speed = 380.0,
        .area_of_effect = 35.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 60,
        .description = "Nuke General's tactical nuclear artillery.",
    },
    .{
        .name = "Nuclear_Artillery_Shell",
        .display_name = "Nuclear Artillery Shell",
        .damage = 280,
        .damage_type = .Nuclear,
        .range = 380.0,
        .rate_of_fire = 0.18,
        .accuracy = 0.88,
        .projectile_speed = 400.0,
        .area_of_effect = 38.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 65,
        .description = "Nuke General's nuclear artillery platform.",
    },

    // ========================================
    // China Special Weapons
    // ========================================
    .{
        .name = "Laser_Beam",
        .display_name = "Tactical Laser Beam",
        .damage = 42,
        .damage_type = .Laser,
        .range = 280.0,
        .rate_of_fire = 6.0,
        .accuracy = 0.95,
        .projectile_speed = 9999.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 25,
        .description = "Continuous laser beam weapon.",
    },
    .{
        .name = "Heavy_MG",
        .display_name = "Heavy Machine Gun",
        .damage = 16,
        .damage_type = .Small_Arms,
        .range = 140.0,
        .rate_of_fire = 6.0,
        .accuracy = 0.80,
        .projectile_speed = 880.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 3,
        .description = "Fortified bunker machine gun.",
    },

    // ========================================
    // GLA Infantry Weapons
    // ========================================
    .{
        .name = "RPG_Launcher",
        .display_name = "RPG-7 Launcher",
        .damage = 60,
        .damage_type = .Anti_Tank,
        .range = 140.0,
        .rate_of_fire = 1.0,
        .accuracy = 0.75,
        .projectile_speed = 350.0,
        .area_of_effect = 7.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 22,
        .description = "Rocket-propelled grenade launcher.",
    },
    .{
        .name = "Dragunov_Rifle",
        .display_name = "Dragunov Sniper Rifle",
        .damage = 80,
        .damage_type = .Small_Arms,
        .range = 280.0,
        .rate_of_fire = 0.5,
        .accuracy = 0.95,
        .projectile_speed = 900.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 15,
        .description = "Jarmen Kell's sniper rifle. Kills vehicle drivers.",
    },
    .{
        .name = "Toxin_Sprayer",
        .display_name = "Anthrax Sprayer",
        .damage = 35,
        .damage_type = .Chemical,
        .range = 90.0,
        .rate_of_fire = 3.0,
        .accuracy = 0.85,
        .projectile_speed = 150.0,
        .area_of_effect = 12.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Chemical weapon that sprays deadly toxins.",
    },
    .{
        .name = "Bomb_Vest",
        .display_name = "Suicide Bomb Vest",
        .damage = 180,
        .damage_type = .Explosive,
        .range = 5.0,
        .rate_of_fire = 0.0,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 22.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 40,
        .description = "Explosive vest worn by GLA Terrorists.",
    },

    // ========================================
    // GLA Vehicle Weapons
    // ========================================
    .{
        .name = "Twin_50cal",
        .display_name = "Twin .50 Cal Machine Guns",
        .damage = 14,
        .damage_type = .Small_Arms,
        .range = 150.0,
        .rate_of_fire = 7.0,
        .accuracy = 0.74,
        .projectile_speed = 860.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 2,
        .description = "Dual machine guns mounted on GLA technicals.",
    },
    .{
        .name = "Scorpion_Rocket",
        .display_name = "Scorpion Rocket",
        .damage = 68,
        .damage_type = .Anti_Tank,
        .range = 180.0,
        .rate_of_fire = 0.8,
        .accuracy = 0.80,
        .projectile_speed = 380.0,
        .area_of_effect = 6.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 24,
        .description = "Rocket fired by GLA Scorpion tanks.",
    },
    .{
        .name = "Rocket_Buggy_Launcher",
        .display_name = "Rocket Buggy Launcher",
        .damage = 55,
        .damage_type = .Artillery,
        .range = 260.0,
        .rate_of_fire = 1.5,
        .accuracy = 0.72,
        .projectile_speed = 340.0,
        .area_of_effect = 15.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 12,
        .description = "Multiple rocket launcher on GLA buggies.",
    },
    .{
        .name = "SCUD_Missile",
        .display_name = "SCUD Ballistic Missile",
        .damage = 350,
        .damage_type = .Explosive,
        .range = 400.0,
        .rate_of_fire = 0.15,
        .accuracy = 0.75,
        .projectile_speed = 280.0,
        .area_of_effect = 32.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 50,
        .description = "Long-range ballistic missile.",
    },
    .{
        .name = "Anthrax_SCUD",
        .display_name = "Anthrax SCUD Missile",
        .damage = 280,
        .damage_type = .Chemical,
        .range = 420.0,
        .rate_of_fire = 0.15,
        .accuracy = 0.75,
        .projectile_speed = 280.0,
        .area_of_effect = 38.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 30,
        .description = "SCUD missile with anthrax warhead.",
    },

    // ========================================
    // GLA Special Weapons
    // ========================================
    .{
        .name = "Bomb_Truck_Explosive",
        .display_name = "Truck Bomb",
        .damage = 400,
        .damage_type = .Explosive,
        .range = 5.0,
        .rate_of_fire = 0.0,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 35.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 80,
        .description = "Massive bomb carried by GLA bomb trucks.",
    },
    .{
        .name = "Bio_Bomb",
        .display_name = "Biological Bomb",
        .damage = 320,
        .damage_type = .Chemical,
        .range = 450.0,
        .rate_of_fire = 0.08,
        .accuracy = 0.85,
        .projectile_speed = 250.0,
        .area_of_effect = 45.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 20,
        .description = "Toxin General's anthrax bomb superweapon.",
    },
    .{
        .name = "SCUD_Storm",
        .display_name = "SCUD Storm Barrage",
        .damage = 300,
        .damage_type = .Explosive,
        .range = 9999.0,
        .rate_of_fire = 0.01,
        .accuracy = 0.80,
        .projectile_speed = 280.0,
        .area_of_effect = 40.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 55,
        .description = "GLA superweapon. Launches 9 SCUDs in grid pattern.",
    },
    .{
        .name = "Demo_Trap_Explosive",
        .display_name = "Demo Trap",
        .damage = 160,
        .damage_type = .Explosive,
        .range = 5.0,
        .rate_of_fire = 0.0,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 20.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 35,
        .description = "Hidden explosive trap.",
    },

    // ========================================
    // Additional Specialized Weapons
    // ========================================
    .{
        .name = "Cluster_Missile",
        .display_name = "Cluster Missile",
        .damage = 45,
        .damage_type = .Explosive,
        .range = 280.0,
        .rate_of_fire = 0.9,
        .accuracy = 0.82,
        .projectile_speed = 420.0,
        .area_of_effect = 25.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 18,
        .description = "Missile that splits into multiple submunitions.",
    },
    .{
        .name = "EMP_Bomb",
        .display_name = "EMP Bomb",
        .damage = 50,
        .damage_type = .Explosive,
        .range = 350.0,
        .rate_of_fire = 0.3,
        .accuracy = 0.90,
        .projectile_speed = 240.0,
        .area_of_effect = 32.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 10,
        .description = "Electromagnetic pulse weapon that disables vehicles.",
    },
    .{
        .name = "Bunker_Buster",
        .display_name = "Bunker Buster Bomb",
        .damage = 320,
        .damage_type = .Explosive,
        .range = 380.0,
        .rate_of_fire = 0.2,
        .accuracy = 0.92,
        .projectile_speed = 220.0,
        .area_of_effect = 18.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 90,
        .description = "Penetrating bomb designed to destroy fortifications.",
    },
    .{
        .name = "Incendiary_Bomb",
        .display_name = "Incendiary Bomb",
        .damage = 160,
        .damage_type = .Flame,
        .range = 340.0,
        .rate_of_fire = 0.4,
        .accuracy = 0.84,
        .projectile_speed = 230.0,
        .area_of_effect = 28.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 20,
        .description = "Fire bomb that creates persistent flames.",
    },
    .{
        .name = "Frag_Grenade",
        .display_name = "Fragmentation Grenade",
        .damage = 35,
        .damage_type = .Explosive,
        .range = 75.0,
        .rate_of_fire = 0.6,
        .accuracy = 0.78,
        .projectile_speed = 180.0,
        .area_of_effect = 14.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 8,
        .description = "Standard fragmentation grenade.",
    },
    .{
        .name = "Molotov_Cocktail",
        .display_name = "Molotov Cocktail",
        .damage = 25,
        .damage_type = .Flame,
        .range = 60.0,
        .rate_of_fire = 0.8,
        .accuracy = 0.72,
        .projectile_speed = 150.0,
        .area_of_effect = 10.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 2,
        .description = "Improvised fire bomb used by GLA mobs.",
    },
    .{
        .name = "Depleted_Uranium_Shell",
        .display_name = "DU Tank Shell",
        .damage = 105,
        .damage_type = .Anti_Tank,
        .range = 230.0,
        .rate_of_fire = 0.55,
        .accuracy = 0.90,
        .projectile_speed = 680.0,
        .area_of_effect = 6.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 50,
        .description = "Armor-piercing depleted uranium shell.",
    },
    .{
        .name = "Composite_Armor_Shell",
        .display_name = "APFSDS Round",
        .damage = 98,
        .damage_type = .Anti_Tank,
        .range = 240.0,
        .rate_of_fire = 0.58,
        .accuracy = 0.88,
        .projectile_speed = 720.0,
        .area_of_effect = 4.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 48,
        .description = "Armor-piercing fin-stabilized discarding sabot round.",
    },
    .{
        .name = "Phosphorus_Shell",
        .display_name = "White Phosphorus Shell",
        .damage = 85,
        .damage_type = .Flame,
        .range = 270.0,
        .rate_of_fire = 0.7,
        .accuracy = 0.80,
        .projectile_speed = 420.0,
        .area_of_effect = 22.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 15,
        .description = "Incendiary artillery shell.",
    },
    .{
        .name = "Thermobaric_Warhead",
        .display_name = "Thermobaric Warhead",
        .damage = 240,
        .damage_type = .Explosive,
        .range = 360.0,
        .rate_of_fire = 0.25,
        .accuracy = 0.86,
        .projectile_speed = 320.0,
        .area_of_effect = 35.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 42,
        .description = "Fuel-air explosive warhead.",
    },
    .{
        .name = "Shrapnel_Shell",
        .display_name = "Shrapnel Artillery Shell",
        .damage = 65,
        .damage_type = .Artillery,
        .range = 290.0,
        .rate_of_fire = 0.8,
        .accuracy = 0.76,
        .projectile_speed = 390.0,
        .area_of_effect = 26.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 12,
        .description = "Fragmentation shell effective against infantry.",
    },
    .{
        .name = "Smoke_Grenade",
        .display_name = "Smoke Grenade",
        .damage = 0,
        .damage_type = .Explosive,
        .range = 70.0,
        .rate_of_fire = 0.4,
        .accuracy = 0.85,
        .projectile_speed = 160.0,
        .area_of_effect = 20.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Smoke grenade for concealment.",
    },
    .{
        .name = "Tandem_Warhead",
        .display_name = "Tandem HEAT Warhead",
        .damage = 115,
        .damage_type = .Anti_Tank,
        .range = 200.0,
        .rate_of_fire = 0.5,
        .accuracy = 0.87,
        .projectile_speed = 410.0,
        .area_of_effect = 5.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 55,
        .description = "Dual-stage shaped charge warhead.",
    },
    .{
        .name = "Proximity_Mine",
        .display_name = "Proximity Mine",
        .damage = 140,
        .damage_type = .Explosive,
        .range = 3.0,
        .rate_of_fire = 0.0,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 18.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 32,
        .description = "Motion-triggered mine.",
    },
    .{
        .name = "Napalm_Strike",
        .display_name = "Napalm Airstrike",
        .damage = 190,
        .damage_type = .Flame,
        .range = 400.0,
        .rate_of_fire = 0.2,
        .accuracy = 0.88,
        .projectile_speed = 260.0,
        .area_of_effect = 40.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 18,
        .description = "Devastating napalm bombing run.",
    },
    .{
        .name = "Carpet_Bomb",
        .display_name = "Carpet Bombing",
        .damage = 150,
        .damage_type = .Explosive,
        .range = 450.0,
        .rate_of_fire = 0.15,
        .accuracy = 0.82,
        .projectile_speed = 240.0,
        .area_of_effect = 50.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 35,
        .description = "Multiple bombs dropped in a line.",
    },
    .{
        .name = "Daisy_Cutter",
        .display_name = "BLU-82 Daisy Cutter",
        .damage = 380,
        .damage_type = .Explosive,
        .range = 420.0,
        .rate_of_fire = 0.1,
        .accuracy = 0.90,
        .projectile_speed = 210.0,
        .area_of_effect = 55.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 45,
        .description = "Massive blast bomb.",
    },
    .{
        .name = "Laser_Guided_Missile",
        .display_name = "Laser-Guided Missile",
        .damage = 125,
        .damage_type = .Anti_Tank,
        .range = 320.0,
        .rate_of_fire = 0.45,
        .accuracy = 0.96,
        .projectile_speed = 520.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 45,
        .description = "Precision laser-guided missile.",
    },
    .{
        .name = "Anti_Ship_Missile",
        .display_name = "Anti-Ship Missile",
        .damage = 180,
        .damage_type = .Anti_Tank,
        .range = 380.0,
        .rate_of_fire = 0.3,
        .accuracy = 0.92,
        .projectile_speed = 480.0,
        .area_of_effect = 12.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 52,
        .description = "Heavy anti-ship cruise missile.",
    },
    .{
        .name = "Cruise_Missile",
        .display_name = "Tomahawk Cruise Missile",
        .damage = 280,
        .damage_type = .Explosive,
        .range = 500.0,
        .rate_of_fire = 0.12,
        .accuracy = 0.94,
        .projectile_speed = 350.0,
        .area_of_effect = 35.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 48,
        .description = "Long-range precision cruise missile.",
    },
    .{
        .name = "Tactical_Missile",
        .display_name = "Tactical Ballistic Missile",
        .damage = 260,
        .damage_type = .Explosive,
        .range = 450.0,
        .rate_of_fire = 0.18,
        .accuracy = 0.88,
        .projectile_speed = 300.0,
        .area_of_effect = 32.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 44,
        .description = "Medium-range tactical missile.",
    },
    .{
        .name = "Mortar_Shell",
        .display_name = "Mortar Shell",
        .damage = 55,
        .damage_type = .Artillery,
        .range = 220.0,
        .rate_of_fire = 1.2,
        .accuracy = 0.74,
        .projectile_speed = 280.0,
        .area_of_effect = 16.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 10,
        .description = "Indirect fire mortar shell.",
    },
    .{
        .name = "Howitzer_Shell",
        .display_name = "155mm Howitzer Shell",
        .damage = 135,
        .damage_type = .Artillery,
        .range = 310.0,
        .rate_of_fire = 0.5,
        .accuracy = 0.82,
        .projectile_speed = 420.0,
        .area_of_effect = 24.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 28,
        .description = "Heavy artillery shell.",
    },
    .{
        .name = "MLRS_Rocket",
        .display_name = "MLRS Rocket",
        .damage = 72,
        .damage_type = .Artillery,
        .range = 340.0,
        .rate_of_fire = 2.0,
        .accuracy = 0.70,
        .projectile_speed = 360.0,
        .area_of_effect = 20.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 16,
        .description = "Multiple launch rocket system.",
    },
    .{
        .name = "Katyusha_Rocket",
        .display_name = "Katyusha Rocket",
        .damage = 68,
        .damage_type = .Artillery,
        .range = 320.0,
        .rate_of_fire = 2.2,
        .accuracy = 0.68,
        .projectile_speed = 340.0,
        .area_of_effect = 18.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 14,
        .description = "Soviet-era rocket artillery.",
    },
    .{
        .name = "Satchel_Charge",
        .display_name = "Satchel Charge",
        .damage = 220,
        .damage_type = .Explosive,
        .range = 8.0,
        .rate_of_fire = 0.2,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 22.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 55,
        .description = "Timed explosive charge.",
    },
    .{
        .name = "Time_Bomb",
        .display_name = "Time Bomb",
        .damage = 280,
        .damage_type = .Explosive,
        .range = 5.0,
        .rate_of_fire = 0.1,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 28.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 65,
        .description = "Large time-delayed bomb.",
    },
    .{
        .name = "Remote_Detonator",
        .display_name = "Remote Explosive",
        .damage = 195,
        .damage_type = .Explosive,
        .range = 6.0,
        .rate_of_fire = 0.0,
        .accuracy = 1.0,
        .projectile_speed = 0.0,
        .area_of_effect = 24.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 48,
        .description = "Remotely triggered explosive.",
    },
    .{
        .name = "Napalm_Launcher",
        .display_name = "Napalm Launcher",
        .damage = 92,
        .damage_type = .Flame,
        .range = 160.0,
        .rate_of_fire = 1.0,
        .accuracy = 0.78,
        .projectile_speed = 280.0,
        .area_of_effect = 20.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 12,
        .description = "Vehicle-mounted napalm projector.",
    },
    .{
        .name = "Flak_Cannon",
        .display_name = "88mm Flak Cannon",
        .damage = 38,
        .damage_type = .Anti_Air,
        .range = 280.0,
        .rate_of_fire = 2.5,
        .accuracy = 0.82,
        .projectile_speed = 680.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 14,
        .description = "Anti-aircraft flak cannon.",
    },
    .{
        .name = "SAM_Launcher",
        .display_name = "Surface-to-Air Missile",
        .damage = 48,
        .damage_type = .Anti_Air,
        .range = 310.0,
        .rate_of_fire = 0.9,
        .accuracy = 0.91,
        .projectile_speed = 510.0,
        .area_of_effect = 6.0,
        .can_target_ground = false,
        .can_target_air = true,
        .penetration = 12,
        .description = "Dedicated anti-aircraft missile system.",
    },
    .{
        .name = "AA_Vulcan",
        .display_name = "Anti-Aircraft Vulcan",
        .damage = 26,
        .damage_type = .Anti_Air,
        .range = 220.0,
        .rate_of_fire = 10.0,
        .accuracy = 0.78,
        .projectile_speed = 980.0,
        .area_of_effect = 2.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 6,
        .description = "Rapid-fire anti-aircraft cannon.",
    },
    .{
        .name = "Quad_Cannon",
        .display_name = "Quad Machine Gun",
        .damage = 32,
        .damage_type = .Anti_Air,
        .range = 200.0,
        .rate_of_fire = 8.0,
        .accuracy = 0.76,
        .projectile_speed = 920.0,
        .area_of_effect = 3.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 8,
        .description = "Four-barrel anti-aircraft system.",
    },
    .{
        .name = "Chaingun",
        .display_name = "30mm Chaingun",
        .damage = 28,
        .damage_type = .Small_Arms,
        .range = 190.0,
        .rate_of_fire = 9.0,
        .accuracy = 0.80,
        .projectile_speed = 940.0,
        .area_of_effect = 2.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 10,
        .description = "Rapid-fire autocannon.",
    },
    .{
        .name = "Auto_Cannon",
        .display_name = "40mm Auto Cannon",
        .damage = 35,
        .damage_type = .Small_Arms,
        .range = 210.0,
        .rate_of_fire = 6.0,
        .accuracy = 0.84,
        .projectile_speed = 960.0,
        .area_of_effect = 3.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 12,
        .description = "Medium autocannon.",
    },
    .{
        .name = "Recoilless_Rifle",
        .display_name = "106mm Recoilless Rifle",
        .damage = 88,
        .damage_type = .Anti_Tank,
        .range = 190.0,
        .rate_of_fire = 0.6,
        .accuracy = 0.83,
        .projectile_speed = 420.0,
        .area_of_effect = 7.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 36,
        .description = "Portable anti-tank gun.",
    },
    .{
        .name = "Wire_Guided_Missile",
        .display_name = "Wire-Guided AT Missile",
        .damage = 92,
        .damage_type = .Anti_Tank,
        .range = 250.0,
        .rate_of_fire = 0.5,
        .accuracy = 0.90,
        .projectile_speed = 400.0,
        .area_of_effect = 6.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 42,
        .description = "Wire-guided precision anti-tank missile.",
    },
    .{
        .name = "Beam_Cannon",
        .display_name = "Particle Beam Cannon",
        .damage = 65,
        .damage_type = .Laser,
        .range = 300.0,
        .rate_of_fire = 3.0,
        .accuracy = 0.96,
        .projectile_speed = 9999.0,
        .area_of_effect = 0.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 32,
        .description = "Advanced energy weapon.",
    },
    .{
        .name = "Tesla_Coil",
        .display_name = "Tesla Weapon",
        .damage = 75,
        .damage_type = .Laser,
        .range = 200.0,
        .rate_of_fire = 2.0,
        .accuracy = 0.92,
        .projectile_speed = 9999.0,
        .area_of_effect = 5.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 28,
        .description = "Electrical discharge weapon.",
    },
    .{
        .name = "Microwave_Beam",
        .display_name = "Microwave Emitter",
        .damage = 42,
        .damage_type = .Laser,
        .range = 180.0,
        .rate_of_fire = 5.0,
        .accuracy = 0.88,
        .projectile_speed = 9999.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 15,
        .description = "Microwave crowd control weapon.",
    },
    .{
        .name = "Radiation_Beam",
        .display_name = "Radiation Projector",
        .damage = 58,
        .damage_type = .Nuclear,
        .range = 160.0,
        .rate_of_fire = 3.0,
        .accuracy = 0.85,
        .projectile_speed = 500.0,
        .area_of_effect = 12.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 20,
        .description = "Radioactive particle weapon.",
    },
    .{
        .name = "Dirty_Bomb",
        .display_name = "Dirty Bomb",
        .damage = 185,
        .damage_type = .Nuclear,
        .range = 380.0,
        .rate_of_fire = 0.2,
        .accuracy = 0.82,
        .projectile_speed = 260.0,
        .area_of_effect = 30.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 35,
        .description = "Radiological dispersal device.",
    },
    .{
        .name = "Neutron_Shell",
        .display_name = "Neutron Artillery Shell",
        .damage = 125,
        .damage_type = .Nuclear,
        .range = 330.0,
        .rate_of_fire = 0.4,
        .accuracy = 0.86,
        .projectile_speed = 410.0,
        .area_of_effect = 26.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 38,
        .description = "Enhanced radiation warhead.",
    },
    .{
        .name = "Storm_Cannon",
        .display_name = "Storm Cannon",
        .damage = 112,
        .damage_type = .Anti_Tank,
        .range = 250.0,
        .rate_of_fire = 0.48,
        .accuracy = 0.89,
        .projectile_speed = 650.0,
        .area_of_effect = 9.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 43,
        .description = "Powerful tank destroyer cannon.",
    },
    .{
        .name = "Plasma_Cannon",
        .display_name = "Plasma Cannon",
        .damage = 88,
        .damage_type = .Laser,
        .range = 240.0,
        .rate_of_fire = 1.5,
        .accuracy = 0.91,
        .projectile_speed = 1200.0,
        .area_of_effect = 6.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 35,
        .description = "Superheated plasma weapon.",
    },
    .{
        .name = "Ion_Cannon",
        .display_name = "Ion Cannon",
        .damage = 450,
        .damage_type = .Laser,
        .range = 9999.0,
        .rate_of_fire = 0.01,
        .accuracy = 1.0,
        .projectile_speed = 9999.0,
        .area_of_effect = 38.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 95,
        .description = "Orbital ion cannon strike.",
    },
    .{
        .name = "Cluster_Bomb",
        .display_name = "Cluster Bomb",
        .damage = 95,
        .damage_type = .Explosive,
        .range = 380.0,
        .rate_of_fire = 0.35,
        .accuracy = 0.80,
        .projectile_speed = 220.0,
        .area_of_effect = 42.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 22,
        .description = "Bomb that disperses multiple bomblets.",
    },
    .{
        .name = "Piercing_Shell",
        .display_name = "Armor Piercing Shell",
        .damage = 102,
        .damage_type = .Anti_Tank,
        .range = 225.0,
        .rate_of_fire = 0.52,
        .accuracy = 0.91,
        .projectile_speed = 710.0,
        .area_of_effect = 5.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 52,
        .description = "Tungsten armor-piercing shell.",
    },
    .{
        .name = "HEAT_Round",
        .display_name = "HEAT Round",
        .damage = 94,
        .damage_type = .Anti_Tank,
        .range = 215.0,
        .rate_of_fire = 0.62,
        .accuracy = 0.86,
        .projectile_speed = 590.0,
        .area_of_effect = 7.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 46,
        .description = "High-explosive anti-tank round.",
    },
    .{
        .name = "Sabot_Round",
        .display_name = "Sabot Round",
        .damage = 108,
        .damage_type = .Anti_Tank,
        .range = 235.0,
        .rate_of_fire = 0.54,
        .accuracy = 0.92,
        .projectile_speed = 750.0,
        .area_of_effect = 3.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 54,
        .description = "Kinetic penetrator round.",
    },
    .{
        .name = "Incendiary_Missile",
        .display_name = "Incendiary Missile",
        .damage = 78,
        .damage_type = .Flame,
        .range = 260.0,
        .rate_of_fire = 0.75,
        .accuracy = 0.84,
        .projectile_speed = 420.0,
        .area_of_effect = 18.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 16,
        .description = "Missile with incendiary warhead.",
    },
    .{
        .name = "Flechette_Round",
        .display_name = "Flechette Round",
        .damage = 42,
        .damage_type = .Small_Arms,
        .range = 120.0,
        .rate_of_fire = 4.0,
        .accuracy = 0.68,
        .projectile_speed = 820.0,
        .area_of_effect = 15.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 4,
        .description = "Shotgun-like anti-personnel round.",
    },
    .{
        .name = "Concussion_Grenade",
        .display_name = "Concussion Grenade",
        .damage = 48,
        .damage_type = .Explosive,
        .range = 70.0,
        .rate_of_fire = 0.55,
        .accuracy = 0.80,
        .projectile_speed = 170.0,
        .area_of_effect = 16.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 12,
        .description = "High-blast grenade.",
    },
    .{
        .name = "Sticky_Bomb",
        .display_name = "Sticky Bomb",
        .damage = 165,
        .damage_type = .Explosive,
        .range = 10.0,
        .rate_of_fire = 0.4,
        .accuracy = 0.88,
        .projectile_speed = 0.0,
        .area_of_effect = 16.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 42,
        .description = "Adhesive magnetic explosive.",
    },
    .{
        .name = "Plasma_Mortar",
        .display_name = "Plasma Mortar",
        .damage = 96,
        .damage_type = .Laser,
        .range = 280.0,
        .rate_of_fire = 0.8,
        .accuracy = 0.78,
        .projectile_speed = 320.0,
        .area_of_effect = 20.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 28,
        .description = "Indirect-fire plasma weapon.",
    },
    .{
        .name = "Rail_Gun",
        .display_name = "Electromagnetic Rail Gun",
        .damage = 135,
        .damage_type = .Anti_Tank,
        .range = 320.0,
        .rate_of_fire = 0.35,
        .accuracy = 0.94,
        .projectile_speed = 2000.0,
        .area_of_effect = 4.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 68,
        .description = "Hypersonic electromagnetic projectile weapon.",
    },
    .{
        .name = "Coil_Gun",
        .display_name = "Gauss Cannon",
        .damage = 118,
        .damage_type = .Anti_Tank,
        .range = 290.0,
        .rate_of_fire = 0.42,
        .accuracy = 0.90,
        .projectile_speed = 1800.0,
        .area_of_effect = 5.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 58,
        .description = "Magnetic acceleration weapon.",
    },
    .{
        .name = "Sonic_Boom",
        .display_name = "Sonic Weapon",
        .damage = 62,
        .damage_type = .Explosive,
        .range = 180.0,
        .rate_of_fire = 2.0,
        .accuracy = 0.82,
        .projectile_speed = 340.0,
        .area_of_effect = 22.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 8,
        .description = "Sonic shockwave weapon.",
    },
    .{
        .name = "Grenade_Launcher",
        .display_name = "40mm Grenade Launcher",
        .damage = 52,
        .damage_type = .Explosive,
        .range = 150.0,
        .rate_of_fire = 1.8,
        .accuracy = 0.76,
        .projectile_speed = 240.0,
        .area_of_effect = 14.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 10,
        .description = "Automatic grenade launcher.",
    },
    .{
        .name = "Seismic_Charge",
        .display_name = "Seismic Bomb",
        .damage = 210,
        .damage_type = .Explosive,
        .range = 360.0,
        .rate_of_fire = 0.15,
        .accuracy = 0.85,
        .projectile_speed = 240.0,
        .area_of_effect = 36.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 48,
        .description = "Ground-penetrating seismic weapon.",
    },
    .{
        .name = "Cryo_Missile",
        .display_name = "Cryogenic Missile",
        .damage = 72,
        .damage_type = .Chemical,
        .range = 280.0,
        .rate_of_fire = 0.7,
        .accuracy = 0.86,
        .projectile_speed = 440.0,
        .area_of_effect = 16.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 18,
        .description = "Super-cooled freezing weapon.",
    },
    .{
        .name = "Acid_Sprayer",
        .display_name = "Corrosive Acid",
        .damage = 48,
        .damage_type = .Chemical,
        .range = 100.0,
        .rate_of_fire = 3.5,
        .accuracy = 0.82,
        .projectile_speed = 180.0,
        .area_of_effect = 10.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 12,
        .description = "Corrosive acid weapon.",
    },
    .{
        .name = "Gas_Grenade",
        .display_name = "Tear Gas Grenade",
        .damage = 8,
        .damage_type = .Chemical,
        .range = 75.0,
        .rate_of_fire = 0.6,
        .accuracy = 0.78,
        .projectile_speed = 160.0,
        .area_of_effect = 20.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Riot control gas grenade.",
    },
    .{
        .name = "Incapacitator",
        .display_name = "Stun Weapon",
        .damage = 5,
        .damage_type = .Laser,
        .range = 90.0,
        .rate_of_fire = 4.0,
        .accuracy = 0.85,
        .projectile_speed = 9999.0,
        .area_of_effect = 6.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Non-lethal incapacitation weapon.",
    },
    .{
        .name = "EMP_Grenade",
        .display_name = "EMP Grenade",
        .damage = 12,
        .damage_type = .Explosive,
        .range = 75.0,
        .rate_of_fire = 0.5,
        .accuracy = 0.82,
        .projectile_speed = 170.0,
        .area_of_effect = 18.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 0,
        .description = "Electromagnetic pulse grenade that disables electronics.",
    },
    .{
        .name = "Smart_Missile",
        .display_name = "Smart Missile",
        .damage = 102,
        .damage_type = .Anti_Tank,
        .range = 340.0,
        .rate_of_fire = 0.48,
        .accuracy = 0.96,
        .projectile_speed = 540.0,
        .area_of_effect = 7.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 44,
        .description = "AI-guided smart missile with target tracking.",
    },
    .{
        .name = "Swarm_Missile",
        .display_name = "Swarm Missiles",
        .damage = 38,
        .damage_type = .Anti_Air,
        .range = 300.0,
        .rate_of_fire = 3.0,
        .accuracy = 0.84,
        .projectile_speed = 490.0,
        .area_of_effect = 8.0,
        .can_target_ground = true,
        .can_target_air = true,
        .penetration = 14,
        .description = "Multiple small missiles launched simultaneously.",
    },
    .{
        .name = "Neutron_Shell",
        .display_name = "Neutron Artillery Shell",
        .damage = 225,
        .damage_type = .Nuclear,
        .range = 480.0,
        .rate_of_fire = 0.12,
        .accuracy = 0.91,
        .projectile_speed = 240.0,
        .area_of_effect = 35.0,
        .can_target_ground = true,
        .can_target_air = false,
        .penetration = 55,
        .description = "Tactical neutron bomb artillery shell with radiation damage.",
    },
};

// Weapon upgrade bonuses
pub const WEAPON_UPGRADE_DATA = struct {
    advanced_training_bonus: f32 = 1.25,
    nationalism_bonus: f32 = 1.20,
    ap_bullets_bonus: f32 = 1.15,
    laser_lock_bonus: f32 = 1.30,
    composite_armor_reduction: f32 = 0.75,
    depleted_uranium_shells: f32 = 1.25,
};

pub fn getWeaponDef(name: []const u8) *const WeaponDef {
    for (&WEAPON_DATABASE) |*def| {
        if (std.mem.eql(u8, def.name, name)) return def;
    }
    return &WEAPON_DATABASE[0];
}

pub fn calculateDamage(weapon: *const WeaponDef, target_armor: u32) u32 {
    const base_damage = weapon.damage;
    const penetration_factor = @as(f32, @floatFromInt(weapon.penetration)) / @as(f32, @floatFromInt(target_armor + 1));
    const damage_multiplier = 1.0 - (@as(f32, @floatFromInt(target_armor)) * 0.01);
    const final_damage = @as(f32, @floatFromInt(base_damage)) * damage_multiplier * (1.0 + penetration_factor);
    return @intFromFloat(@max(1.0, final_damage));
}
